// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_INTERNAL_PACKAGE@@;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import okhttp3.Headers;
import okhttp3.HttpUrl;

/** JSON and parameter encoding shared by the generated code. Internal. */
public final class Utils {
    private static final ObjectMapper MAPPER = newObjectMapper();

    private Utils() {}

    public static String serializeQueryParam(Object v) {
        if (v instanceof ToQueryParam) {
            return ((ToQueryParam) v).toQueryParam();
        } else if (v instanceof OffsetDateTime) {
            return ((OffsetDateTime) v).format(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        } else if (v instanceof BigDecimal) {
            return ((BigDecimal) v).toPlainString();
        } else if (v instanceof Collection) {
            Stream<String> items = ((Collection<?>) v).stream().map(Utils::serializeQueryParam);
            // A set has no order of its own: sort it so that URLs are stable.
            if (v instanceof Set) {
                items = items.sorted();
            }
            return items.collect(Collectors.joining(","));
        } else {
            return String.valueOf(v);
        }
    }

    /**
     * Append a collection as repeated query parameters, one entry per item
     * (OpenAPI {@code explode=true} behavior, e.g. {@code ?tag=a&tag=b}).
     */
    public static void addExplodedQueryParameter(HttpUrl.Builder url, String name, Iterable<?> values) {
        for (Object item : values) {
            url.addQueryParameter(name, serializeQueryParam(item));
        }
    }

    /**
     * Append the JSON value of {@code value}: objects as {@code name[key]=value}, lists as
     * repeated {@code name=item} ({@code name[]=item} with {@code deepObject}, {@code name=a,b}
     * without {@code explode}).
     */
    public static void addStructuredQueryParameter(
            HttpUrl.Builder url, String name, Object value, boolean deepObject, boolean explode) {
        List<Map.Entry<String, String>> pairs = new ArrayList<>();
        encodeParam(name, MAPPER.valueToTree(value), deepObject, explode, pairs);
        pairs.forEach(pair -> url.addQueryParameter(pair.getKey(), pair.getValue()));
    }

    /**
     * One JSON value as query or form pairs, nested values the way Stripe-style APIs read them:
     * {@code name[key]=value}, {@code name[]=item} for lists of scalars and {@code
     * name[0][key]=value} for lists of objects. Top-level lists of scalars repeat {@code name}
     * unless {@code deepObject} or not {@code explode}.
     */
    public static void encodeParam(
            String name,
            JsonNode value,
            boolean deepObject,
            boolean explode,
            List<Map.Entry<String, String>> out) {
        boolean nested = false;
        for (JsonNode item : value) {
            nested |= item.isContainerNode();
        }
        if (value.isArray() && !deepObject && !nested) {
            List<String> texts = new ArrayList<>();
            for (JsonNode item : value) {
                if (!item.isNull()) {
                    texts.add(item.asText());
                }
            }
            if (explode) {
                texts.forEach(text -> out.add(new AbstractMap.SimpleEntry<>(name, text)));
            } else if (!texts.isEmpty()) {
                out.add(new AbstractMap.SimpleEntry<>(name, String.join(",", texts)));
            }
            return;
        }
        flattenParam(name, value, out);
    }

    private static void flattenParam(
            String prefix, JsonNode value, List<Map.Entry<String, String>> out) {
        if (value.isObject()) {
            Iterator<Map.Entry<String, JsonNode>> fields = value.fields();
            while (fields.hasNext()) {
                Map.Entry<String, JsonNode> field = fields.next();
                flattenParam(prefix + "[" + field.getKey() + "]", field.getValue(), out);
            }
        } else if (value.isArray()) {
            for (int index = 0; index < value.size(); index++) {
                JsonNode item = value.get(index);
                flattenParam(prefix + (item.isContainerNode() ? "[" + index + "]" : "[]"), item, out);
            }
        } else if (!value.isNull() && !value.isMissingNode()) {
            out.add(new AbstractMap.SimpleEntry<>(prefix, value.asText()));
        }
    }

    /**
     * {@code value} as one path segment, which the URL builder percent-encodes. Dot segments and
     * empty values are rejected: they would change the path of the request.
     */
    public static String pathSegment(String name, Object value) {
        String segment = value == null ? "" : serializeQueryParam(value);
        if (segment.isEmpty() || segment.equals(".") || segment.equals("..")) {
            throw new IllegalArgumentException(
                    "invalid path parameter `" + name + "`: \"" + segment + "\"");
        }
        return segment;
    }

    /** Implemented by an {@code ApiException} that keeps the headers of its response. */
    public interface WithResponseHeaders {
        void setResponseHeaders(Headers headers);
    }

    /** Implemented by an {@code ApiException} that keeps the body parsed as its declared schema. */
    public interface WithError {
        void setError(Object error);
    }

    public interface ToQueryParam {
        /** The value as sent in a query string, before URL encoding. */
        String toQueryParam();
    }

    /** {@code value} as JSON, with the SDK's settings. */
    public static String toJson(Object value) throws JsonProcessingException {
        return MAPPER.writeValueAsString(value);
    }

    /** Parse {@code json} into a {@code type}, with the SDK's settings. */
    public static <T> T fromJson(String json, Class<T> type) throws JsonProcessingException {
        return MAPPER.readValue(json, type);
    }

    /** {@code value} as JSON; a value the mapper cannot write is a bug, thrown unchecked. */
    public static String json(Object value) {
        try {
            return MAPPER.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** Parse {@code json} into a {@code type}, throwing {@link UncheckedIOException} if invalid. */
    public static <T> T parse(String json, Class<T> type) {
        try {
            return MAPPER.readValue(json, type);
        } catch (JsonProcessingException e) {
            throw new UncheckedIOException(e);
        }
    }

    /** The mapper the SDK uses, shared: configure a {@link #getObjectMapper()} copy instead. */
    static ObjectMapper objectMapper() {
        return MAPPER;
    }

    /**
     * A new mapper configured like the SDK's: ISO-8601 dates keeping their offset, decimals as
     * strings, unknown properties ignored.
     */
    public static ObjectMapper getObjectMapper() {
        return MAPPER.copy();
    }

    private static ObjectMapper newObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        mapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);
        mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        mapper.enable(JsonParser.Feature.INCLUDE_SOURCE_IN_LOCATION);
        mapper.registerModule(new JavaTimeModule());
        mapper.registerModule(new Jdk8Module());
        mapper.registerModule(new SimpleModule().addSerializer(new DecimalSerializer()));
        return mapper;
    }

    /** Reads a union of values told apart by their JSON type, such as {@code string | Customer}. */
    public abstract static class UnionDeserializer<T> extends StdDeserializer<T> {
        private static final long serialVersionUID = 1L;

        protected UnionDeserializer(Class<T> type) {
            super(type);
        }

        /** The variant holding {@code node}, or null when none takes its JSON type. */
        protected abstract T decode(JsonNode node, DeserializationContext ctxt) throws IOException;

        protected static <V> V read(JsonNode node, DeserializationContext ctxt, TypeReference<V> type)
                throws IOException {
            return ctxt.readTreeAsValue(node, ctxt.getTypeFactory().constructType(type));
        }

        @Override
        public T deserialize(JsonParser parser, DeserializationContext ctxt) throws IOException {
            JsonNode node = ctxt.readTree(parser);
            T value = decode(node, ctxt);
            if (value == null) {
                return ctxt.reportInputMismatch(
                        this,
                        "no variant of %s is a JSON %s",
                        handledType().getSimpleName(),
                        node.getNodeType());
            }
            return value;
        }
    }

    /** Decimals travel as strings, so that no JSON parser rounds them through a double. */
    private static final class DecimalSerializer extends StdSerializer<BigDecimal> {
        private static final long serialVersionUID = 1L;

        DecimalSerializer() {
            super(BigDecimal.class);
        }

        @Override
        public void serialize(BigDecimal value, JsonGenerator gen, SerializerProvider provider)
                throws IOException {
            gen.writeString(value.toPlainString());
        }
    }
}
