// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_PACKAGE@@;

import com.fasterxml.jackson.databind.ObjectMapper;
import @@JAVA_PACKAGE@@.exceptions.ApiException;
import @@JAVA_PACKAGE@@.streaming.EventStream;

import okhttp3.*;

import java.io.IOException;
import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.locks.LockSupport;
import java.util.UUID;

public class @@CLIENT_NAME@@HttpClient {
    private final HttpUrl baseUrl;
    private final Map<String, String> defaultHeaders;
    private final List<Long> retrySchedule;
    private final OkHttpClient client;
    private final ObjectMapper objectMapper;
    private final @@CLIENT_NAME@@Auth auth;
    private final List<List<String>> security;

    /** A client authenticating through {@code defaultHeaders} only. */
    public @@CLIENT_NAME@@HttpClient(
            HttpUrl baseUrl, Map<String, String> defaultHeaders, List<Long> retrySchedule) {
        this(baseUrl, defaultHeaders, retrySchedule, List.of(), null);
    }

    public @@CLIENT_NAME@@HttpClient(
            HttpUrl baseUrl,
            Map<String, String> defaultHeaders,
            List<Long> retrySchedule,
            List<Interceptor> interceptors) {
        this(baseUrl, defaultHeaders, retrySchedule, interceptors, null);
    }

    public @@CLIENT_NAME@@HttpClient(
            HttpUrl baseUrl,
            Map<String, String> defaultHeaders,
            List<Long> retrySchedule,
            List<Interceptor> interceptors,
            @@CLIENT_NAME@@Auth auth) {
        this(baseUrl, defaultHeaders, retrySchedule, withInterceptors(interceptors), auth, null);
    }

    private static OkHttpClient withInterceptors(List<Interceptor> interceptors) {
        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        interceptors.forEach(builder::addInterceptor);
        return builder.build();
    }

    private @@CLIENT_NAME@@HttpClient(
            HttpUrl baseUrl,
            Map<String, String> defaultHeaders,
            List<Long> retrySchedule,
            OkHttpClient client,
            @@CLIENT_NAME@@Auth auth,
            List<List<String>> security) {
        this.baseUrl = baseUrl;
        this.defaultHeaders = defaultHeaders;
        this.retrySchedule = retrySchedule;
        this.client = client;
        this.auth = auth;
        this.security = security;

        this.objectMapper = Utils.getObjectMapper();
    }

    /** A client for operations whose security requirement differs from the API-wide one. */
    public @@CLIENT_NAME@@HttpClient withSecurity(List<List<String>> security) {
        return new @@CLIENT_NAME@@HttpClient(
                baseUrl, defaultHeaders, retrySchedule, client, auth, security);
    }

    public HttpUrl.Builder newUrlBuilder() {
        return new HttpUrl.Builder()
                .scheme(baseUrl.scheme())
                .host(baseUrl.host())
                .port(baseUrl.port());
    }

    public <Req, Res> Res executeRequest(
            String method, HttpUrl url, Headers headers, Req reqBody, Class<Res> responseClass)
            throws ApiException, IOException {
        Request.Builder reqBuilder = new Request.Builder().url(url);

        // Handle request body
        String jsonBody = "";
        if (reqBody != null) {
            jsonBody = objectMapper.writeValueAsString(reqBody);
            RequestBody body = RequestBody.create(jsonBody, MediaType.parse("application/json"));
            reqBuilder.method(method, body);
        } else {
            reqBuilder.method(method, emptyBody(method));
        }

        // Add default headers
        defaultHeaders.forEach(reqBuilder::addHeader);
        if (auth != null) {
            auth.apply(reqBuilder, url, security);
        }

        String idempotencyKey = headers == null ? null : headers.get("idempotency-key");
        if ((idempotencyKey == null || idempotencyKey.isEmpty()) && "POST".equals(method.toUpperCase())) {
                reqBuilder.addHeader("idempotency-key", "auto_" + UUID.randomUUID().toString());
        }

        // Add custom headers if present
        if (headers != null) {
            headers.forEach(pair -> reqBuilder.addHeader(pair.getFirst(), pair.getSecond()));
        }

        reqBuilder.addHeader(
                "x-@@HEADER_PREFIX@@-req-id",
                String.valueOf(ThreadLocalRandom.current().nextLong(0, Long.MAX_VALUE)));

        Request request = reqBuilder.build();
        Response response = executeRequestWithRetry(request, jsonBody);

        if (response.body() == null) {
            throw new ApiException("Body is null", response.code(), "");
        }

        String bodyString = response.body().string();

        if (response.code() == 204) {
            return null;
        }

        if (response.code() >= 200 && response.code() < 300) {
            if (responseClass == null) {
                return null;
            }
            return objectMapper.readValue(bodyString, responseClass);
        }

        throw new ApiException(
                "Non 200 status code: `" + response.code() + "`",
                response.code(),
                bodyString,
                objectMapper);
    }

    /**
     * Execute a request with application/x-www-form-urlencoded body.
     */
    public <Req, Res> Res executeFormRequest(
            String method, HttpUrl url, Headers headers, Req reqBody, Class<Res> responseClass)
            throws ApiException, IOException {
        Request.Builder reqBuilder = new Request.Builder().url(url);

        // Handle form-urlencoded request body
        String formBody = "";
        if (reqBody != null) {
            Map<String, Object> fields = objectMapper.convertValue(reqBody, new com.fasterxml.jackson.core.type.TypeReference<Map<String, Object>>() {});
            FormBody.Builder formBuilder = new FormBody.Builder();
            for (Map.Entry<String, Object> entry : fields.entrySet()) {
                if (entry.getValue() != null) {
                    formBuilder.add(entry.getKey(), String.valueOf(entry.getValue()));
                }
            }
            RequestBody body = formBuilder.build();
            formBody = fields.toString();
            reqBuilder.method(method, body);
        } else {
            reqBuilder.method(method, emptyBody(method));
        }

        // Add default headers
        defaultHeaders.forEach(reqBuilder::addHeader);
        if (auth != null) {
            auth.apply(reqBuilder, url, security);
        }

        String idempotencyKey = headers == null ? null : headers.get("idempotency-key");
        if ((idempotencyKey == null || idempotencyKey.isEmpty()) && "POST".equals(method.toUpperCase())) {
                reqBuilder.addHeader("idempotency-key", "auto_" + UUID.randomUUID().toString());
        }

        // Add custom headers if present
        if (headers != null) {
            headers.forEach(pair -> reqBuilder.addHeader(pair.getFirst(), pair.getSecond()));
        }

        reqBuilder.addHeader(
                "x-@@HEADER_PREFIX@@-req-id",
                String.valueOf(ThreadLocalRandom.current().nextLong(0, Long.MAX_VALUE)));

        Request request = reqBuilder.build();
        Response response = executeRequestWithRetry(request, formBody);

        if (response.body() == null) {
            throw new ApiException("Body is null", response.code(), "");
        }

        String bodyString = response.body().string();

        if (response.code() == 204) {
            return null;
        }

        if (response.code() >= 200 && response.code() < 300) {
            if (responseClass == null) {
                return null;
            }
            return objectMapper.readValue(bodyString, responseClass);
        }

        throw new ApiException(
                "Non 200 status code: `" + response.code() + "`",
                response.code(),
                bodyString,
                objectMapper);
    }

    /**
     * Execute a request that returns binary data (e.g., PDF downloads).
     */
    public <Req> byte[] executeBinaryRequest(
            String method, HttpUrl url, Headers headers, Req reqBody)
            throws ApiException, IOException {
        Request.Builder reqBuilder = new Request.Builder().url(url);

        // Handle request body
        String jsonBody = "";
        if (reqBody != null) {
            jsonBody = objectMapper.writeValueAsString(reqBody);
            RequestBody body = RequestBody.create(jsonBody, MediaType.parse("application/json"));
            reqBuilder.method(method, body);
        } else {
            reqBuilder.method(method, emptyBody(method));
        }

        // Add default headers
        defaultHeaders.forEach(reqBuilder::addHeader);
        if (auth != null) {
            auth.apply(reqBuilder, url, security);
        }

        // Add custom headers if present
        if (headers != null) {
            headers.forEach(pair -> reqBuilder.addHeader(pair.getFirst(), pair.getSecond()));
        }

        reqBuilder.addHeader(
                "x-@@HEADER_PREFIX@@-req-id",
                String.valueOf(ThreadLocalRandom.current().nextLong(0, Long.MAX_VALUE)));

        Request request = reqBuilder.build();
        Response response = executeRequestWithRetry(request, jsonBody);

        if (response.body() == null) {
            throw new ApiException("Body is null", response.code(), "");
        }

        if (response.code() >= 200 && response.code() < 300) {
            return response.body().bytes();
        }

        String bodyString = response.body().string();
        throw new ApiException(
                "Non 200 status code: `" + response.code() + "`",
                response.code(),
                bodyString,
                objectMapper);
    }

    /**
     * Execute a request with a raw or multipart body. Streamed bodies are sent once, without
     * retries.
     */
    public <Res> Res executeBodyRequest(
            String method, HttpUrl url, Headers headers, RequestBody body, Class<Res> responseClass)
            throws ApiException, IOException {
        Request request = buildRequest(method, url, headers, body);
        Response response = retry(request, client.newCall(request).execute(), client);
        try (response) {
            String bodyString = response.body() == null ? "" : response.body().string();
            if (response.code() >= 200 && response.code() < 300) {
                return responseClass == null || bodyString.isEmpty()
                        ? null
                        : objectMapper.readValue(bodyString, responseClass);
            }
            throw new ApiException(
                    "Non 200 status code: `" + response.code() + "`",
                    response.code(),
                    bodyString,
                    objectMapper);
        }
    }

    /** Open a {@code text/event-stream} response. The read timeout does not apply to it. */
    public EventStream executeEventStream(String method, HttpUrl url, Headers headers)
            throws ApiException, IOException {
        OkHttpClient streaming = client.newBuilder().readTimeout(Duration.ZERO).build();
        Request.Builder builder = buildRequest(method, url, headers, null).newBuilder();
        Request request = builder.header("Accept", "text/event-stream").build();
        Response response = retry(request, streaming.newCall(request).execute(), streaming);
        if (response.code() < 200 || response.code() >= 300) {
            String bodyString = response.body() == null ? "" : response.body().string();
            response.close();
            throw new ApiException(
                    "Non 200 status code: `" + response.code() + "`",
                    response.code(),
                    bodyString,
                    objectMapper);
        }
        MediaType contentType = response.body().contentType();
        if (contentType == null || !"text/event-stream".equals(contentType.type() + "/" + contentType.subtype())) {
            response.close();
            throw new IOException("expected a text/event-stream response, got " + contentType);
        }
        return new EventStream(response);
    }

    private Request buildRequest(String method, HttpUrl url, Headers headers, RequestBody body) {
        Request.Builder reqBuilder = new Request.Builder().url(url);
        reqBuilder.method(method, body != null ? body : emptyBody(method));
        defaultHeaders.forEach(reqBuilder::addHeader);
        if (auth != null) {
            auth.apply(reqBuilder, url, security);
        }
        String idempotencyKey = headers == null ? null : headers.get("idempotency-key");
        if ((idempotencyKey == null || idempotencyKey.isEmpty()) && "POST".equals(method.toUpperCase())) {
            reqBuilder.addHeader("idempotency-key", "auto_" + UUID.randomUUID().toString());
        }
        if (headers != null) {
            headers.forEach(pair -> reqBuilder.addHeader(pair.getFirst(), pair.getSecond()));
        }
        reqBuilder.addHeader(
                "x-@@HEADER_PREFIX@@-req-id",
                String.valueOf(ThreadLocalRandom.current().nextLong(0, Long.MAX_VALUE)));
        return reqBuilder.build();
    }

    private Response retry(Request request, Response response, OkHttpClient http)
            throws IOException {
        RequestBody body = request.body();
        int retryCount = 0;
        while (response.code() >= 500
                && retryCount < retrySchedule.size()
                && (body == null || !body.isOneShot())) {
            response.close();
            LockSupport.parkNanos(retrySchedule.get(retryCount) * 1_000_000);
            Request retryRequest =
                    request.newBuilder()
                            .header("x-@@HEADER_PREFIX@@-retry-count", String.valueOf(retryCount + 1))
                            .build();
            response = http.newCall(retryRequest).execute();
            retryCount++;
        }
        return response;
    }

    private static RequestBody emptyBody(String method) {
        boolean needsBody = List.of("POST", "PUT", "PATCH").contains(method.toUpperCase());
        return needsBody ? RequestBody.create(new byte[0]) : null;
    }

    private Response executeRequestWithRetry(Request request, String body) throws IOException {
        Response response = client.newCall(request).execute();

        int retryCount = 0;
        while (response.code() >= 500 && retryCount < retrySchedule.size()) {
            response.close();

            // Use LockSupport for precise parking instead of Thread.sleep
            LockSupport.parkNanos(retrySchedule.get(retryCount) * 1_000_000); // Convert ms to ns

            Request retryRequest =
                    request.newBuilder()
                            .header("x-@@HEADER_PREFIX@@-retry-count", String.valueOf(retryCount + 1))
                            .build();
            response = client.newCall(retryRequest).execute();
            retryCount++;
        }
        return response;
    }
}
