// this file is @generated by Perseid; edit the shared runtime template.

/** How `int64` values are typed, set by `int64` in the `[typescript]` table of perseid.toml. */
const INT64 = "@@INT64@@" as "number" | "bigint" | "string";

const TOKEN = /"(?:[^"\\]|\\.)*"|-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?/g;
const BIGINT_MARK = "\u0000bigint:";
const BIGINT_MARKED = /"\\u0000bigint:(-?\d+)"/g;

/**
 * `JSON.parse`, except that when int64 values are `bigint` or `string`, integers beyond
 * `Number.MAX_SAFE_INTEGER` are read as strings so that the models keep every digit.
 */
export function parseJson(text: string): any {
  if (INT64 === "number" || !/\d{16}/.test(text)) {
    return JSON.parse(text);
  }
  return JSON.parse(
    text.replace(TOKEN, (token) =>
      token[0] !== '"' && /^-?\d+$/.test(token) && !Number.isSafeInteger(Number(token))
        ? `"${token}"`
        : token
    )
  );
}

/** `JSON.stringify`, writing `bigint` values as JSON integers. */
export function stringifyJson(value: unknown): string {
  let bigints = false;
  const json = JSON.stringify(value, (_key, item) => {
    if (typeof item !== "bigint") {
      return item;
    }
    bigints = true;
    return `${BIGINT_MARK}${item}`;
  });
  return bigints ? json.replace(BIGINT_MARKED, "$1") : json;
}

/** @internal Whether a union holds its object variant: not a scalar, list or `Date`. */
export function isJsonObject<T>(
  value: T
): value is Exclude<T, string | number | boolean | bigint | unknown[] | Date | null | undefined> {
  return (
    typeof value === "object" && value !== null && !Array.isArray(value) && !(value instanceof Date)
  );
}

/**
 * @internal The properties of `object` other than `known` (property names): those the API
 * sends or accepts that this SDK version does not know, kept as they are.
 */
export function extraProperties(object: unknown, known: readonly string[]): object {
  const extra = {};
  if (isJsonObject(object)) {
    for (const [key, value] of Object.entries(object as Record<string, unknown>)) {
      if (!known.includes(key)) {
        Object.defineProperty(extra, key, { value, enumerable: true, writable: true, configurable: true });
      }
    }
  }
  return extra;
}

/**
 * @internal The properties of `object` named in `keys`: a base model's own, without the ones
 * it took for unknown.
 */
export function pickProperties<T extends object>(object: T, keys: readonly string[]): T {
  return Object.fromEntries(Object.entries(object).filter(([key]) => keys.includes(key))) as T;
}

/** @internal The properties of `object` other than those named in `keys`, set again after. */
export function omitProperties<T extends object>(object: T, keys: readonly string[]): T {
  return Object.fromEntries(Object.entries(object).filter(([key]) => !keys.includes(key))) as T;
}
