// this file is @generated by Perseid; edit the shared runtime template.
/** How a list operation pages. Paths are JSON property names from the response root. */
export type Pagination = {
  style: "cursor" | "page" | "offset";
  items: string[];
  nextCursor?: string[];
  itemCursor?: string;
  hasMore?: string[];
  totalPages?: string[];
  total?: string[];
  firstPage: number;
};

function at(value: any, path: string[] | undefined): any {
  for (const key of path ?? []) {
    value = value?.[key];
  }
  return value;
}

/**
 * Yields every item of a paginated operation, fetching the next page once the
 * current one is consumed. `start` is the page parameter of the first request.
 */
export async function* paginate<P, T>(
  pagination: Pagination,
  start: any,
  fetchPage: (param: any) => Promise<P>,
  pageToJson: (page: P) => any,
  itemFromJson: (json: any) => T
): AsyncGenerator<T, void, undefined> {
  const { style } = pagination;
  let param = start ?? (style === "page" ? pagination.firstPage : style === "offset" ? 0 : undefined);
  for (;;) {
    const page = pageToJson(await fetchPage(param));
    const items: any[] = at(page, pagination.items) ?? [];
    for (const item of items) {
      yield itemFromJson(item);
    }
    if (items.length === 0 || (pagination.hasMore && at(page, pagination.hasMore) === false)) {
      return;
    }
    if (style === "cursor") {
      const next = pagination.nextCursor
        ? at(page, pagination.nextCursor)
        : items[items.length - 1][pagination.itemCursor!];
      if (next === undefined || next === null || next === "" || next === param) {
        return;
      }
      param = next;
    } else if (style === "page") {
      const totalPages = at(page, pagination.totalPages);
      if (typeof totalPages === "number" && param - pagination.firstPage + 1 >= totalPages) {
        return;
      }
      param += 1;
    } else {
      param += items.length;
      const total = at(page, pagination.total);
      if (typeof total === "number" && param >= total) {
        return;
      }
    }
  }
}
