// this file is @generated by Perseid; edit the shared runtime template.
import { v4 as uuidv4 } from "uuid";
import { applyAuth, type Credentials, type Security, type SecurityScheme } from "./auth";
import { type Middleware, withMiddleware } from "./middleware";
import { EventStream, type MultipartBody, type UploadBody } from "./streaming";
import { ApiException, type XOR } from "./util";

export const LIB_VERSION = "@@VERSION@@"; // x-release-please-version
const USER_AGENT = `@@USER_AGENT_PREFIX@@-typescript/${LIB_VERSION}`;

export enum HttpMethod {
  GET = "GET",
  HEAD = "HEAD",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
  CONNECT = "CONNECT",
  OPTIONS = "OPTIONS",
  TRACE = "TRACE",
  PATCH = "PATCH",
}

export type @@CLIENT_NAME@@RequestContext = {
  /** The API base URL, like "@@DEFAULT_BASE_URL@@" */
  baseUrl: string;
  /** Security schemes of the API, and the requirement of operations that declare none. */
  auth: { schemes: Record<string, SecurityScheme>; security: Security };
  /** Time in milliseconds to wait for requests to get a response. */
  timeout?: number;
  /** Write a one-line summary of every request and response to stderr. */
  debug?: boolean;
  /**
   * Custom fetch implementation to use for HTTP requests.
   * Useful for testing, adding custom middleware, or running in non-standard environments.
   */
  fetch?: typeof fetch;
  /** Wraps every HTTP attempt: caching, logging, custom headers. */
  middleware?: Middleware[];
} & Credentials &
  XOR<
  {
    /** List of delays (in milliseconds) to wait before each retry attempt. */
    retryScheduleInMs?: number[];
  },
  {
    /**
     * The number of times the client will retry if a server-side error
     * or timeout is received.
     * Default: 2
     */
    numRetries?: number;
  }
>;

type ScalarQueryParameter = string | boolean | number | Date;
type QueryParameter = ScalarQueryParameter | ScalarQueryParameter[] | null | undefined;

function encodeQueryParamValue(name: string, value: ScalarQueryParameter): string {
  if (typeof value === "string") {
    return value;
  }
  if (typeof value === "boolean" || typeof value === "number") {
    return value.toString();
  }
  if (value instanceof Date) {
    return value.toISOString();
  }
  throw new Error(`query parameter ${name} has unsupported type`);
}

export class @@CLIENT_NAME@@Request {
  constructor(
    private readonly method: HttpMethod,
    private path: string
  ) {}

  private body?: BodyInit;
  private bodyContentType = "application/json";
  private oneShot = false;
  private queryParams: [string, string][] = [];
  private headerParams: Record<string, string> = {};
  private security?: Security;

  public setPathParam(name: string, value: string) {
    const newPath = this.path.replace(`{${name}}`, encodeURIComponent(value));
    if (this.path === newPath) {
      throw new Error(`path parameter ${name} not found`);
    }
    this.path = newPath;
  }

  public setQueryParams(params: { [name: string]: QueryParameter }) {
    for (const [name, value] of Object.entries(params)) {
      this.setQueryParam(name, value);
    }
  }

  /**
   * Set a query parameter. Array values are comma-joined
   * (OpenAPI `style: form, explode: false`).
   */
  public setQueryParam(name: string, value: QueryParameter) {
    if (value === undefined || value === null) {
      return;
    }

    if (Array.isArray(value)) {
      if (value.length > 0) {
        this.queryParams.push([
          name,
          value.map((item) => encodeQueryParamValue(name, item)).join(","),
        ]);
      }
      return;
    }

    this.queryParams.push([name, encodeQueryParamValue(name, value)]);
  }

  /**
   * Append an array value as repeated query parameters
   * (OpenAPI `style: form, explode: true`), e.g. `?status=a&status=b`.
   */
  public setExplodedQueryParam(name: string, values?: ScalarQueryParameter[] | null) {
    if (values === undefined || values === null) {
      return;
    }

    for (const value of values) {
      this.queryParams.push([name, encodeQueryParamValue(name, value)]);
    }
  }

  /** Override the API-wide security requirement for this operation. */
  public setSecurity(security: Security) {
    this.security = security;
  }

  public setHeaderParam(name: string, value?: string) {
    if (value === undefined) {
      return;
    }

    this.headerParams[name] = value;
  }

  /** Set a JSON request body. */
  public setBody(value: any) {
    this.body = JSON.stringify(value);
    this.bodyContentType = "application/json";
  }

  /** Set an `application/x-www-form-urlencoded` request body. */
  public setFormBody(value: Record<string, any>) {
    const params = new URLSearchParams();
    for (const [name, item] of Object.entries(value)) {
      if (item === undefined || item === null) {
        continue;
      }
      if (Array.isArray(item)) {
        for (const inner of item) {
          params.append(name, String(inner));
        }
      } else {
        params.append(name, String(item));
      }
    }
    this.body = params.toString();
    this.bodyContentType = "application/x-www-form-urlencoded";
  }

  /** Set a raw `application/octet-stream` body. */
  public setUploadBody(value: UploadBody) {
    this.body = value as BodyInit;
    this.bodyContentType = "application/octet-stream";
    this.oneShot = typeof ReadableStream !== "undefined" && value instanceof ReadableStream;
  }

  /** Set a `multipart/form-data` body. */
  public setMultipartBody(value: MultipartBody) {
    this.body = value.blob();
    this.bodyContentType = `multipart/form-data; boundary=${value.boundary}`;
  }

  /**
   * Send this request, returning the request body as a caller-specified type.
   *
   * If the server returns a non-2xx status, an `ApiException` is thrown (see its
   * documentation for how the error body is exposed).
   *
   * If the server returns a 5xx error, the request is retried up to two times with
   * exponential backoff. If retries are exhausted, an `ApiException` is thrown.
   */
  public async send<R>(
    ctx: @@CLIENT_NAME@@RequestContext,
    parseResponseBody: (jsonObject: any) => R
  ): Promise<R> {
    const response = await this.sendInner(ctx);
    if (response.status === 204) {
      return <R>(<unknown>null);
    }
    const responseBody = await response.text();
    return parseResponseBody(JSON.parse(responseBody));
  }

  /** Same as `send`, but the response body is returned as raw bytes. */
  public async sendBinary(ctx: @@CLIENT_NAME@@RequestContext): Promise<Uint8Array> {
    const response = await this.sendInner(ctx);
    return new Uint8Array(await response.arrayBuffer());
  }

  /** Same as `send`, but the response body is returned as text. */
  public async sendText(ctx: @@CLIENT_NAME@@RequestContext): Promise<string> {
    const response = await this.sendInner(ctx);
    return await response.text();
  }

  /** Same as `send`, but the response is a live event stream. The timeout covers opening it. */
  public async sendEventStream(ctx: @@CLIENT_NAME@@RequestContext): Promise<EventStream> {
    this.headerParams.accept = "text/event-stream";
    const response = await this.sendInner(ctx, true);
    const contentType = response.headers.get("content-type") ?? "";
    if (contentType.split(";")[0].trim().toLowerCase() !== "text/event-stream") {
      await response.body?.cancel();
      throw new Error(`expected a text/event-stream response, got ${contentType}`);
    }
    return new EventStream(response);
  }

  /** Same as `send`, but the response body is discarded, not parsed. */
  public async sendNoResponseBody(ctx: @@CLIENT_NAME@@RequestContext): Promise<void> {
    await this.sendInner(ctx);
  }

  private async sendInner(
    ctx: @@CLIENT_NAME@@RequestContext,
    stream = false
  ): Promise<Response> {
    const url = new URL(ctx.baseUrl + this.path);
    for (const [name, value] of this.queryParams) {
      url.searchParams.append(name, value);
    }

    if (
      this.headerParams["idempotency-key"] === undefined &&
      this.method.toUpperCase() === "POST"
    ) {
      this.headerParams["idempotency-key"] = `auto_${uuidv4()}`;
    }

    const randomId = Math.floor(Math.random() * Number.MAX_SAFE_INTEGER);

    if (this.body != null) {
      this.headerParams["content-type"] = this.bodyContentType;
    }

    const authHeaders: Record<string, string> = {};
    await applyAuth(
      ctx.auth.schemes,
      this.security ?? ctx.auth.security,
      ctx,
      authHeaders,
      url
    );

    // Cloudflare Workers fail if the credentials option is used in a fetch call.
    const isCredentialsSupported = "credentials" in Request.prototype;
    const opening = stream && ctx.timeout !== undefined ? new AbortController() : undefined;
    const openTimer = opening && setTimeout(() => opening.abort(), ctx.timeout);
    const timeoutSignal =
      ctx.timeout !== undefined && !stream ? AbortSignal.timeout(ctx.timeout) : undefined;

    const response = await sendWithRetry(
      url,
      {
        method: this.method.toString(),
        body: this.body,
        headers: {
          accept: "application/json, */*;q=0.8",
          ...authHeaders,
          "user-agent": USER_AGENT,
          "@@HEADER_PREFIX@@-req-id": randomId.toString(),
          ...this.headerParams,
        },
        credentials: isCredentialsSupported ? "same-origin" : undefined,
        signal: opening?.signal ?? timeoutSignal,
        ...(this.oneShot ? { duplex: "half" } : {}),
      },
      ctx.retryScheduleInMs,
      ctx.retryScheduleInMs?.[0],
      // An explicit check (not `||`) so that `numRetries: 0` and an empty retry
      // schedule really disable retries instead of falling back to the default.
      this.oneShot
        ? 0
        : ctx.retryScheduleInMs !== undefined
          ? ctx.retryScheduleInMs.length
          : ctx.numRetries,
      withMiddleware(ctx.fetch, ctx.middleware),
      ctx.debug
    ).finally(() => clearTimeout(openTimer));
    return filterResponseForErrors(response);
  }
}

async function filterResponseForErrors(response: Response): Promise<Response> {
  if (response.status < 300) {
    return response;
  }
  throw new ApiException(response.status, await response.text(), response.headers);
}

type @@CLIENT_NAME@@RequestInit = RequestInit & {
  headers: Record<string, string>;
};

async function sendWithRetry(
  url: URL,
  init: @@CLIENT_NAME@@RequestInit,
  retryScheduleInMs?: number[],
  nextInterval = 50,
  triesLeft = 2,
  fetchImpl: typeof fetch = fetch,
  debug = false,
  retryCount = 1
): Promise<Response> {
  const sleep = (interval: number) =>
    new Promise((resolve) => setTimeout(resolve, interval));

  if (debug) {
    console.error(`@@PACKAGE_NAME@@: ${init.method} ${url} (attempt ${retryCount})`);
  }

  try {
    const response = await fetchImpl(url, init);
    if (debug) {
      console.error(`@@PACKAGE_NAME@@: ${init.method} ${url} -> ${response.status}`);
    }
    if (triesLeft <= 0 || response.status < 500) {
      return response;
    }
  } catch (e) {
    if (debug) {
      console.error(`@@PACKAGE_NAME@@: ${init.method} ${url} failed: ${e}`);
    }
    if (triesLeft <= 0) {
      throw e;
    }
  }

  await sleep(nextInterval);
  init.headers["@@HEADER_PREFIX@@-retry-count"] = retryCount.toString();
  nextInterval = retryScheduleInMs?.[retryCount] ?? nextInterval * 2;
  return await sendWithRetry(
    url,
    init,
    retryScheduleInMs,
    nextInterval,
    --triesLeft,
    fetchImpl,
    debug,
    ++retryCount
  );
}
