use std::{
    io::{BufRead, BufReader, Write},
    net::{TcpListener, TcpStream},
    sync::mpsc,
    time::{Duration, Instant, SystemTime, UNIX_EPOCH},
};

use anyhow::{Context, Result, bail};
use crypto_box::aead::{OsRng, rand_core::RngCore};
use jsonwebtoken::{Algorithm, EncodingKey, Header};
use serde_json::{Value, json};

use super::{Ui, api::GitHub, api::web_base};

const WAIT: Duration = Duration::from_secs(15 * 60);

pub struct App {
    pub id: String,
    pub slug: Option<String>,
    /// Only known right after the App is created: GitHub never shows it again.
    pub pem: Option<String>,
}

pub struct Owner {
    pub login: String,
    pub organization: bool,
}

/// Creates the App through GitHub's manifest flow, a browser round trip to a local callback.
pub fn create(owner: &Owner, spec: &str, name: &str, ui: &Ui) -> Result<App> {
    let listener = TcpListener::bind("127.0.0.1:0").context("listening for GitHub's callback")?;
    let port = listener.local_addr()?.port();
    let mut bytes = [0u8; 16];
    OsRng.fill_bytes(&mut bytes);
    let state: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
    let web = web_base();
    let target = match owner.organization {
        true => format!(
            "{web}/organizations/{}/settings/apps/new?state={state}",
            owner.login
        ),
        false => format!("{web}/settings/apps/new?state={state}"),
    };
    let home = format!("https://github.com/{spec}");
    let manifest = json!({
        "name": format!("{name}-sdk-bot"),
        "url": home,
        "description": format!("Opens the {name} SDK pull requests generated by perseid."),
        "hook_attributes": { "url": home, "active": false },
        "redirect_url": format!("http://127.0.0.1:{port}/callback"),
        "public": false,
        "default_permissions": {
            "contents": "write",
            "pull_requests": "write",
            "metadata": "read",
        },
    });
    let page = format!(
        r#"<!doctype html><meta charset="utf-8"><title>perseid</title>
<form id="app" method="post" action="{}"><input type="hidden" name="manifest" value="{}">
<p>Taking you to GitHub to create the App… <button>Continue</button></p></form>
<script>document.getElementById("app").submit()</script>"#,
        escape(&target),
        escape(&manifest.to_string())
    );
    let local = format!("http://127.0.0.1:{port}/");
    ui.say(&format!(
        "Create the GitHub App that will open SDK pull requests: {local}"
    ));
    ui.open(&local);
    let code = callback(&listener, &page, &state)?;
    let app = GitHub::new(None).post(&format!("/app-manifests/{code}/conversions"), json!({}))?;
    let (Some(id), Some(slug), Some(pem)) = (
        app["id"].as_u64(),
        app["slug"].as_str(),
        app["pem"].as_str(),
    ) else {
        bail!("GitHub created the App but sent back no id, slug or key");
    };
    ui.ok(&format!("Created the GitHub App {slug}"));
    Ok(App {
        id: id.to_string(),
        slug: Some(slug.to_owned()),
        pem: Some(pem.to_owned()),
    })
}

/// Serves the page posting the manifest and waits for GitHub's redirect, returning its code.
fn callback(listener: &TcpListener, page: &str, state: &str) -> Result<String> {
    listener.set_nonblocking(true)?;
    let deadline = Instant::now() + WAIT;
    while Instant::now() < deadline {
        let stream = match listener.accept() {
            Ok((stream, _)) => stream,
            Err(e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                std::thread::sleep(Duration::from_millis(100));
                continue;
            }
            Err(e) => return Err(e.into()),
        };
        if let Some(code) = answer(stream, page, state)? {
            return Ok(code);
        }
    }
    bail!("the GitHub App wasn't created within 15 minutes, run the command again")
}

fn answer(mut stream: TcpStream, page: &str, state: &str) -> Result<Option<String>> {
    stream.set_nonblocking(false)?;
    stream.set_read_timeout(Some(Duration::from_secs(10)))?;
    let mut reader = BufReader::new(&stream);
    let mut line = String::new();
    reader.read_line(&mut line)?;
    let mut header = String::new();
    while reader.read_line(&mut header)? > 2 {
        header.clear();
    }
    let target = line.split_whitespace().nth(1).unwrap_or("/");
    let (path, query) = target.split_once('?').unwrap_or((target, ""));
    let param = |name: &str| {
        query
            .split('&')
            .find_map(|pair| pair.strip_prefix(name)?.strip_prefix('='))
    };
    let (status, body, code) = match path {
        "/" => ("200 OK", page.to_owned(), None),
        "/callback" if param("state") == Some(state) => match param("code") {
            Some(code) => (
                "200 OK",
                "<!doctype html><meta charset=\"utf-8\"><p>The App is created, back to the terminal.</p>".to_owned(),
                Some(code.to_owned()),
            ),
            None => ("400 Bad Request", "no code".to_owned(), None),
        },
        "/callback" => ("400 Bad Request", "unexpected state".to_owned(), None),
        _ => ("404 Not Found", String::new(), None),
    };
    write!(
        stream,
        "HTTP/1.1 {status}\r\nContent-Type: text/html; charset=utf-8\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",
        body.len()
    )?;
    Ok(code)
}

fn escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('"', "&quot;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// A short-lived JWT authenticating as the App itself.
fn jwt(id: &str, key: &EncodingKey) -> Result<String> {
    let now = SystemTime::now().duration_since(UNIX_EPOCH)?.as_secs();
    let iss = id
        .parse::<u64>()
        .map_or_else(|_| Value::from(id), Value::from);
    let claims = json!({ "iat": now - 60, "exp": now + 540, "iss": iss });
    Ok(jsonwebtoken::encode(
        &Header::new(Algorithm::RS256),
        &claims,
        key,
    )?)
}

/// Sends the user to the App's installation page and waits until it covers `repos`.
pub fn install(app: &App, owner: &Owner, repos: &[String], ui: &Ui) -> Result<()> {
    let web = web_base();
    let url = match (&app.slug, owner.organization) {
        (Some(slug), _) => format!("{web}/apps/{slug}/installations/new"),
        (None, true) => format!("{web}/organizations/{}/settings/installations", owner.login),
        (None, false) => format!("{web}/settings/installations"),
    };
    let names: Vec<_> = repos
        .iter()
        .map(|r| r.rsplit('/').next().unwrap_or(r))
        .collect();
    let Some(pem) = &app.pem else {
        ui.say(&format!(
            "Make sure the App is installed on {}: {url}",
            names.join(", ")
        ));
        if !ui.yes {
            ui.pause("Press enter once it is")?;
        }
        return Ok(());
    };
    let key = EncodingKey::from_rsa_pem(pem.as_bytes()).context("reading the App's key")?;
    ui.say(&format!(
        "Install the App on {}, choosing \"Only select repositories\": {}",
        owner.login,
        names.join(", ")
    ));
    ui.info(&url);
    ui.open(&url);
    ui.info("Waiting for the installation (press enter once done)…");
    let (enter, pressed) = mpsc::channel();
    std::thread::spawn(move || {
        while std::io::stdin()
            .lock()
            .read_line(&mut String::new())
            .unwrap_or(0)
            > 0
        {
            if enter.send(()).is_err() {
                break;
            }
        }
    });
    let deadline = Instant::now() + WAIT;
    let mut asked = false;
    loop {
        let jwt = GitHub::new(Some(jwt(&app.id, &key)?));
        let mut missing = Vec::new();
        for repo in repos {
            let path = format!("/repos/{repo}/installation");
            let reply = jwt.send("GET", &path, None)?;
            if reply.status == 404 {
                missing.push(repo.as_str());
            } else {
                super::api::check("GET", &path, reply)?;
            }
        }
        if missing.is_empty() {
            ui.ok(&format!("The App is installed on {}", names.join(", ")));
            return Ok(());
        }
        if asked {
            ui.warn(&format!("Not installed on {} yet", missing.join(", ")));
        }
        if Instant::now() > deadline {
            bail!(
                "the App isn't installed on {} yet: install it from {url}, then run `perseid setup-github` again",
                missing.join(", ")
            );
        }
        asked = pressed.recv_timeout(Duration::from_secs(2)).is_ok();
    }
}

pub fn owner(api: &GitHub, login: &str) -> Result<Owner> {
    let user: Value = api.get(&format!("/users/{login}"))?;
    Ok(Owner {
        login: user["login"].as_str().unwrap_or(login).to_owned(),
        organization: user["type"] == "Organization",
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn manifests_are_escaped_into_the_form() {
        assert_eq!(
            escape(r#"{"a":"<b>&"}"#),
            "{&quot;a&quot;:&quot;&lt;b&gt;&amp;&quot;}"
        );
    }
}
