// this file is @generated by Perseid; edit the shared runtime template.
using System;
using System.Net.Http;
using System.Threading;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace @@PACKAGE_NAME@@;

/// <summary>Registers the client with <c>Microsoft.Extensions.DependencyInjection</c>.</summary>
public static class @@CLIENT_NAME@@ServiceCollectionExtensions
{
    private static readonly Action<ILogger, string, string, string, long, int, Exception?> s_attempt =
        LoggerMessage.Define<string, string, string, long, int>(
            LogLevel.Debug,
            new EventId(1, "HttpAttempt"),
            "{Method} {Url}: {Outcome} in {ElapsedMs} ms, attempt {Attempt}"
        );

    private static readonly Action<ILogger, string, string, string, long, long, Exception?> s_retry =
        LoggerMessage.Define<string, string, string, long, long>(
            LogLevel.Information,
            new EventId(2, "HttpRetry"),
            "{Method} {Url}: {Outcome} in {ElapsedMs} ms, retried in {DelayMs} ms"
        );

    private static readonly Action<ILogger, string, string, string, long, Exception?> s_renewal =
        LoggerMessage.Define<string, string, string, long>(
            LogLevel.Debug,
            new EventId(3, "HttpTokenRenewal"),
            "{Method} {Url}: {Outcome} in {ElapsedMs} ms, retried with a renewed access token"
        );

    /// <summary>
    /// Registers <see cref="@@CLIENT_NAME@@Client"/> and <see cref="I@@CLIENT_NAME@@Client"/> as a typed
    /// client of <c>IHttpClientFactory</c>, configured by <paramref name="configure"/> and any
    /// <c>Configure&lt;@@CLIENT_NAME@@ClientOptions&gt;</c> call.
    /// </summary>
    /// <remarks>
    /// The <c>HttpClient</c> has no timeout of its own: the client applies
    /// <see cref="@@CLIENT_NAME@@ClientOptions.Timeout"/> or the per-call one to each attempt.
    /// Add middleware to the returned builder with <c>AddHttpMessageHandler</c>, not to
    /// <see cref="@@CLIENT_NAME@@ClientOptions.Handlers"/>, and leave
    /// <see cref="@@CLIENT_NAME@@ClientOptions.HttpMessageHandler"/> unset. Unless
    /// <see cref="@@CLIENT_NAME@@ClientOptions.Log"/> is set, attempts are logged to the
    /// <c>@@PACKAGE_NAME@@</c> category of the container's <see cref="ILoggerFactory"/>.
    /// </remarks>
    /// <param name="services">The service collection.</param>
    /// <param name="configure">Sets the token, base URL, timeout or retries.</param>
    /// <returns>The builder of the named <c>HttpClient</c>, to add handlers or resilience to.</returns>
    public static IHttpClientBuilder Add@@CLIENT_NAME@@Client(
        this IServiceCollection services,
        Action<@@CLIENT_NAME@@ClientOptions>? configure = null
    )
    {
        ArgumentNullException.ThrowIfNull(services);
        var options = services.AddOptions<@@CLIENT_NAME@@ClientOptions>();
        if (configure is not null)
        {
            options.Configure(configure);
        }
        options.Configure<ILoggerFactory>(
            (settings, loggers) => settings.Log ??= LogTo(loggers.CreateLogger("@@PACKAGE_NAME@@"))
        );
        services.AddTransient<I@@CLIENT_NAME@@Client>(provider =>
            provider.GetRequiredService<@@CLIENT_NAME@@Client>()
        );
        var builder = services.AddHttpClient(
            nameof(@@CLIENT_NAME@@Client),
            http => http.Timeout = Timeout.InfiniteTimeSpan
        );
        builder.AddTypedClient(
            (HttpClient http, IServiceProvider provider) =>
            {
                var settings = provider.GetRequiredService<IOptions<@@CLIENT_NAME@@ClientOptions>>().Value;
                if (settings.Handlers.Count > 0 || settings.HttpMessageHandler is not null)
                {
                    throw new InvalidOperationException(
                        "with dependency injection, add middleware with AddHttpMessageHandler on the builder Add@@CLIENT_NAME@@Client returns"
                    );
                }
                return new @@CLIENT_NAME@@Client(http, null, settings);
            }
        );
        return builder;
    }

    /// <summary>Logs attempts to <paramref name="logger"/>: at debug level, retried ones at
    /// information level, and those repeated with a renewed access token at debug level.</summary>
    /// <param name="logger">The logger.</param>
    /// <returns>A <see cref="@@CLIENT_NAME@@ClientOptions.Log"/> callback.</returns>
    public static Action<ApiAttempt> LogTo(ILogger logger)
    {
        ArgumentNullException.ThrowIfNull(logger);
        return attempt =>
        {
            var elapsed = (long)attempt.Elapsed.TotalMilliseconds;
            if (attempt.RetryIn is { } delay)
            {
                s_retry(logger, attempt.Method, attempt.Url, attempt.Outcome, elapsed, (long)delay.TotalMilliseconds, null);
            }
            else if (attempt.TokenRenewed)
            {
                s_renewal(logger, attempt.Method, attempt.Url, attempt.Outcome, elapsed, null);
            }
            else
            {
                s_attempt(logger, attempt.Method, attempt.Url, attempt.Outcome, elapsed, attempt.Attempt, null);
            }
        };
    }
}
