// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_PACKAGE@@.streaming;

import com.fasterxml.jackson.databind.JsonNode;
import @@JAVA_INTERNAL_PACKAGE@@.Utils;

import java.nio.charset.StandardCharsets;

import okhttp3.Headers;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.RequestBody;

/** Builds a {@code multipart/form-data} body. Null fields are left out. */
public final class Multipart {
    private final MultipartBody.Builder builder = new MultipartBody.Builder().setType(MultipartBody.FORM);

    /** An empty form. */
    public Multipart() {}

    /**
     * Adds a field: scalars as text, objects as JSON, lists as one part per item.
     *
     * @param name the field name
     * @param value the value, left out when null
     * @return this form
     */
    public Multipart field(String name, Object value) {
        return field(name, value, null);
    }

    /**
     * Like {@link #field(String, Object)}, with the media type the spec declares for the part.
     *
     * @param name the field name
     * @param value the value, left out when null
     * @param contentType the declared media type, or null
     * @return this form
     */
    public Multipart field(String name, Object value, String contentType) {
        if (value == null) {
            return this;
        }
        JsonNode node = Utils.getObjectMapper().valueToTree(value);
        if (node.isArray()) {
            node.forEach(item -> field(name, item, contentType));
        } else if (node.isNull()) {
            return this;
        } else if (node.isContainerNode() || contentType != null) {
            String text = node.isContainerNode() || !node.isTextual() ? node.toString() : node.asText();
            builder.addPart(
                    Headers.of("Content-Disposition", "form-data; name=\"" + name + "\""),
                    RequestBody.create(
                            text.getBytes(StandardCharsets.UTF_8),
                            MediaType.get(contentType != null ? contentType : "application/json")));
        } else {
            builder.addFormDataPart(name, node.isTextual() ? node.asText() : node.toString());
        }
        return this;
    }

    /**
     * Adds a file.
     *
     * @param name the field name
     * @param upload the file, left out when null
     * @return this form
     */
    public Multipart file(String name, Upload upload) {
        return file(name, upload, null);
    }

    /**
     * Adds a file; {@code contentType} is the media type the spec declares, used unless the
     * upload sets its own.
     *
     * @param name the field name
     * @param upload the file, left out when null
     * @param contentType the declared media type, or null
     * @return this form
     */
    public Multipart file(String name, Upload upload, String contentType) {
        if (upload != null) {
            String filename = upload.getFilename() != null ? upload.getFilename() : "file";
            builder.addFormDataPart(name, filename, upload.part(contentType));
        }
        return this;
    }

    /**
     * Adds several files as repeated parts of the same name.
     *
     * @param name the field name
     * @param uploads the files, left out when null
     * @param contentType the declared media type, or null
     * @return this form
     */
    public Multipart files(String name, java.util.List<Upload> uploads, String contentType) {
        if (uploads != null) {
            uploads.forEach(upload -> file(name, upload, contentType));
        }
        return this;
    }

    /**
     * The body.
     *
     * @return the multipart body
     */
    public RequestBody build() {
        return builder.build();
    }
}
