// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_PACKAGE@@.streaming;

import java.time.Duration;
import java.util.Objects;

/** One server-sent event. Data lines are joined with a newline; nothing is JSON-decoded. */
public final class SseEvent {
    private final String event;
    private final String data;
    private final String id;
    private final Duration retry;

    /**
     * An event.
     *
     * @param event the event name, {@code message} by default
     * @param data the data lines, joined with a newline
     * @param id the last event ID, or null
     * @param retry the reconnection delay, or null
     */
    public SseEvent(String event, String data, String id, Duration retry) {
        this.event = event;
        this.data = data;
        this.id = id;
        this.retry = retry;
    }

    /**
     * The event name.
     *
     * @return the name, {@code message} when the server sent none
     */
    public String event() {
        return event;
    }

    /**
     * The data lines, joined with a newline.
     *
     * @return the data
     */
    public String data() {
        return data;
    }

    /**
     * The last event ID, including updates from events with no data.
     *
     * @return the ID, or null
     */
    public String id() {
        return id;
    }

    /**
     * The server-provided reconnection delay. The SDK does not reconnect.
     *
     * @return the delay, or null
     */
    public Duration retry() {
        return retry;
    }

    @Override
    public boolean equals(Object other) {
        if (!(other instanceof SseEvent)) {
            return false;
        }
        SseEvent that = (SseEvent) other;
        return event.equals(that.event)
                && data.equals(that.data)
                && Objects.equals(id, that.id)
                && Objects.equals(retry, that.retry);
    }

    @Override
    public int hashCode() {
        return Objects.hash(event, data, id, retry);
    }

    @Override
    public String toString() {
        return "SseEvent{event=" + event + ", data=" + data + ", id=" + id + ", retry=" + retry + "}";
    }
}
