// this file is @generated by Perseid; edit the shared runtime template.
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;

namespace @@PACKAGE_NAME@@;

/// <summary>Thrown when a webhook payload fails verification.</summary>
/// <param name="message">What failed.</param>
public sealed class WebhookVerificationException(string message) : @@CLIENT_NAME@@Exception(message);

/// <summary>Verifies and signs Standard Webhooks (https://www.standardwebhooks.com) payloads, also
/// accepting <c>svix-*</c> headers: <c>new Webhook(secret).Verify(rawBody, name => Request.Headers[name])</c>.</summary>
public sealed class Webhook
{
    private const string SecretPrefix = "whsec_";
    private static readonly TimeSpan Tolerance = TimeSpan.FromMinutes(5);

    private static readonly (string Primary, string Fallback)[] Names =
    [
        ("webhook-id", "svix-id"),
        ("webhook-timestamp", "svix-timestamp"),
        ("webhook-signature", "svix-signature"),
    ];

    private readonly byte[] _key;

    /// <summary>A verifier for the signing secret of an endpoint.</summary>
    /// <param name="secret">The signing secret as shown in your dashboard: base64, with or without
    /// the <c>whsec_</c> prefix.</param>
    /// <exception cref="ArgumentException">The secret is empty or not valid base64.</exception>
    public Webhook(string secret)
        : this(Decode(secret)) { }

    /// <summary>A verifier for a raw signing key.</summary>
    /// <param name="key">The raw, already decoded signing key.</param>
    public Webhook(byte[] key)
    {
        ArgumentNullException.ThrowIfNull(key);
        if (key.Length == 0)
        {
            throw new ArgumentException("Webhook secret is empty", nameof(key));
        }
        _key = (byte[])key.Clone();
    }

    /// <inheritdoc cref="Verify(byte[], Func{string, string?})"/>
    public void Verify(string payload, IEnumerable<KeyValuePair<string, string>> headers) =>
        Verify(Encoding.UTF8.GetBytes(payload), headers);

    /// <inheritdoc cref="Verify(byte[], Func{string, string?})"/>
    public void Verify(byte[] payload, IEnumerable<KeyValuePair<string, string>> headers)
    {
        var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var (name, value) in headers)
        {
            map[name] = map.TryGetValue(name, out var existing) ? $"{existing} {value}" : value;
        }
        Verify(payload, name => map.GetValueOrDefault(name));
    }

    /// <inheritdoc cref="Verify(byte[], Func{string, string?})"/>
    public void Verify(string payload, HttpHeaders headers) =>
        Verify(Encoding.UTF8.GetBytes(payload), headers);

    /// <inheritdoc cref="Verify(byte[], Func{string, string?})"/>
    public void Verify(byte[] payload, HttpHeaders headers) =>
        Verify(
            payload,
            name => headers.TryGetValues(name, out var values) ? string.Join(" ", values) : null
        );

    /// <inheritdoc cref="Verify(byte[], Func{string, string?})"/>
    public void Verify(string payload, Func<string, string?> header) =>
        Verify(Encoding.UTF8.GetBytes(payload), header);

    /// <summary>Checks the signature of the raw body, exactly as received, and that the timestamp is
    /// within five minutes of now. <paramref name="header"/> returns a request header by name.</summary>
    /// <exception cref="WebhookVerificationException">Verification failed.</exception>
    public void Verify(byte[] payload, Func<string, string?> header)
    {
        ArgumentNullException.ThrowIfNull(payload);
        var values = Names
            .Select(n => NonEmpty(header(n.Primary)) ?? NonEmpty(header(n.Fallback)))
            .ToArray();
        if (values is not [{ } id, { } timestamp, { } signatures])
        {
            throw new WebhookVerificationException("Missing required headers");
        }
        if (
            !long.TryParse(
                timestamp,
                NumberStyles.AllowLeadingSign,
                CultureInfo.InvariantCulture,
                out var seconds
            )
        )
        {
            throw new WebhookVerificationException("Invalid Signature Headers");
        }
        var now = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        if (seconds < now - (long)Tolerance.TotalSeconds)
        {
            throw new WebhookVerificationException("Message timestamp too old");
        }
        if (seconds > now + (long)Tolerance.TotalSeconds)
        {
            throw new WebhookVerificationException("Message timestamp too new");
        }
        var expected = Encoding.ASCII.GetBytes(Digest(id, seconds, payload));
        foreach (
            var part in signatures.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
        )
        {
            var comma = part.IndexOf(',');
            if (
                comma > 0
                && part[..comma] == "v1"
                && CryptographicOperations.FixedTimeEquals(
                    Encoding.ASCII.GetBytes(part[(comma + 1)..]),
                    expected
                )
            )
            {
                return;
            }
        }
        throw new WebhookVerificationException("No matching signature found");
    }

    /// <summary>Returns the <c>v1,&lt;base64&gt;</c> value of the <c>webhook-signature</c> header.</summary>
    public string Sign(string msgId, DateTimeOffset timestamp, string payload) =>
        Sign(msgId, timestamp, Encoding.UTF8.GetBytes(payload));

    /// <inheritdoc cref="Sign(string, DateTimeOffset, string)"/>
    public string Sign(string msgId, DateTimeOffset timestamp, byte[] payload) =>
        $"v1,{Digest(msgId, timestamp.ToUnixTimeSeconds(), payload)}";

    private string Digest(string msgId, long seconds, byte[] payload)
    {
        var prefix = Encoding.UTF8.GetBytes($"{msgId}.{seconds}.");
        var content = new byte[prefix.Length + payload.Length];
        prefix.CopyTo(content, 0);
        payload.CopyTo(content, prefix.Length);
        return Convert.ToBase64String(HMACSHA256.HashData(_key, content));
    }

    private static string? NonEmpty(string? value) => string.IsNullOrEmpty(value) ? null : value;

    private static byte[] Decode(string secret)
    {
        ArgumentNullException.ThrowIfNull(secret);
        var encoded = secret.StartsWith(SecretPrefix, StringComparison.Ordinal)
            ? secret[SecretPrefix.Length..]
            : secret;
        try
        {
            return Convert.FromBase64String(encoded);
        }
        catch (FormatException e)
        {
            throw new ArgumentException("Webhook secret is not valid base64", nameof(secret), e);
        }
    }
}
