use super::{assets::Assets, config::Project, io, source, workspace as ws};
use anyhow::{Result, ensure};
use serde_json::{Value, json};
use std::{fs, path::Path, process::Command};
fn gh(args: &[&str]) -> Result<String> {
    io::text(Command::new("gh").args(args))
}
fn copy_control(project: &Project, root: &Path) -> Result<()> {
    for path in [
        project.path.clone(),
        project.snapshot()?,
        project.lock_path(),
        project.versions_path(),
    ] {
        if path.exists() {
            let relative = path.strip_prefix(&project.root)?;
            io::write(&io::relative(root, relative)?, &fs::read(path)?)?;
        }
    }
    Ok(())
}
pub fn generate_pr(
    project: &Project,
    names: &[String],
    assets: &Assets,
    dry_run: bool,
) -> Result<Value> {
    let lock = source::locked(project, assets)?;
    let all = project.groups(&[])?;
    let mut destinations = project.groups(names)?;
    for (repo, selected) in &mut destinations {
        *selected = all[repo].clone();
    }
    destinations.entry(".".into()).or_default();
    let mut pending = Vec::new();
    let mut results = Vec::new();
    for (repository, selected) in destinations {
        let repo = ws::github_repo(&ws::repository_url(project, &repository)?)?;
        let temp = ws::delivery(project, &repository, &selected)?;
        let root = temp.path().join("repo");
        let base = ws::branch(&root)?;
        let branch = format!("perseid/{}/update", project.config.name);
        ensure!(base != branch, "Update branch cannot be the base branch");
        if repository == "." {
            copy_control(project, &root)?;
        }
        ws::render(
            project,
            &root,
            &selected,
            &lock,
            assets,
            ws::RenderOptions {
                no_format: false,
                checks: true,
                version_root: &root,
            },
        )?;
        let paths = ws::tracked_changes(&root)?;
        let title = format!("Update {} SDKs", project.config.name);
        let body = format!(
            "Generated by Perseid from the committed spec snapshot.\n\nSpec SHA-256: `{}`\n\nTargets: {}.\n\nConfigured SDK checks passed.\n",
            lock.spec_sha256,
            selected.join(", ")
        );
        pending.push((temp, repo, base, branch, title, body, paths));
    }
    for (temp, repo, base, branch, title, body, paths) in pending {
        let root = temp.path().join("repo");
        if dry_run {
            results.push(json!({"repository":repo,"base":base,"branch":branch,"changed":paths}));
            continue;
        }
        let existing: Vec<Value> = serde_json::from_str(&gh(&[
            "pr",
            "list",
            "--repo",
            &repo,
            "--head",
            &branch,
            "--base",
            &base,
            "--state",
            "open",
            "--json",
            "number,url",
        ])?)?;
        let reference = format!("refs/heads/{branch}");
        let remote = io::git(&root, &["ls-remote", "--heads", "origin", &reference])?;
        let expected = remote.split_whitespace().next().unwrap_or("");
        if !expected.is_empty() {
            io::git(&root, &["fetch", "--quiet", "origin", &reference])?;
            let marker = format!("Perseid-Project: {}", project.config.name);
            ensure!(
                io::git(&root, &["show", "-s", "--format=%s", expected])? == title
                    && io::git(&root, &["show", "-s", "--format=%B", expected])?
                        .lines()
                        .any(|line| line == marker),
                "Reserved branch contains a non-Perseid commit"
            );
            if !paths.is_empty()
                && !existing.is_empty()
                && io::git(&root, &["write-tree"])?
                    == io::git(&root, &["rev-parse", &format!("{expected}^{{tree}}")])?
            {
                results.push(json!({"repository":repo,"changed":[],"pr":existing[0]["url"]}));
                continue;
            }
        }
        if paths.is_empty() {
            if let Some(pr) = existing.first() {
                gh(&["pr", "close", &pr["number"].to_string(), "--repo", &repo])?;
            }
            results.push(json!({"repository":repo,"changed":[],"pr":null}));
            continue;
        }
        io::git(
            &root,
            &[
                "-c",
                "user.name=perseid[bot]",
                "-c",
                "user.email=perseid@users.noreply.github.com",
                "commit",
                "--quiet",
                "-m",
                &title,
                "-m",
                &format!("Perseid-Project: {}", project.config.name),
            ],
        )?;
        io::git(
            &root,
            &[
                "push",
                &format!("--force-with-lease={reference}:{expected}"),
                "origin",
                &format!("HEAD:{reference}"),
            ],
        )?;
        let body_file = temp.path().join("body.md");
        io::write(&body_file, body.as_bytes())?;
        let body_path = body_file.to_str().unwrap();
        let url = if let Some(pr) = existing.first() {
            gh(&[
                "pr",
                "edit",
                &pr["number"].to_string(),
                "--repo",
                &repo,
                "--title",
                &title,
                "--body-file",
                body_path,
            ])?;
            pr["url"].as_str().unwrap().to_owned()
        } else {
            gh(&[
                "pr",
                "create",
                "--repo",
                &repo,
                "--base",
                &base,
                "--head",
                &branch,
                "--title",
                &title,
                "--body-file",
                body_path,
            ])?
        };
        results.push(json!({"repository":repo,"changed":paths,"pr":url}));
    }
    Ok(results.into())
}
