// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_PACKAGE@@.exceptions;

/** Thrown when a webhook payload fails signature verification. */
public class WebhookVerificationException extends Exception {
    private static final long serialVersionUID = 1L;

    /**
     * An exception for a payload that fails verification.
     *
     * @param message why it fails
     */
    public WebhookVerificationException(String message) {
        super(message);
    }
}
