# this file is @generated by Perseid; edit the shared runtime template.
"""Security schemes: bearer tokens, HTTP basic credentials and API keys."""

from __future__ import annotations

import base64
import typing as t

import httpx

__all__ = [
    "Security",
    "SecurityScheme",
    "TokenProvider",
    "apply_auth",
    "async_token",
    "chosen_schemes",
    "needs_token_provider",
    "sync_token",
]

TokenProvider = t.Callable[[], str | t.Awaitable[str]]
"""Returns a fresh bearer token; the async client also accepts coroutine functions."""

Security = t.Sequence[t.Sequence[str]]
"""Alternatives of scheme names: the first one whose credentials are all configured is sent."""


class SecurityScheme(t.NamedTuple):
    """How the API reads one kind of credentials."""

    kind: str
    """``bearer``, ``basic`` or ``api_key``."""
    location: str = ""
    param: str = ""


class _Credentials(t.Protocol):
    bearer_access_token: str | None
    token_provider: TokenProvider | None
    basic_auth: tuple[str, str] | None
    api_keys: t.Mapping[str, str]
    security_schemes: t.Mapping[str, SecurityScheme]


def _configured(cfg: _Credentials, name: str) -> bool:
    scheme = cfg.security_schemes.get(name)
    if scheme is None:
        return False
    if scheme.kind == "bearer":
        return cfg.token_provider is not None or bool(cfg.bearer_access_token)
    if scheme.kind == "basic":
        return cfg.basic_auth is not None
    return bool(cfg.api_keys.get(name) or cfg.bearer_access_token)


def chosen_schemes(cfg: _Credentials, security: Security) -> list[str]:
    """The schemes of the first alternative of ``security`` whose credentials are all set."""
    for names in security:
        if names and all(_configured(cfg, name) for name in names):
            return list(names)
    return []


def needs_token_provider(cfg: _Credentials, names: t.Sequence[str]) -> bool:
    """Whether the token provider must be called for the schemes ``names``."""
    return cfg.token_provider is not None and any(
        cfg.security_schemes[name].kind == "bearer" for name in names
    )


def sync_token(cfg: _Credentials) -> str:
    """A token from the provider, which must not be a coroutine function."""
    assert cfg.token_provider is not None
    token = cfg.token_provider()
    if not isinstance(token, str):
        raise TypeError("an async token_provider needs the async client")
    return token


async def async_token(cfg: _Credentials) -> str:
    """A token from the provider, awaited when it returns an awaitable."""
    assert cfg.token_provider is not None
    token = cfg.token_provider()
    return token if isinstance(token, str) else await token


def apply_auth(
    cfg: _Credentials,
    names: t.Sequence[str],
    provided_token: str | None,
    headers: httpx.Headers,
    params: list[tuple[str, str]],
) -> None:
    """Sets the credentials of the schemes ``names`` on a request's headers and query."""
    for name in names:
        scheme = cfg.security_schemes[name]
        if scheme.kind == "bearer":
            token = provided_token if provided_token is not None else cfg.bearer_access_token
            headers["authorization"] = f"Bearer {token}"
        elif scheme.kind == "basic":
            assert cfg.basic_auth is not None
            raw = ":".join(cfg.basic_auth).encode()
            headers["authorization"] = f"Basic {base64.b64encode(raw).decode()}"
        else:
            key = cfg.api_keys.get(name) or cfg.bearer_access_token or ""
            if scheme.location == "query":
                params.append((scheme.param, key))
            elif scheme.location == "cookie":
                cookie = f"{scheme.param}={key}"
                previous = headers.get("cookie")
                headers["cookie"] = cookie if previous is None else f"{previous}; {cookie}"
            else:
                headers[scheme.param.lower()] = key
