# this file is @generated by Perseid; edit the shared runtime template.
"""Iterators over every item of a paginated list operation."""

from __future__ import annotations

import typing as t

from ..serialization import BaseModel

__all__ = ["Pagination", "paginate_async", "paginate_sync"]

_M = t.TypeVar("_M", bound=BaseModel)
Path = t.Sequence[str]


class Pagination(t.NamedTuple):
    """How a list operation pages. Paths are JSON property names from the response root."""

    style: str
    items: Path
    next_cursor: t.Optional[Path] = None
    item_cursor: t.Optional[str] = None
    has_more: t.Optional[Path] = None
    total_pages: t.Optional[Path] = None
    total: t.Optional[Path] = None
    first_page: int = 1


def _at(value: t.Any, path: t.Optional[Path]) -> t.Any:
    for key in path or ():
        value = value.get(key) if isinstance(value, dict) else None
    return value


class _Cursor:
    def __init__(self, pagination: Pagination, start: t.Any) -> None:
        self.pagination = pagination
        if start is None and pagination.style == "page":
            start = pagination.first_page
        elif start is None and pagination.style == "offset":
            start = 0
        self.param = start

    def advance(self, page: t.Dict[str, t.Any], items: t.List[t.Any]) -> bool:
        """Moves to the next page, returning whether there is one."""
        p = self.pagination
        if not items or (p.has_more is not None and _at(page, p.has_more) is False):
            return False
        if p.style == "cursor":
            if p.next_cursor is not None:
                cursor = _at(page, p.next_cursor)
            else:
                cursor = items[-1].get(p.item_cursor)
            if cursor in (None, "") or cursor == self.param:
                return False
            self.param = cursor
            return True
        if p.style == "page":
            total_pages = _at(page, p.total_pages)
            if isinstance(total_pages, int) and self.param - p.first_page + 1 >= total_pages:
                return False
            self.param += 1
            return True
        self.param += len(items)
        total = _at(page, p.total)
        return not (isinstance(total, int) and self.param >= total)


def paginate_sync(
    pagination: Pagination,
    start: t.Any,
    fetch_page: t.Callable[[t.Any], BaseModel],
    item: t.Type[_M],
) -> t.Iterator[_M]:
    cursor = _Cursor(pagination, start)
    while True:
        page = fetch_page(cursor.param).to_dict()
        items = _at(page, pagination.items) or []
        for raw in items:
            yield item.from_dict(raw)
        if not cursor.advance(page, items):
            return


async def paginate_async(
    pagination: Pagination,
    start: t.Any,
    fetch_page: t.Callable[[t.Any], t.Awaitable[BaseModel]],
    item: t.Type[_M],
) -> t.AsyncIterator[_M]:
    cursor = _Cursor(pagination, start)
    while True:
        page = (await fetch_page(cursor.param)).to_dict()
        items = _at(page, pagination.items) or []
        for raw in items:
            yield item.from_dict(raw)
        if not cursor.advance(page, items):
            return
