# this file is @generated by Perseid; edit the shared runtime template.
"""Raw responses: the status and headers of a call next to its decoded result."""

from __future__ import annotations

import contextvars
import datetime
import functools
import typing as t

import httpx

__all__ = [
    "APIResponse",
    "async_to_raw_response_wrapper",
    "capture_response",
    "to_raw_response_wrapper",
]

_T = t.TypeVar("_T")
_P = t.ParamSpec("_P")

_captured: contextvars.ContextVar[list[httpx.Response] | None] = contextvars.ContextVar(
    "_captured", default=None
)

_REQUEST_ID_HEADERS = ("x-request-id", "request-id")


def capture_response(response: httpx.Response) -> None:
    """Hands the final response of a call to the raw response wrapper around it, if any."""
    captured = _captured.get()
    if captured is not None:
        captured.append(response)


def request_id(headers: httpx.Headers) -> str | None:
    """The request id to quote to support, when the API sends one."""
    for name in _REQUEST_ID_HEADERS:
        if name in headers:
            return headers[name]
    return None


class APIResponse(t.Generic[_T]):
    """The HTTP response of a call, with its decoded result from :meth:`parse`."""

    http_response: httpx.Response
    """The underlying ``httpx`` response. A stream's body is left unread."""

    def __init__(self, http_response: httpx.Response, parsed: _T) -> None:
        self.http_response = http_response
        self._parsed = parsed

    def parse(self) -> _T:
        """The decoded result, as the method returns it without ``with_raw_response``."""
        return self._parsed

    @property
    def status_code(self) -> int:
        """The HTTP status."""
        return self.http_response.status_code

    @property
    def headers(self) -> httpx.Headers:
        """The response headers."""
        return self.http_response.headers

    @property
    def request_id(self) -> str | None:
        """The ``x-request-id`` (or ``request-id``) header, to quote to support."""
        return request_id(self.http_response.headers)

    @property
    def url(self) -> httpx.URL:
        """The URL of the request."""
        return self.http_response.url

    @property
    def method(self) -> str:
        """The HTTP method of the request."""
        return self.http_response.request.method

    @property
    def elapsed(self) -> datetime.timedelta:
        """Time between sending the request and reading the response."""
        return self.http_response.elapsed

    def __repr__(self) -> str:
        return f"<APIResponse [{self.status_code}] {self.method} {self.url}>"


def _raw(captured: list[httpx.Response], parsed: _T) -> APIResponse[_T]:
    if not captured:
        raise RuntimeError("the method sent no request")
    return APIResponse(captured[-1], parsed)


def to_raw_response_wrapper(func: t.Callable[_P, _T]) -> t.Callable[_P, APIResponse[_T]]:
    """Makes ``func``, a method of a resource, return an :class:`APIResponse`."""

    @functools.wraps(func)
    def wrapped(*args: _P.args, **kwargs: _P.kwargs) -> APIResponse[_T]:
        captured: list[httpx.Response] = []
        token = _captured.set(captured)
        try:
            parsed = func(*args, **kwargs)
        finally:
            _captured.reset(token)
        return _raw(captured, parsed)

    return wrapped


def async_to_raw_response_wrapper(
    func: t.Callable[_P, t.Awaitable[_T]],
) -> t.Callable[_P, t.Awaitable[APIResponse[_T]]]:
    """Makes ``func``, a method of an async resource, return an :class:`APIResponse`."""

    @functools.wraps(func)
    async def wrapped(*args: _P.args, **kwargs: _P.kwargs) -> APIResponse[_T]:
        captured: list[httpx.Response] = []
        token = _captured.set(captured)
        try:
            parsed = await func(*args, **kwargs)
        finally:
            _captured.reset(token)
        return _raw(captured, parsed)

    return wrapped
