# this file is @generated by Perseid; edit the shared runtime template.
"""Server-sent event streams, raw uploads and multipart bodies."""

from __future__ import annotations

import dataclasses
import json
import os
import typing as t

import httpx

from .._exceptions import APIResponseValidationError, connection_error
from ..serialization import JSONValue, from_json_value, to_json_value

__all__ = [
    "AsyncEventStream",
    "AsyncStream",
    "EventStream",
    "FileInput",
    "MultipartField",
    "Stream",
    "SseEvent",
    "Upload",
    "UploadContent",
    "is_event_stream",
    "multipart_files",
    "not_an_event_stream",
    "replayable",
]

_T = t.TypeVar("_T")

UploadContent: t.TypeAlias = (
    "bytes | t.IO[bytes] | t.Iterable[bytes] | t.AsyncIterable[bytes]"
)
"""A raw body. Only ``bytes`` are retried; streams and files are sent once."""


class Upload(t.NamedTuple):
    """A multipart file with its filename and content type."""

    content: bytes | t.IO[bytes]
    filename: str | None = None
    content_type: str = "application/octet-stream"


FileInput: t.TypeAlias = "bytes | t.IO[bytes] | Upload"
"""A multipart file: its content, or an :class:`Upload` naming it."""

MultipartField: t.TypeAlias = "tuple[str, object, bool]"
"""A multipart field: its name, its value and whether it is a file."""


@dataclasses.dataclass
class SseEvent:
    """One server-sent event. Data lines are joined with a newline; nothing is JSON-decoded."""

    event: str
    data: str
    id: str | None = None
    """Last event ID, including updates from events with no data."""
    retry: int | None = None
    """Server-provided reconnection delay in milliseconds. The SDK does not reconnect."""


def is_event_stream(response: httpx.Response) -> bool:
    content_type: str = response.headers.get("content-type", "")
    return content_type.split(";")[0].strip().lower() == "text/event-stream"


def not_an_event_stream(response: httpx.Response) -> APIResponseValidationError:
    return APIResponseValidationError(response, "expected a text/event-stream response")


class _Parser:
    def __init__(self) -> None:
        self.id: str | None = None
        self.retry: int | None = None
        self._line = ""
        self._data = ""
        self._event = ""
        self._after_cr = False
        self._first_line = True

    def push(self, text: str) -> list[SseEvent]:
        events: list[SseEvent] = []
        for char in text:
            if self._after_cr:
                self._after_cr = False
                if char == "\n":
                    continue
            if char not in "\r\n":
                self._line += char
                continue
            self._after_cr = char == "\r"
            event = self._end_line()
            if event is not None:
                events.append(event)
        return events

    def _end_line(self) -> SseEvent | None:
        line, self._line = self._line, ""
        if self._first_line and line.startswith("\ufeff"):
            line = line[1:]
        self._first_line = False
        if not line:
            event, self._event = self._event or "message", ""
            if not self._data:
                return None
            data, self._data = self._data[:-1], ""
            return SseEvent(event, data, self.id, self.retry)
        if line.startswith(":"):
            return None
        name, _, value = line.partition(":")
        value = value[1:] if value.startswith(" ") else value
        if name == "data":
            self._data += value + "\n"
        elif name == "event":
            self._event = value
        elif name == "id" and "\0" not in value:
            self.id = value
        elif name == "retry" and value.isdigit():
            self.retry = int(value)
        return None


class _EventSource:
    """A live ``text/event-stream`` response. Close it, or use it as a context manager."""

    response: httpx.Response
    """The ``httpx`` response, whose body is read as the stream is iterated."""

    def __init__(self, response: httpx.Response) -> None:
        self.response = response
        self._parser = _Parser()

    @property
    def last_event_id(self) -> str | None:
        """The id of the last event, to resume from with a ``Last-Event-ID`` header."""
        return self._parser.id

    def _events(self) -> t.Iterator[SseEvent]:
        try:
            for text in self.response.iter_text():
                yield from self._parser.push(text)
        except httpx.RequestError as exc:
            raise connection_error(exc) from exc
        finally:
            self.close()

    def close(self) -> None:
        """Stops reading the stream and releases the connection."""
        self.response.close()


class _AsyncEventSource:
    """A live ``text/event-stream`` response, iterated with ``async for``."""

    response: httpx.Response
    """The ``httpx`` response, whose body is read as the stream is iterated."""

    def __init__(self, response: httpx.Response) -> None:
        self.response = response
        self._parser = _Parser()

    @property
    def last_event_id(self) -> str | None:
        """The id of the last event, to resume from with a ``Last-Event-ID`` header."""
        return self._parser.id

    async def _events(self) -> t.AsyncIterator[SseEvent]:
        try:
            async for text in self.response.aiter_text():
                for event in self._parser.push(text):
                    yield event
        except httpx.RequestError as exc:
            raise connection_error(exc) from exc
        finally:
            await self.aclose()

    async def aclose(self) -> None:
        """Stops reading the stream and releases the connection."""
        await self.response.aclose()


class EventStream(_EventSource):
    """The server-sent events of a response, as received."""

    def __iter__(self) -> t.Iterator[SseEvent]:
        return self._events()

    def __enter__(self) -> EventStream:
        return self

    def __exit__(self, *exc_info: object) -> None:
        self.close()


class AsyncEventStream(_AsyncEventSource):
    """The server-sent events of a response, as received, iterated with ``async for``."""

    def __aiter__(self) -> t.AsyncIterator[SseEvent]:
        return self._events()

    async def __aenter__(self) -> AsyncEventStream:
        return self

    async def __aexit__(self, *exc_info: object) -> None:
        await self.aclose()


def _decode(event: SseEvent, type_: type[_T], response: httpx.Response) -> _T:
    try:
        return t.cast(_T, from_json_value(type_, json.loads(event.data)))
    except (ValueError, TypeError) as exc:
        raise APIResponseValidationError(response, f"event {event.data!r}: {exc}") from exc


class Stream(_EventSource, t.Generic[_T]):
    """The JSON ``data`` of each server-sent event, decoded until a ``[DONE]`` event.

    :attr:`last_event` is the raw event of the latest item, with its ``event`` and ``id``.
    """

    last_event: SseEvent | None = None
    """The event the latest item was decoded from."""

    def __init__(self, response: httpx.Response, type_: type[_T]) -> None:
        super().__init__(response)
        self._type = type_

    def __iter__(self) -> t.Iterator[_T]:
        for event in self._events():
            if event.data == "[DONE]":
                self.close()
                return
            self.last_event = event
            yield _decode(event, self._type, self.response)

    def __enter__(self) -> Stream[_T]:
        return self

    def __exit__(self, *exc_info: object) -> None:
        self.close()


class AsyncStream(_AsyncEventSource, t.Generic[_T]):
    """The JSON ``data`` of each server-sent event, decoded until a ``[DONE]`` event.

    :attr:`last_event` is the raw event of the latest item, with its ``event`` and ``id``.
    """

    last_event: SseEvent | None = None
    """The event the latest item was decoded from."""

    def __init__(self, response: httpx.Response, type_: type[_T]) -> None:
        super().__init__(response)
        self._type = type_

    async def __aiter__(self) -> t.AsyncIterator[_T]:
        async for event in self._events():
            if event.data == "[DONE]":
                await self.aclose()
                return
            self.last_event = event
            yield _decode(event, self._type, self.response)

    async def __aenter__(self) -> AsyncStream[_T]:
        return self

    async def __aexit__(self, *exc_info: object) -> None:
        await self.aclose()


def _scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


_File: t.TypeAlias = (
    "tuple[str, tuple[str | None, bytes | t.IO[bytes] | str, str | None]]"
)


def multipart_files(fields: t.Sequence[MultipartField]) -> list[_File]:
    """Renders multipart fields as ``httpx`` files, skipping ``None``."""
    files: list[_File] = []
    for name, value, is_file in fields:
        if value is None:
            continue
        if is_file:
            upload = value if isinstance(value, Upload) else Upload(t.cast("bytes", value))
            filename = upload.filename or os.path.basename(getattr(upload.content, "name", "file"))
            files.append((name, (filename, upload.content, upload.content_type)))
            continue
        json_value: JSONValue = to_json_value(value)
        for item in json_value if isinstance(json_value, list) else [json_value]:
            if isinstance(item, (dict, list)):
                files.append((name, (None, json.dumps(item), "application/json")))
            elif item is not None:
                files.append((name, (None, _scalar(item), None)))
    return files


def replayable(content: object, files: t.Sequence[_File]) -> bool:
    """Whether a request body can be sent again, for retries."""
    if content is not None and not isinstance(content, (bytes, str)):
        return False
    return all(isinstance(file[1], (bytes, str)) for _, file in files)
