# this file is @generated by Perseid; edit the shared runtime template.
"""Server-sent event streams, raw uploads and multipart bodies."""

from __future__ import annotations

import dataclasses
import json
import os
import typing as t

import httpx

from ..errors import ResponseDecodeError
from ..serialization import to_json_value

__all__ = [
    "AsyncEventStream",
    "EventStream",
    "FileInput",
    "SseEvent",
    "Upload",
    "UploadContent",
    "is_event_stream",
    "multipart_files",
    "not_an_event_stream",
    "replayable",
]

UploadContent = t.Union[bytes, t.IO[bytes], t.Iterable[bytes], t.AsyncIterable[bytes]]
"""A raw body. Only ``bytes`` are retried; streams and files are sent once."""


class Upload(t.NamedTuple):
    """A multipart file with its filename and content type."""

    content: bytes | t.IO[bytes]
    filename: str | None = None
    content_type: str = "application/octet-stream"


FileInput = t.Union[bytes, t.IO[bytes], Upload]


@dataclasses.dataclass
class SseEvent:
    """One server-sent event. Data lines are joined with a newline; nothing is JSON-decoded."""

    event: str
    data: str
    id: str | None = None
    """Last event ID, including updates from events with no data."""
    retry: int | None = None
    """Server-provided reconnection delay in milliseconds. The SDK does not reconnect."""


def is_event_stream(response: httpx.Response) -> bool:
    content_type: str = response.headers.get("content-type", "")
    return content_type.split(";")[0].strip().lower() == "text/event-stream"


def not_an_event_stream(response: httpx.Response) -> ResponseDecodeError:
    return ResponseDecodeError(response.status_code, b"", "expected a text/event-stream response")


class _Parser:
    def __init__(self) -> None:
        self.id: str | None = None
        self.retry: int | None = None
        self._line = ""
        self._data = ""
        self._event = ""
        self._after_cr = False
        self._first_line = True

    def push(self, text: str) -> list[SseEvent]:
        events = []
        for char in text:
            if self._after_cr:
                self._after_cr = False
                if char == "\n":
                    continue
            if char not in "\r\n":
                self._line += char
                continue
            self._after_cr = char == "\r"
            event = self._end_line()
            if event is not None:
                events.append(event)
        return events

    def _end_line(self) -> SseEvent | None:
        line, self._line = self._line, ""
        if self._first_line and line.startswith("\ufeff"):
            line = line[1:]
        self._first_line = False
        if not line:
            event, self._event = self._event or "message", ""
            if not self._data:
                return None
            data, self._data = self._data[:-1], ""
            return SseEvent(event, data, self.id, self.retry)
        if line.startswith(":"):
            return None
        name, _, value = line.partition(":")
        value = value[1:] if value.startswith(" ") else value
        if name == "data":
            self._data += value + "\n"
        elif name == "event":
            self._event = value
        elif name == "id" and "\0" not in value:
            self.id = value
        elif name == "retry" and value.isdigit():
            self.retry = int(value)
        return None


class EventStream:
    """A live ``text/event-stream`` response. Close it, or use it as a context manager."""

    def __init__(self, response: httpx.Response) -> None:
        self._response = response
        self._parser = _Parser()

    @property
    def last_event_id(self) -> str | None:
        return self._parser.id

    def __iter__(self) -> t.Iterator[SseEvent]:
        try:
            for text in self._response.iter_text():
                yield from self._parser.push(text)
        finally:
            self.close()

    def close(self) -> None:
        self._response.close()

    def __enter__(self) -> EventStream:
        return self

    def __exit__(self, *exc_info: t.Any) -> None:
        self.close()


class AsyncEventStream:
    """A live ``text/event-stream`` response, iterated with ``async for``."""

    def __init__(self, response: httpx.Response) -> None:
        self._response = response
        self._parser = _Parser()

    @property
    def last_event_id(self) -> str | None:
        return self._parser.id

    async def __aiter__(self) -> t.AsyncIterator[SseEvent]:
        try:
            async for text in self._response.aiter_text():
                for event in self._parser.push(text):
                    yield event
        finally:
            await self.aclose()

    async def aclose(self) -> None:
        await self._response.aclose()

    async def __aenter__(self) -> AsyncEventStream:
        return self

    async def __aexit__(self, *exc_info: t.Any) -> None:
        await self.aclose()


def _scalar(value: t.Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def multipart_files(fields: t.Sequence[tuple[str, t.Any, bool]]) -> list[t.Any]:
    """Renders ``(name, value, is_file)`` fields as ``httpx`` multipart files, skipping ``None``."""
    files: list[t.Any] = []
    for name, value, is_file in fields:
        if value is None:
            continue
        if is_file:
            upload = value if isinstance(value, Upload) else Upload(value)
            filename = upload.filename or os.path.basename(getattr(upload.content, "name", "file"))
            files.append((name, (filename, upload.content, upload.content_type)))
            continue
        value = to_json_value(value)
        for item in value if isinstance(value, list) else [value]:
            if isinstance(item, (dict, list)):
                files.append((name, (None, json.dumps(item), "application/json")))
            elif item is not None:
                files.append((name, (None, _scalar(item), None)))
    return files


def replayable(kwargs: t.Mapping[str, t.Any]) -> bool:
    """Whether a request body can be sent again, for retries."""
    content = kwargs.get("content")
    if content is not None and not isinstance(content, bytes):
        return False
    files = kwargs.get("files") or []
    return all(isinstance(file[1], (bytes, str)) for _, file in files)
