// Code generated by perseid from its shared runtime template. DO NOT EDIT.

// Package @@PACKAGE_NAME@@ is the Go SDK for the @@CLIENT_NAME@@ API.
//
// The entry point is [New], which returns a [Client]. Every API area hangs off
// the client as an accessor method:
//
//	client := @@PACKAGE_NAME@@.New("your-api-key", nil)
//
//	customers, err := client.Customers().ListCustomers(context.Background(), nil)
//	if err != nil {
//		return err
//	}
//	for _, c := range customers.Data {
//		fmt.Println(c.Name)
//	}
//
// Optional request fields and query parameters are modelled as pointers: a nil
// pointer means "not sent". Required fields are plain values.
//
// Errors coming back from the API are always a [*APIError]; use errors.As to
// inspect the status code, headers and body.
//
// Every method takes trailing [RequestOption] values to adjust one call, e.g.
// [WithHeader], [WithTimeout] or [WithIdempotencyKey].
package @@PACKAGE_NAME@@

import (
	"context"
	"net/http"
	"strings"
	"time"
)

const (
	// DefaultServerURL is the @@CLIENT_NAME@@ API endpoint used when Options.ServerURL
	// is empty.
	DefaultServerURL = "@@DEFAULT_BASE_URL@@"

	// DefaultTimeout bounds a single request attempt, response body included.
	DefaultTimeout = 15 * time.Second

	// DefaultNumRetries is how many times a request is retried when it fails
	// transiently: network errors, 408, 429 and 5xx responses.
	DefaultNumRetries = 2
)

// Options configures a [Client]. The zero value is valid and selects the
// defaults documented on each field.
type Options struct {
	// ServerURL overrides the API base URL. Defaults to DefaultServerURL.
	ServerURL string

	// HTTPClient is the client used to perform requests. Supply your own to
	// control proxies, TLS or connection pooling. Defaults to a client with no
	// timeout of its own; per-attempt deadlines come from Timeout instead.
	HTTPClient *http.Client

	// Middleware wraps every HTTP attempt: caching, logging, custom headers.
	Middleware []Middleware

	// Timeout bounds a single attempt, from dialing until the response body has
	// been read. Zero selects DefaultTimeout; a negative value disables it.
	Timeout time.Duration

	// NumRetries is the number of retries attempted on transient failures,
	// waiting 500ms, 1s, 2s... (up to 8s) minus a random jitter, or the
	// server's Retry-After when it is under a minute. Zero selects
	// DefaultNumRetries and a negative value disables retries.
	NumRetries int

	// RetrySchedule is the delay to wait before each retry, and takes
	// precedence over NumRetries. Set it to an empty (non-nil) slice to disable
	// retries entirely.
	RetrySchedule []time.Duration

	// UserAgent overrides the User-Agent header sent with every request.
	UserAgent string

	// Debug writes a one-line summary of every request and response to stderr.
	Debug bool

	// TokenProvider is called before each request for a fresh bearer token,
	// e.g. an OAuth2 access token. It takes precedence over the client token.
	TokenProvider func(ctx context.Context) (string, error)

	// BasicAuth holds the credentials of HTTP basic security schemes.
	BasicAuth *BasicAuth

	// APIKeys holds API keys by security scheme name. Schemes left out use the
	// client token.
	APIKeys map[string]string
}

// config is the resolved, immutable form of Options held by a Client.
type config struct {
	serverURL     string
	token         string
	userAgent     string
	httpClient    *http.Client
	timeout       time.Duration
	retrySchedule []time.Duration
	jitter        bool
	debug         bool
	tokenProvider func(ctx context.Context) (string, error)
	basicAuth     *BasicAuth
	apiKeys       map[string]string
}

func newConfig(token string, options *Options) *config {
	opts := Options{}
	if options != nil {
		opts = *options
	}

	cfg := &config{
		serverURL:  DefaultServerURL,
		token:      token,
		userAgent:  "@@USER_AGENT_PREFIX@@-go/" + Version,
		httpClient: http.DefaultClient,
		timeout:    DefaultTimeout,
		debug:      opts.Debug,

		tokenProvider: opts.TokenProvider,
		basicAuth:     opts.BasicAuth,
		apiKeys:       opts.APIKeys,
	}

	if opts.ServerURL != "" {
		cfg.serverURL = strings.TrimSuffix(opts.ServerURL, "/")
	}
	if opts.HTTPClient != nil {
		cfg.httpClient = opts.HTTPClient
	}
	cfg.httpClient = withMiddleware(cfg.httpClient, opts.Middleware)
	if opts.UserAgent != "" {
		cfg.userAgent = opts.UserAgent
	}
	switch {
	case opts.Timeout > 0:
		cfg.timeout = opts.Timeout
	case opts.Timeout < 0:
		cfg.timeout = 0
	}

	switch {
	case opts.RetrySchedule != nil:
		cfg.retrySchedule = append([]time.Duration(nil), opts.RetrySchedule...)
	case opts.NumRetries > 0:
		cfg.retrySchedule, cfg.jitter = exponentialBackoff(opts.NumRetries), true
	case opts.NumRetries < 0:
		cfg.retrySchedule = nil
	default:
		cfg.retrySchedule, cfg.jitter = exponentialBackoff(DefaultNumRetries), true
	}

	return cfg
}

func (c *config) withToken(token string) *config {
	clone := *c
	clone.token = token
	return &clone
}

// exponentialBackoff waits 500ms before the first retry, doubling up to 8 seconds.
func exponentialBackoff(retries int) []time.Duration {
	const maxBackoff = 8 * time.Second

	schedule := make([]time.Duration, 0, retries)
	backoff := 500 * time.Millisecond
	for i := 0; i < retries; i++ {
		schedule = append(schedule, backoff)
		backoff *= 2
		if backoff > maxBackoff {
			backoff = maxBackoff
		}
	}
	return schedule
}
