// Code generated by perseid from its shared runtime template. DO NOT EDIT.

package @@PACKAGE_NAME@@

import (
	"encoding/json"
	"errors"
)

// Sentinels that errors.Is matches against the status of an [*APIError]:
//
//	if errors.Is(err, @@PACKAGE_NAME@@.ErrNotFound) {
//		// ...
//	}
var (
	ErrBadRequest          error = &statusError{"bad request", 400, 400}
	ErrUnauthorized        error = &statusError{"unauthorized", 401, 401}
	ErrForbidden           error = &statusError{"forbidden", 403, 403}
	ErrNotFound            error = &statusError{"not found", 404, 404}
	ErrConflict            error = &statusError{"conflict", 409, 409}
	ErrUnprocessableEntity error = &statusError{"unprocessable entity", 422, 422}
	ErrRateLimited         error = &statusError{"rate limited", 429, 429}
	ErrServer              error = &statusError{"server error", 500, 599}
)

type statusError struct {
	text     string
	min, max int
}

func (e *statusError) Error() string { return "@@PACKAGE_NAME@@: " + e.text }

// Is reports whether target is the status sentinel, such as [ErrNotFound],
// matching the status of the response.
func (e *APIError) Is(target error) bool {
	status, ok := target.(*statusError)
	return ok && e.StatusCode >= status.min && e.StatusCode <= status.max
}

// ErrorBody decodes the body of the [*APIError] in err's chain as a T, the
// error schema an operation documents for that status. It reports false when
// err holds no APIError or its body is not JSON.
//
//	if body, ok := @@PACKAGE_NAME@@.ErrorBody[@@PACKAGE_NAME@@.ErrorResponse](err); ok {
//		log.Print(body.Message)
//	}
func ErrorBody[T any](err error) (*T, bool) {
	var apiErr *APIError
	if !errors.As(err, &apiErr) {
		return nil, false
	}
	body := decodeErrorBody[T](apiErr.RawBody)
	return body, body != nil
}

func decodeErrorBody[T any](raw []byte) *T {
	var body T
	if kind := jsonKind(raw); kind == "" || kind == "null" || json.Unmarshal(raw, &body) != nil {
		return nil
	}
	return &body
}
