// Code generated by perseid from its shared runtime template. DO NOT EDIT.

package @@PACKAGE_NAME@@

import (
	"bytes"
	"encoding/json"
	"fmt"
	"slices"
	"strings"
)

// objectFields returns the properties of the JSON object data, failing as
// typeName when one of required is missing or null. Like encoding/json, it
// matches names case-insensitively.
func objectFields(data []byte, typeName string, required ...string) (map[string]json.RawMessage, error) {
	var fields map[string]json.RawMessage
	if json.Unmarshal(data, &fields) != nil {
		return nil, nil
	}
	for _, name := range required {
		value, ok := fields[name]
		if !ok {
			for key, v := range fields {
				if strings.EqualFold(key, name) {
					value, ok = v, true
					break
				}
			}
		}
		if !ok || bytes.Equal(bytes.TrimSpace(value), []byte("null")) {
			return nil, fmt.Errorf("@@PACKAGE_NAME@@: %s: required property %q is missing or null", typeName, name)
		}
	}
	return fields, nil
}

// extraFields removes the known properties from fields, returning nil when
// none are left.
func extraFields(fields map[string]json.RawMessage, known ...string) map[string]json.RawMessage {
	for name := range fields {
		if slices.ContainsFunc(known, func(k string) bool { return strings.EqualFold(k, name) }) {
			delete(fields, name)
		}
	}
	if len(fields) == 0 {
		return nil
	}
	return fields
}

// typedExtraFields is extraFields for a model whose additionalProperties
// schema types the values: it decodes each unknown property as a T into
// target, which is left nil when there are none.
func typedExtraFields[T any](target *map[string]T, fields map[string]json.RawMessage, known ...string) error {
	raw := extraFields(fields, known...)
	if raw == nil {
		*target = nil
		return nil
	}
	decoded := make(map[string]T, len(raw))
	for name, value := range raw {
		var item T
		if err := json.Unmarshal(value, &item); err != nil {
			return fmt.Errorf("@@PACKAGE_NAME@@: additional property %q: %w", name, err)
		}
		decoded[name] = item
	}
	*target = decoded
	return nil
}

// marshalWithExtra encodes v, an object, followed by the extra properties it
// does not already have, in name order.
func marshalWithExtra[T any](v any, extra map[string]T) ([]byte, error) {
	data, err := json.Marshal(v)
	if err != nil || len(extra) == 0 {
		return data, err
	}
	return appendExtra(data, extra)
}

// appendExtra adds to data, an encoded JSON object, the extra properties it
// does not already have, in name order.
func appendExtra[T any](data []byte, extra map[string]T) ([]byte, error) {
	if len(extra) == 0 {
		return data, nil
	}
	var present map[string]json.RawMessage
	if err := json.Unmarshal(data, &present); err != nil {
		return nil, fmt.Errorf("@@PACKAGE_NAME@@: a model with extra fields must encode to a JSON object: %w", err)
	}
	names := make([]string, 0, len(extra))
	for name := range extra {
		if _, ok := present[name]; !ok {
			names = append(names, name)
		}
	}
	slices.Sort(names)

	var out bytes.Buffer
	out.Write(bytes.TrimSuffix(bytes.TrimSpace(data), []byte("}")))
	separator := len(present) > 0
	for _, name := range names {
		value := extra[name]
		if raw, ok := any(value).(json.RawMessage); ok && len(bytes.TrimSpace(raw)) == 0 {
			continue
		}
		key, err := json.Marshal(name)
		if err != nil {
			return nil, err
		}
		encoded, err := json.Marshal(value)
		if err != nil {
			return nil, fmt.Errorf("@@PACKAGE_NAME@@: extra field %s is not JSON: %w", key, err)
		}
		if separator {
			out.WriteByte(',')
		}
		separator = true
		out.Write(key)
		out.WriteByte(':')
		out.Write(encoded)
	}
	out.WriteByte('}')
	return out.Bytes(), nil
}
