// Code generated by perseid from its shared runtime template. DO NOT EDIT.

package @@PACKAGE_NAME@@

import (
	"bytes"
	"encoding/json"
	"fmt"
	"slices"
	"strings"
)

// extraFields returns the properties of the JSON object data that are not
// known, or nil when there are none. Like encoding/json, it matches names
// case-insensitively, so "Id" counts as the known "id".
func extraFields(data []byte, known ...string) map[string]json.RawMessage {
	var fields map[string]json.RawMessage
	if json.Unmarshal(data, &fields) != nil {
		return nil
	}
	for name := range fields {
		if slices.ContainsFunc(known, func(k string) bool { return strings.EqualFold(k, name) }) {
			delete(fields, name)
		}
	}
	if len(fields) == 0 {
		return nil
	}
	return fields
}

// marshalWithExtra encodes v, an object, followed by the extra properties it
// does not already have, in name order.
func marshalWithExtra(v any, extra map[string]json.RawMessage) ([]byte, error) {
	data, err := json.Marshal(v)
	if err != nil || len(extra) == 0 {
		return data, err
	}
	var present map[string]json.RawMessage
	if err := json.Unmarshal(data, &present); err != nil {
		return nil, err
	}
	names := make([]string, 0, len(extra))
	for name := range extra {
		if _, ok := present[name]; !ok {
			names = append(names, name)
		}
	}
	slices.Sort(names)

	var out bytes.Buffer
	out.Write(bytes.TrimSuffix(bytes.TrimSpace(data), []byte("}")))
	separator := len(present) > 0
	for _, name := range names {
		value := extra[name]
		if len(bytes.TrimSpace(value)) == 0 {
			continue
		}
		key, err := json.Marshal(name)
		if err != nil {
			return nil, err
		}
		if separator {
			out.WriteByte(',')
		}
		separator = true
		out.Write(key)
		out.WriteByte(':')
		if err := json.Compact(&out, value); err != nil {
			return nil, fmt.Errorf("@@PACKAGE_NAME@@: extra field %s is not JSON: %w", key, err)
		}
	}
	out.WriteByte('}')
	return out.Bytes(), nil
}
