// this file is @generated by Perseid; edit the shared runtime template.
package @@PACKAGE_NAME@@

import "net/http"

// Middleware wraps the transport of every HTTP attempt, inside the retry loop: call
// next.RoundTrip to continue, or return a response of your own, e.g. from a cache.
// The first entry of Options.Middleware is the outermost.
type Middleware func(next http.RoundTripper) http.RoundTripper

// RoundTripperFunc adapts a function to an [http.RoundTripper].
type RoundTripperFunc func(*http.Request) (*http.Response, error)

// RoundTrip implements [http.RoundTripper].
func (f RoundTripperFunc) RoundTrip(req *http.Request) (*http.Response, error) { return f(req) }

func withMiddleware(client *http.Client, middleware []Middleware) *http.Client {
	if len(middleware) == 0 {
		return client
	}
	wrapped := *client
	transport := client.Transport
	if transport == nil {
		transport = http.DefaultTransport
	}
	for i := len(middleware) - 1; i >= 0; i-- {
		transport = middleware[i](transport)
	}
	wrapped.Transport = transport
	return &wrapped
}
