// this file is @generated by Perseid; edit the shared runtime template.
package @@PACKAGE_NAME@@

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime"
	"mime/multipart"
	"net/textproto"
	"strconv"
	"strings"
	"time"
)

// SseEvent is one server-sent event. Data lines are joined with a newline;
// nothing is JSON-decoded.
type SseEvent struct {
	Event string
	Data  string
	// ID is the last event ID, including updates from events with no data.
	ID string
	// Retry is the server-provided reconnection delay. The SDK does not reconnect.
	Retry time.Duration
}

// EventStream is a live text/event-stream response: loop on Next, check Err,
// and Close it once done. The client timeout only covers opening the stream.
type EventStream struct {
	body   io.ReadCloser
	reader *bufio.Reader
	cancel context.CancelFunc
	parser sseParser
	event  SseEvent
	err    error
}

// Next reads the next event. It returns false at the end of the stream or on
// error, see Err.
func (s *EventStream) Next() bool {
	for s.err == nil {
		char, _, err := s.reader.ReadRune()
		if err != nil {
			if !errors.Is(err, io.EOF) {
				s.err = err
			}
			return false
		}
		if event, ok := s.parser.push(char); ok {
			s.event = event
			return true
		}
	}
	return false
}

// Event returns the event Next read.
func (s *EventStream) Event() SseEvent { return s.event }

// LastEventID returns the ID of the last event read, including events with no data.
func (s *EventStream) LastEventID() string { return s.parser.id }

// Err returns the error that ended the stream, if any.
func (s *EventStream) Err() error { return s.err }

// Close closes the connection.
func (s *EventStream) Close() error {
	defer s.cancel()
	return s.body.Close()
}

// All yields every event, then the error that ended the stream, if any. It has
// the shape of an iter.Seq2[SseEvent, error].
func (s *EventStream) All() func(yield func(SseEvent, error) bool) {
	return func(yield func(SseEvent, error) bool) {
		for s.Next() {
			if !yield(s.event, nil) {
				return
			}
		}
		if s.err != nil {
			yield(SseEvent{}, s.err)
		}
	}
}

type sseParser struct {
	line, data, event strings.Builder
	id                string
	retry             time.Duration
	afterCR           bool
	started           bool
}

func (p *sseParser) push(char rune) (SseEvent, bool) {
	if p.afterCR {
		p.afterCR = false
		if char == '\n' {
			return SseEvent{}, false
		}
	}
	if char != '\n' && char != '\r' {
		p.line.WriteRune(char)
		return SseEvent{}, false
	}
	p.afterCR = char == '\r'
	line := p.line.String()
	p.line.Reset()
	if !p.started {
		p.started = true
		line = strings.TrimPrefix(line, "\ufeff")
	}
	if line == "" {
		name := p.event.String()
		p.event.Reset()
		if name == "" {
			name = "message"
		}
		data := p.data.String()
		p.data.Reset()
		if data == "" {
			return SseEvent{}, false
		}
		return SseEvent{Event: name, Data: strings.TrimSuffix(data, "\n"), ID: p.id, Retry: p.retry}, true
	}
	if strings.HasPrefix(line, ":") {
		return SseEvent{}, false
	}
	name, value, _ := strings.Cut(line, ":")
	value = strings.TrimPrefix(value, " ")
	switch name {
	case "data":
		p.data.WriteString(value + "\n")
	case "event":
		p.event.Reset()
		p.event.WriteString(value)
	case "id":
		if !strings.ContainsRune(value, 0) {
			p.id = value
		}
	case "retry":
		if ms, err := strconv.ParseUint(value, 10, 63); err == nil {
			p.retry = time.Duration(ms) * time.Millisecond
		}
	}
	return SseEvent{}, false
}

// executeEventStream opens a text/event-stream response.
func (c *Client) executeEventStream(ctx context.Context, req *request) (*EventStream, error) {
	req.stream = true
	req.SetHeader("Accept", "text/event-stream")
	if _, _, err := c.do(ctx, req); err != nil {
		return nil, err
	}
	resp := req.response
	mediaType, _, _ := mime.ParseMediaType(resp.Header.Get("Content-Type"))
	if mediaType != "text/event-stream" {
		resp.Body.Close()
		req.cancel()
		return nil, fmt.Errorf("@@PACKAGE_NAME@@: expected a text/event-stream response, got %q", mediaType)
	}
	return &EventStream{body: resp.Body, reader: bufio.NewReader(resp.Body), cancel: req.cancel}, nil
}

// Upload is a multipart file. Readers implementing io.Seeker are rewound for
// retries; other readers are sent once.
type Upload struct {
	Reader      io.Reader
	Filename    string
	ContentType string
}

// multipartField is a form field: a JSON-encodable value, or a file.
type multipartField struct {
	name  string
	value any
	file  *Upload
}

// SetUploadBody sends r as a raw application/octet-stream body.
func (r *request) SetUploadBody(body io.Reader) {
	r.contentType = "application/octet-stream"
	r.newBody = rewinder(body)
	_, seekable := body.(io.Seeker)
	r.oneShot = !seekable
}

// SetMultipartBody streams fields as a multipart/form-data body.
func (r *request) SetMultipartBody(fields []multipartField) {
	boundary, err := randomHex(16)
	if err != nil {
		r.err = err
		return
	}
	r.contentType = "multipart/form-data; boundary=" + boundary
	var rewinds []func() (io.Reader, error)
	for _, field := range fields {
		if field.file != nil {
			rewinds = append(rewinds, rewinder(field.file.Reader))
		}
	}
	r.newBody = func() (io.Reader, error) {
		for _, rewind := range rewinds {
			if _, err := rewind(); err != nil {
				return nil, err
			}
		}
		reader, writer := io.Pipe()
		go func() {
			form := multipart.NewWriter(writer)
			err := form.SetBoundary(boundary)
			for _, field := range fields {
				if err == nil {
					err = writeMultipartField(form, field)
				}
			}
			if err == nil {
				err = form.Close()
			}
			writer.CloseWithError(err)
		}()
		return reader, nil
	}
	for _, field := range fields {
		if field.file != nil {
			if _, ok := field.file.Reader.(io.Seeker); !ok {
				r.oneShot = true
			}
		}
	}
}

// rewinder returns the reader, seeked back to where it started when possible.
func rewinder(body io.Reader) func() (io.Reader, error) {
	seeker, ok := body.(io.Seeker)
	if !ok {
		return func() (io.Reader, error) { return body, nil }
	}
	start, err := seeker.Seek(0, io.SeekCurrent)
	return func() (io.Reader, error) {
		if err != nil {
			return nil, err
		}
		_, err := seeker.Seek(start, io.SeekStart)
		return body, err
	}
}

func writeMultipartField(form *multipart.Writer, field multipartField) error {
	header := textproto.MIMEHeader{}
	if field.file != nil {
		filename := field.file.Filename
		if filename == "" {
			filename = "file"
		}
		contentType := field.file.ContentType
		if contentType == "" {
			contentType = "application/octet-stream"
		}
		header.Set("Content-Disposition", mime.FormatMediaType("form-data", map[string]string{"name": field.name, "filename": filename}))
		header.Set("Content-Type", contentType)
		part, err := form.CreatePart(header)
		if err == nil {
			_, err = io.Copy(part, field.file.Reader)
		}
		return err
	}
	encoded, err := json.Marshal(field.value)
	if err != nil || string(encoded) == "null" {
		return err
	}
	header.Set("Content-Disposition", mime.FormatMediaType("form-data", map[string]string{"name": field.name}))
	var text string
	switch encoded[0] {
	case '"':
		err = json.Unmarshal(encoded, &text)
	case '{', '[':
		header.Set("Content-Type", "application/json")
		text = string(encoded)
	default:
		text = string(encoded)
	}
	if err != nil {
		return err
	}
	part, err := form.CreatePart(header)
	if err == nil {
		_, err = io.WriteString(part, text)
	}
	return err
}
