// Code generated by perseid from its shared runtime template. DO NOT EDIT.

package @@PACKAGE_NAME@@

import (
	"math/rand/v2"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// RequestOption adjusts a single call, on top of the client's [Options]. Every
// method takes them last:
//
//	opts := []@@PACKAGE_NAME@@.RequestOption{@@PACKAGE_NAME@@.WithTimeout(time.Minute), @@PACKAGE_NAME@@.WithMaxRetries(0)}
type RequestOption func(*callConfig)

// WithHeader sets a header on the request, replacing any value the SDK would send.
func WithHeader(name, value string) RequestOption {
	return func(c *callConfig) {
		c.headers.Set(name, value)
	}
}

// WithQuery sets a query parameter on the request, replacing any value the SDK
// would send, such as one the API added after this SDK version.
func WithQuery(name, value string) RequestOption {
	return func(c *callConfig) {
		c.query.Set(name, value)
	}
}

// WithJSONSet sets the JSON body property at path, keys separated by dots, to
// value, creating the objects on the way: WithJSONSet("metadata.source", "cli").
func WithJSONSet(path string, value any) RequestOption {
	return func(c *callConfig) {
		c.jsonSet = append(c.jsonSet, jsonSetting{strings.Split(path, "."), value})
	}
}

// WithIdempotencyKey sets the key that lets the server deduplicate retried
// requests, and makes a POST safe to retry.
func WithIdempotencyKey(key string) RequestOption {
	return WithHeader("Idempotency-Key", key)
}

// WithTimeout bounds each attempt of the request; zero or less disables the timeout.
func WithTimeout(timeout time.Duration) RequestOption {
	return func(c *callConfig) {
		c.timeout = max(timeout, 0)
	}
}

// WithMaxRetries sets how many times the request is retried; zero disables retries.
func WithMaxRetries(retries int) RequestOption {
	return func(c *callConfig) {
		c.retrySchedule = exponentialBackoff(max(retries, 0))
		c.jitter = true
	}
}

// WithResponseInto stores the HTTP response of the call in *dst, for its status
// and headers, such as the request id. Its body has already been read into the
// result, and can be read again; for an event stream, it is the stream itself.
// It is also set when the call fails with an [*APIError].
//
//	var resp *http.Response
//	opt := @@PACKAGE_NAME@@.WithResponseInto(&resp)
//	// after the call:
//	log.Print(resp.StatusCode, resp.Header.Get("X-Request-Id"))
func WithResponseInto(dst **http.Response) RequestOption {
	return func(c *callConfig) {
		c.response = dst
	}
}

// callConfig is the per-call view of the client configuration.
type callConfig struct {
	headers       http.Header
	query         url.Values
	jsonSet       []jsonSetting
	timeout       time.Duration
	retrySchedule []time.Duration
	jitter        bool
	response      **http.Response
}

type jsonSetting struct {
	path  []string
	value any
}

func (c *config) callConfig(options []RequestOption) callConfig {
	call := callConfig{
		headers:       http.Header{},
		query:         url.Values{},
		timeout:       c.timeout,
		retrySchedule: c.retrySchedule,
		jitter:        c.jitter,
	}
	for _, option := range options {
		option(&call)
	}
	return call
}

// maxRetryAfter caps how long a server's Retry-After can delay a retry.
const maxRetryAfter = time.Minute

// delay is the wait before retry number attempt+1. The default schedule is
// jittered by up to a quarter so that clients do not retry in lockstep.
func (c callConfig) delay(attempt int, retryAfter time.Duration) time.Duration {
	if retryAfter > 0 && retryAfter <= maxRetryAfter {
		return retryAfter
	}
	delay := c.retrySchedule[attempt]
	if c.jitter && delay > 0 {
		delay -= rand.N(delay/4 + 1)
	}
	return delay
}
