// Code generated by perseid from its shared runtime template. DO NOT EDIT.

package @@PACKAGE_NAME@@

import (
	"context"
	"iter"
)

// Page is one page of a paginated list operation, as its List method returns
// it: its items, and the way to the page after it.
//
//	for page != nil {
//		for _, item := range page.Items {
//			// ...
//		}
//		if page, err = page.NextPage(ctx); err != nil {
//			return err
//		}
//	}
type Page[T any] struct {
	// Items holds the items of this page.
	Items []T

	next func(ctx context.Context) (*Page[T], error)
}

// HasNextPage reports whether another page follows this one.
func (p *Page[T]) HasNextPage() bool {
	return p != nil && p.next != nil
}

// NextPage fetches the page after this one. It returns nil and no error after
// the last page.
func (p *Page[T]) NextPage(ctx context.Context) (*Page[T], error) {
	if !p.HasNextPage() {
		return nil, nil
	}
	return p.next(ctx)
}

// AutoPager iterates over every item of a paginated list operation, as its
// ListAutoPaging method returns it, fetching each page once the previous one
// is consumed: loop on Next, then check Err, or range over [AutoPager.All].
type AutoPager[T any] struct {
	ctx     context.Context
	first   func(ctx context.Context) (*Page[T], error)
	page    *Page[T]
	index   int
	current T
	err     error
}

func newAutoPager[T any](ctx context.Context, first func(ctx context.Context) (*Page[T], error)) *AutoPager[T] {
	return &AutoPager[T]{ctx: ctx, first: first}
}

// Next advances to the next item. It returns false once every item has been
// read or when a request failed, see Err.
func (p *AutoPager[T]) Next() bool {
	for p.err == nil {
		switch {
		case p.first != nil:
			p.page, p.err = p.first(p.ctx)
			p.first, p.index = nil, 0
		case p.page == nil:
			return false
		case p.index < len(p.page.Items):
			p.current = p.page.Items[p.index]
			p.index++
			return true
		case p.page.HasNextPage():
			p.page, p.err = p.page.NextPage(p.ctx)
			p.index = 0
		default:
			return false
		}
	}
	return false
}

// Current returns the item Next advanced to.
func (p *AutoPager[T]) Current() T { return p.current }

// Page returns the page holding the current item, nil before the first call
// to Next.
func (p *AutoPager[T]) Page() *Page[T] { return p.page }

// Err returns the error that stopped the iteration, if any.
func (p *AutoPager[T]) Err() error { return p.err }

// All yields every item, then the error that stopped the iteration, if any.
func (p *AutoPager[T]) All() iter.Seq2[T, error] {
	return func(yield func(T, error) bool) {
		for p.Next() {
			if !yield(p.current, nil) {
				return
			}
		}
		if p.err != nil {
			var zero T
			yield(zero, p.err)
		}
	}
}

type pageNumber interface {
	~int | ~int16 | ~int32 | ~int64 | ~uint16 | ~uint64
}

// reached reports whether n is at least total.
func reached[N, M pageNumber](n N, total M) bool {
	return int64(n) >= int64(total)
}
