# this file is @generated by Perseid; edit the shared runtime template.
"""(De)serialization support for the generated @@CLIENT_NAME@@ models.

The generated models are plain :mod:`dataclasses`. All JSON conversion lives
here so the generated code stays declarative and dependency free.

Conventions mirrored from the Rust SDK:

* ``None`` valued fields are omitted from the serialized payload (equivalent to
  ``#[serde(skip_serializing_if = "Option::is_none")]``), except required
  any-JSON (``t.Any``) fields, where ``None`` is a JSON ``null``.
* Unknown JSON keys are ignored when deserializing.
* ``Decimal`` values travel as JSON strings, ``datetime`` values as RFC 3339
  strings. Only finite decimals are valid: ``NaN`` and ``Infinity`` are
  rejected in both directions.
"""

from __future__ import annotations

import dataclasses
import datetime as _datetime
import enum
import json
import re
import typing as t
from decimal import Decimal

__all__ = [
    "BaseModel",
    "TaggedUnionModel",
    "@@CLIENT_NAME@@Error",
    "ModelParseError",
    "format_decimal",
    "parse_datetime",
    "parse_decimal",
    "to_json_value",
]

_T = t.TypeVar("_T", bound="BaseModel")


# `@@CLIENT_NAME@@Error` is defined here rather than in `errors.py` because the
# generated models import this module and `errors.py` imports the models. It is
# re-exported from `@@PACKAGE_NAME@@.errors` and `@@PACKAGE_NAME@@`, which is where to import it.
class @@CLIENT_NAME@@Error(Exception):
    """Base class for every error raised by this SDK."""


class ModelParseError(@@CLIENT_NAME@@Error, ValueError):
    """Raised when a payload cannot be mapped onto a model.

    It is also a :class:`ValueError`. A client call never lets it escape on its
    own: a response body that fails to parse raises
    :class:`@@PACKAGE_NAME@@.errors.ResponseDecodeError`, chained to this error.
    """


# --------------------------------------------------------------------------
# Serialization
# --------------------------------------------------------------------------


def to_json_value(value: t.Any) -> t.Any:
    """Convert a Python value into something ``json.dumps`` understands."""
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, BaseModel):
        return value.to_dict()
    if isinstance(value, enum.Enum):
        return to_json_value(value.value)
    if isinstance(value, Decimal):
        return format_decimal(value)
    if isinstance(value, _datetime.datetime):
        return format_datetime(value)
    if isinstance(value, _datetime.date):
        return value.isoformat()
    if isinstance(value, (list, tuple, set, frozenset)):
        return [to_json_value(v) for v in value]
    if isinstance(value, dict):
        return {str(k): to_json_value(v) for k, v in value.items()}
    return value


def format_decimal(value: Decimal) -> str:
    """Render a decimal as its JSON string form.

    Raises :class:`ValueError` for ``NaN`` and infinities, which the API does
    not accept and no other @@CLIENT_NAME@@ SDK can represent.
    """
    if not value.is_finite():
        raise ValueError(f"cannot serialize non-finite decimal {value!r}")
    return str(value)


def parse_decimal(value: t.Any) -> Decimal:
    """Parse a ``format: decimal`` JSON value into a finite :class:`Decimal`.

    The API sends decimals as JSON strings (``"12.50"``, ``"1e3"``). JSON
    numbers are rejected, since they may already have lost precision, and so
    are ``NaN``/``Infinity``, which are not decimals the API can produce.
    """
    if not isinstance(value, str):
        raise ModelParseError(f"expected a decimal string, got {value!r}")
    try:
        parsed = Decimal(value)
    except ArithmeticError as exc:  # `decimal.InvalidOperation`
        raise ModelParseError(f"invalid decimal {value!r}") from exc
    if not parsed.is_finite():
        raise ModelParseError(f"non-finite decimal {value!r}")
    return parsed


def format_datetime(value: _datetime.datetime) -> str:
    """Render a datetime as an RFC 3339 string (naive values are treated as UTC)."""
    if value.tzinfo is None:
        value = value.replace(tzinfo=_datetime.timezone.utc)
    return value.isoformat()


_FRACTION_RE = re.compile(r"(?<=[Tt ]\d\d:\d\d:\d\d)\.(\d+)")


def _normalize_fraction(match: "re.Match[str]") -> str:
    return "." + match.group(1)[:6].ljust(6, "0")


def parse_datetime(value: t.Any) -> _datetime.datetime:
    """Parse an ISO 8601 / RFC 3339 string into an aware :class:`datetime.datetime`.

    The result is always timezone-aware. The @@CLIENT_NAME@@ API sends every
    date-time in UTC, but some fields carry no UTC offset (e.g.
    ``2026-09-19T10:00:00.123456``): those are read as UTC. A string with an
    explicit offset (``Z``, ``+02:00``) keeps it. Fractional seconds may have
    1 to 9 digits: they are truncated to microseconds, the precision of
    :class:`datetime.datetime`.
    """
    if isinstance(value, _datetime.datetime):
        parsed = value
    elif isinstance(value, str):
        text = value
        # `fromisoformat` only learned about the `Z` suffix in Python 3.11.
        if text.endswith(("Z", "z")):
            text = text[:-1] + "+00:00"
        # Before Python 3.11, `fromisoformat` only accepts exactly 3 or 6
        # fractional digits, while the server sends anywhere from 1 to 9.
        # Rewrite the fraction to 6 digits so every version parses alike.
        text = _FRACTION_RE.sub(_normalize_fraction, text, count=1)
        try:
            parsed = _datetime.datetime.fromisoformat(text)
        except ValueError as exc:  # pragma: no cover - depends on server output
            raise ModelParseError(f"invalid date-time string {value!r}") from exc
    else:
        raise ModelParseError(f"expected a date-time string, got {type(value).__name__}")
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=_datetime.timezone.utc)
    return parsed


# --------------------------------------------------------------------------
# Deserialization
# --------------------------------------------------------------------------

_NoneType = type(None)
_hints_cache: t.Dict[type, t.Dict[str, t.Any]] = {}


def _type_hints(cls: type) -> t.Dict[str, t.Any]:
    hints = _hints_cache.get(cls)
    if hints is None:
        hints = t.get_type_hints(cls)
        _hints_cache[cls] = hints
    return hints


def _from_json_value(annotation: t.Any, value: t.Any, ctx: str) -> t.Any:
    if annotation is t.Any or annotation is None or annotation is _NoneType:
        return value

    origin = t.get_origin(annotation)

    if origin is t.Union:
        args = t.get_args(annotation)
        non_none = [a for a in args if a is not _NoneType]
        if value is None and _NoneType in args:
            return None
        if len(non_none) == 1:
            return _from_json_value(non_none[0], value, ctx)
        # Unions of models only appear inside tagged unions, which override
        # `from_dict` and never route through here.
        raise ModelParseError(f"{ctx}: cannot deserialize into union {annotation!r}")

    if origin in (list, set, frozenset, tuple):
        args = t.get_args(annotation)
        inner = args[0] if args else t.Any
        if not isinstance(value, list):
            raise ModelParseError(f"{ctx}: expected a list, got {type(value).__name__}")
        items = [_from_json_value(inner, v, f"{ctx}[{i}]") for i, v in enumerate(value)]
        return set(items) if origin in (set, frozenset) else items

    if origin is dict:
        args = t.get_args(annotation)
        inner = args[1] if len(args) == 2 else t.Any
        if not isinstance(value, dict):
            raise ModelParseError(
                f"{ctx}: expected an object, got {type(value).__name__}"
            )
        return {
            str(k): _from_json_value(inner, v, f"{ctx}.{k}") for k, v in value.items()
        }

    if origin is t.Literal:
        return value

    if isinstance(annotation, type):
        if issubclass(annotation, BaseModel):
            if not isinstance(value, dict):
                raise ModelParseError(
                    f"{ctx}: expected an object, got {type(value).__name__}"
                )
            return annotation.from_dict(value)
        if issubclass(annotation, enum.Enum):
            try:
                return annotation(value)
            except ValueError as exc:
                raise ModelParseError(f"{ctx}: unknown value {value!r}") from exc
        if annotation is _datetime.datetime:
            return parse_datetime(value)
        if annotation is _datetime.date:
            if isinstance(value, _datetime.date):
                return value
            return _datetime.date.fromisoformat(str(value))
        if annotation is Decimal:
            try:
                return parse_decimal(value)
            except ModelParseError as exc:
                raise ModelParseError(f"{ctx}: {exc}") from exc
        if annotation is bool:
            if not isinstance(value, bool):
                raise ModelParseError(f"{ctx}: expected a boolean, got {value!r}")
            return value
        if annotation is float:
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise ModelParseError(f"{ctx}: expected a number, got {value!r}")
            return float(value)
        if annotation is int:
            if isinstance(value, bool) or not isinstance(value, int):
                raise ModelParseError(f"{ctx}: expected an integer, got {value!r}")
            return value
        if annotation is str:
            if not isinstance(value, str):
                raise ModelParseError(f"{ctx}: expected a string, got {value!r}")
            return value

    return value


# --------------------------------------------------------------------------
# Base classes
# --------------------------------------------------------------------------


@dataclasses.dataclass
class BaseModel:
    """Base class of every generated model."""

    #: Maps python attribute names onto their JSON key, when they differ.
    _JSON_KEYS: t.ClassVar[t.Mapping[str, str]] = {}
    #: Attribute names whose (model) value is merged into the parent object.
    _FLATTENED: t.ClassVar[t.Tuple[str, ...]] = ()

    @classmethod
    def _json_key(cls, name: str) -> str:
        return cls._JSON_KEYS.get(name, name)

    def to_dict(self) -> t.Dict[str, t.Any]:
        """Serialize into a JSON-compatible dict, omitting ``None`` fields.

        The exception is a required any-JSON field (annotated ``t.Any``), where
        ``None`` is the JSON ``null`` value rather than "unset".
        """
        out: t.Dict[str, t.Any] = {}
        hints = _type_hints(type(self))
        for field in dataclasses.fields(self):
            value = getattr(self, field.name)
            if value is None and hints.get(field.name) is not t.Any:
                continue
            if field.name in self._FLATTENED:
                flattened = to_json_value(value)
                if not isinstance(flattened, dict):
                    raise TypeError(
                        f"{type(self).__name__}.{field.name} must serialize to an object"
                    )
                out.update(flattened)
                continue
            out[self._json_key(field.name)] = to_json_value(value)
        return out

    def to_json(self) -> str:
        return json.dumps(self.to_dict())

    @classmethod
    def from_dict(cls: t.Type[_T], data: t.Mapping[str, t.Any]) -> _T:
        """Build a model from a decoded JSON object, ignoring unknown keys."""
        if not isinstance(data, t.Mapping):
            raise ModelParseError(
                f"{cls.__name__}: expected an object, got {type(data).__name__}"
            )
        hints = _type_hints(cls)
        kwargs: t.Dict[str, t.Any] = {}
        for field in dataclasses.fields(cls):
            annotation = hints.get(field.name, t.Any)
            ctx = f"{cls.__name__}.{field.name}"
            if field.name in cls._FLATTENED:
                kwargs[field.name] = _from_json_value(annotation, data, ctx)
                continue
            key = cls._json_key(field.name)
            if key not in data:
                if _is_optional(annotation):
                    kwargs[field.name] = None
                    continue
                raise ModelParseError(f"{cls.__name__}: missing required field {key!r}")
            kwargs[field.name] = _from_json_value(annotation, data[key], ctx)
        return cls(**kwargs)

    @classmethod
    def from_json(cls: t.Type[_T], data: t.Union[str, bytes]) -> _T:
        return cls.from_dict(json.loads(data))


def _is_optional(annotation: t.Any) -> bool:
    return t.get_origin(annotation) is t.Union and _NoneType in t.get_args(annotation)


@dataclasses.dataclass
class TaggedUnionModel(BaseModel):
    """Base class for discriminated unions (``oneOf`` with a discriminator).

    Subclasses declare two dataclass fields: the discriminator (a ``Literal``
    of the variant names) and the content (a ``Union`` of the variant models).
    """

    #: JSON key holding the variant name.
    _DISCRIMINATOR: t.ClassVar[str] = ""
    #: Attribute holding the discriminator value.
    _DISCRIMINATOR_ATTR: t.ClassVar[str] = ""
    #: Attribute holding the variant payload.
    _CONTENT_ATTR: t.ClassVar[str] = ""
    #: JSON key holding the variant payload; ``None`` when internally tagged
    #: (i.e. the payload's fields sit next to the discriminator).
    _CONTENT_KEY: t.ClassVar[t.Optional[str]] = None
    #: Variant name -> model class (``None`` for variants without a payload).
    _VARIANTS: t.ClassVar[t.Mapping[str, t.Optional[t.Type[BaseModel]]]] = {}

    def to_dict(self) -> t.Dict[str, t.Any]:
        tag = getattr(self, self._DISCRIMINATOR_ATTR)
        if tag not in self._VARIANTS:
            raise ValueError(f"{type(self).__name__}: unknown variant {tag!r}")
        content = getattr(self, self._CONTENT_ATTR)
        out: t.Dict[str, t.Any] = {}
        if self._CONTENT_KEY is None:
            if content is not None:
                serialized = to_json_value(content)
                if not isinstance(serialized, dict):
                    raise TypeError(
                        f"{type(self).__name__}: variant {tag!r} must serialize to an object"
                    )
                out.update(serialized)
            out[self._DISCRIMINATOR] = tag
        else:
            out[self._DISCRIMINATOR] = tag
            out[self._CONTENT_KEY] = to_json_value(content)
        return out

    @classmethod
    def from_dict(cls: t.Type[_T], data: t.Mapping[str, t.Any]) -> _T:
        if not isinstance(data, t.Mapping):
            raise ModelParseError(
                f"{cls.__name__}: expected an object, got {type(data).__name__}"
            )
        assert issubclass(cls, TaggedUnionModel)
        if cls._DISCRIMINATOR not in data:
            raise ModelParseError(
                f"{cls.__name__}: missing discriminator {cls._DISCRIMINATOR!r}"
            )
        tag = data[cls._DISCRIMINATOR]
        if tag not in cls._VARIANTS:
            raise ModelParseError(f"{cls.__name__}: unknown variant {tag!r}")
        variant = cls._VARIANTS[tag]
        content: t.Any = None
        if variant is not None:
            if cls._CONTENT_KEY is None:
                payload: t.Any = data
            else:
                payload = data.get(cls._CONTENT_KEY, {})
            if not isinstance(payload, t.Mapping):
                raise ModelParseError(
                    f"{cls.__name__}: variant {tag!r} payload must be an object"
                )
            content = variant.from_dict(payload)
        return cls(**{cls._DISCRIMINATOR_ATTR: tag, cls._CONTENT_ATTR: content})
