# this file is @generated by Perseid; edit the shared runtime template.
"""Unions of several models without a discriminator, and expandable ids."""

from __future__ import annotations

import typing as t

from .serialization import (
    BaseModel,
    Discriminator,
    ModelParseError,
    UnknownVariant,
    from_json_value,
    to_json_value,
)

__all__ = ["ObjectUnion", "as_variant", "expandable_id"]

_M = t.TypeVar("_M", bound=BaseModel)


class ObjectUnion(Discriminator):
    """Annotation metadata of a union of several models without a discriminator.

    ``others`` is the union of its other members, told apart by JSON type. With
    ``when``, an object is the first model whose properties it has, equal to
    the given values (any value for ``...``). With ``best_match``, it is the
    model whose required properties are all present and which has the most of
    its known properties, the first one on ties. A member that is not a model
    (a free-form ``dict``) matches any object and comes last. When a member
    fails to decode the next one is tried. An object that no member
    decodes is kept as an :class:`UnknownVariant` with an empty tag.
    """

    def __init__(
        self,
        others: t.Any = None,
        *,
        when: t.Sequence[tuple[t.Any, t.Mapping[str, t.Any]]] = (),
        best_match: t.Sequence[tuple[t.Any, tuple[str, ...], tuple[str, ...]]] = (),
    ) -> None:
        super().__init__("", {})
        self.others = others
        self.when = [(model, dict(conditions)) for model, conditions in when]
        self.best_match = list(best_match)

    def candidates(self, value: t.Mapping[str, t.Any]) -> list[t.Any]:
        """The members ``value`` may be, the likeliest first: the ones to try in order."""
        found: list[t.Any] = [
            model
            for model, conditions in self.when
            if all(
                key in value and (want is ... or _same_json(value[key], want))
                for key, want in conditions.items()
            )
        ]
        scored = [
            (sum(key in value for key in known), model)
            for model, required, known in self.best_match
            if all(key in value for key in required)
        ]
        # Stable: the most known properties first, the declaration (rank) order on ties.
        found.extend(model for _, model in sorted(scored, key=lambda pair: -pair[0]))
        return found

    def pick(self, value: t.Mapping[str, t.Any]) -> t.Any:
        found = self.candidates(value)
        return found[0] if found else None

    def parse(self, value: t.Any, ctx: str) -> t.Any:
        if not isinstance(value, t.Mapping):
            if self.others is None:
                raise ModelParseError(f"{ctx}: expected an object, got {type(value).__name__}")
            return from_json_value(self.others, value)
        for model in self.candidates(value):
            try:
                return from_json_value(model, dict(value))
            except ModelParseError:
                continue
        return UnknownVariant("", dict(value))

    def serialize(self, value: t.Any) -> t.Any:
        return to_json_value(value)


def _same_json(value: t.Any, want: t.Any) -> bool:
    return bool(value == want and isinstance(value, bool) == isinstance(want, bool))


def as_variant(value: t.Any, model: type[_M]) -> _M:
    """``value``, a union member, read as ``model``: another variant than the one decoding picked."""
    return model.from_dict(to_json_value(value))


def expandable_id(value: t.Any) -> str | None:
    """The id of an expandable field: the string, or the ``id`` of the expanded object."""
    if isinstance(value, str):
        return value
    id = getattr(value, "id", None)
    return id if isinstance(id, str) else None
