// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_INTERNAL_PACKAGE@@;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import @@JAVA_PACKAGE@@.ApiResponse;
import @@JAVA_PACKAGE@@.@@CLIENT_NAME@@Options;
import @@JAVA_PACKAGE@@.RequestOptions;
import @@JAVA_PACKAGE@@.exceptions.@@CLIENT_NAME@@Exception;
import @@JAVA_PACKAGE@@.exceptions.ApiConnectionException;
import @@JAVA_PACKAGE@@.exceptions.ApiException;
import @@JAVA_PACKAGE@@.exceptions.ApiTimeoutException;
import @@JAVA_PACKAGE@@.exceptions.AuthenticationException;
import @@JAVA_PACKAGE@@.exceptions.BadRequestException;
import @@JAVA_PACKAGE@@.exceptions.ConflictException;
import @@JAVA_PACKAGE@@.exceptions.InternalServerException;
import @@JAVA_PACKAGE@@.exceptions.InvalidDataException;
import @@JAVA_PACKAGE@@.exceptions.NotFoundException;
import @@JAVA_PACKAGE@@.exceptions.PermissionDeniedException;
import @@JAVA_PACKAGE@@.exceptions.RateLimitException;
import @@JAVA_PACKAGE@@.exceptions.UnprocessableEntityException;
import @@JAVA_PACKAGE@@.streaming.EventStream;
import @@JAVA_PACKAGE@@.streaming.SseEvent;
import java.io.IOException;
import java.io.InterruptedIOException;
import java.net.SocketTimeoutException;
import java.time.Duration;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;
import okhttp3.Callback;
import okhttp3.Dispatcher;
import okhttp3.FormBody;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.Interceptor;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

/** Sends the requests of the generated resources. Internal: not part of the SDK's API. */
public final class @@CLIENT_NAME@@HttpClient implements AutoCloseable {
    private static final MediaType JSON = MediaType.parse("application/json");
    private static final Set<String> IDEMPOTENT_METHODS =
            Set.of("GET", "HEAD", "PUT", "DELETE", "OPTIONS", "TRACE");
    private static final Set<String> BODY_METHODS = Set.of("POST", "PUT", "PATCH");
    private static final Duration MAX_RETRY_AFTER = Duration.ofSeconds(60);
    private static final Duration MAX_CONNECT_TIMEOUT = Duration.ofSeconds(10);
    private static final long DEFAULT_BACKOFF_MILLIS = 500;
    private static final System.Logger LOGGER = System.getLogger("@@JAVA_PACKAGE@@");

    private final HttpUrl baseUrl;
    private final Map<String, String> defaultHeaders;
    private final List<Long> retrySchedule;
    private final OkHttpClient client;
    private final boolean ownsClient;
    private final ObjectMapper objectMapper = Utils.objectMapper();
    private final @@CLIENT_NAME@@Auth auth;
    private final List<List<String>> security;

    /**
     * A client sending to {@code baseUrl} with the settings of {@code options}.
     *
     * @param baseUrl the API root
     * @param defaultHeaders headers of every request
     * @param options the client options
     * @param auth the credentials
     */
    public @@CLIENT_NAME@@HttpClient(
            HttpUrl baseUrl,
            Map<String, String> defaultHeaders,
            @@CLIENT_NAME@@Options options,
            @@CLIENT_NAME@@Auth auth) {
        this(
                baseUrl,
                Map.copyOf(defaultHeaders),
                options.retrySchedule(),
                okHttpClient(options),
                options.httpClient().isEmpty(),
                auth,
                null);
        if (auth != null) {
            auth.useTokenFetcher(this::fetchToken);
        }
    }

    /**
     * Requests an access token with the OAuth2 client credentials grant, through this client's
     * interceptors, timeouts and retries like any other request.
     */
    private @@CLIENT_NAME@@Auth.Grant fetchToken(
            String tokenUrl, String scope, String clientId, String clientSecret, boolean inBody) {
        HttpUrl url;
        if (tokenUrl.contains("://")) {
            url = HttpUrl.parse(tokenUrl);
            if (url == null) {
                throw new IllegalArgumentException("Invalid token URL: " + tokenUrl);
            }
        } else {
            // An absolute-path reference resolves against the origin of the base URL, any other
            // relative one under it; a query stays a query.
            if (tokenUrl.startsWith("/")) {
                url = baseUrl.resolve(tokenUrl);
            } else {
                int query = tokenUrl.indexOf('?');
                HttpUrl.Builder joined =
                        baseUrl.newBuilder().addPathSegments(query < 0 ? tokenUrl : tokenUrl.substring(0, query));
                if (query >= 0) {
                    joined.encodedQuery(tokenUrl.substring(query + 1));
                }
                url = joined.build();
            }
            if (url == null) {
                throw new IllegalArgumentException("Invalid token URL: " + tokenUrl);
            }
        }
        FormBody.Builder form = new FormBody.Builder().add("grant_type", "client_credentials");
        if (!scope.isEmpty()) {
            form.add("scope", scope);
        }
        Headers headers = Headers.of();
        if (inBody) {
            form.add("client_id", clientId).add("client_secret", clientSecret);
        } else {
            headers = Headers.of("Authorization", @@CLIENT_NAME@@Auth.basicAuthorization(clientId, clientSecret));
        }
        JsonNode answer =
                withSecurity(List.of())
                        .call("POST", url)
                        .headers(headers)
                        .body(form.build())
                        .returning(JsonNode.class)
                        .send();
        String accessToken = answer == null ? "" : answer.path("access_token").asText("");
        if (accessToken.isEmpty()) {
            throw new InvalidDataException("the token endpoint answered without an access_token");
        }
        JsonNode expires = answer.path("expires_in");
        double seconds = -1;
        if (expires.isNumber()) {
            seconds = Math.max(expires.asDouble(), 0);
        } else if (expires.isTextual()) {
            try {
                seconds = Math.max(Double.parseDouble(expires.asText().trim()), 0);
            } catch (NumberFormatException ignored) {
                // Declares no usable lifetime.
            }
        }
        return new @@CLIENT_NAME@@Auth.Grant(accessToken, seconds);
    }

    private @@CLIENT_NAME@@HttpClient(
            HttpUrl baseUrl,
            Map<String, String> defaultHeaders,
            List<Long> retrySchedule,
            OkHttpClient client,
            boolean ownsClient,
            @@CLIENT_NAME@@Auth auth,
            List<List<String>> security) {
        this.baseUrl = baseUrl;
        this.defaultHeaders = defaultHeaders;
        this.retrySchedule = retrySchedule;
        this.client = client;
        this.ownsClient = ownsClient;
        this.auth = auth;
        this.security = security;
    }

    /**
     * A client for operations whose security requirement differs from the API-wide one.
     *
     * @param security alternatives of security scheme names
     * @return a client sharing this one's connections
     */
    public @@CLIENT_NAME@@HttpClient withSecurity(List<List<String>> security) {
        return new @@CLIENT_NAME@@HttpClient(
                baseUrl, defaultHeaders, retrySchedule, client, false, auth, security);
    }

    /** Releases the threads and connections of the OkHttp client, unless it was given. */
    @Override
    public void close() {
        if (ownsClient) {
            client.dispatcher().executorService().shutdown();
            client.connectionPool().evictAll();
        }
    }

    private static OkHttpClient okHttpClient(@@CLIENT_NAME@@Options options) {
        OkHttpClient.Builder builder =
                options.httpClient()
                        .map(OkHttpClient::newBuilder)
                        .orElseGet(() -> withTimeout(new OkHttpClient.Builder(), options.timeout()));
        if (options.httpClient().isEmpty()) {
            Dispatcher dispatcher = new Dispatcher();
            dispatcher.setMaxRequests(64);
            dispatcher.setMaxRequestsPerHost(64);
            builder.dispatcher(dispatcher);
        }
        options.interceptors().forEach(builder::addInterceptor);
        builder.addInterceptor(logger(options.debug() ? System.Logger.Level.INFO : System.Logger.Level.DEBUG));
        builder.addInterceptor(RESTORE_RETRY_AFTER);
        builder.addNetworkInterceptor(HIDE_RETRY_AFTER);
        return builder.build();
    }

    /** The header holding the {@code Retry-After} values that {@link #HIDE_RETRY_AFTER} hid. */
    private static final String HIDDEN_RETRY_AFTER = "x-@@HEADER_PREFIX@@-hidden-retry-after";

    /**
     * OkHttp silently repeats a request answered 408 without {@code Retry-After}, or 503 with
     * {@code Retry-After: 0}. To leave every retry to the client's own loop, which honors
     * {@code maxRetries} and idempotency, the {@code Retry-After} of these responses reads
     * "never" to OkHttp, its values set aside until {@link #RESTORE_RETRY_AFTER} puts them back.
     */
    private static final Interceptor HIDE_RETRY_AFTER =
            chain -> {
                Response response = chain.proceed(chain.request());
                if (response.code() != 408 && response.code() != 503) {
                    return response;
                }
                Headers.Builder headers = response.headers().newBuilder().removeAll("Retry-After");
                headers.add(HIDDEN_RETRY_AFTER, "-");
                for (String value : response.headers("Retry-After")) {
                    headers.add(HIDDEN_RETRY_AFTER, ":" + value);
                }
                return response.newBuilder().headers(headers.set("Retry-After", "never").build()).build();
            };

    /** Puts back the {@code Retry-After} values that {@link #HIDE_RETRY_AFTER} set aside. */
    private static final Interceptor RESTORE_RETRY_AFTER =
            chain -> {
                Response response = chain.proceed(chain.request());
                List<String> hidden = response.headers(HIDDEN_RETRY_AFTER);
                if (hidden.isEmpty()) {
                    return response;
                }
                Headers.Builder headers =
                        response.headers().newBuilder().removeAll(HIDDEN_RETRY_AFTER).removeAll("Retry-After");
                for (String value : hidden) {
                    if (value.startsWith(":")) {
                        headers.add("Retry-After", value.substring(1));
                    }
                }
                return response.newBuilder().headers(headers.build()).build();
            };

    private static Interceptor logger(System.Logger.Level level) {
        return chain -> {
            Request request = chain.request();
            if (!LOGGER.isLoggable(level)) {
                return chain.proceed(request);
            }
            LOGGER.log(level, "{0} {1}", request.method(), request.url());
            Response response = chain.proceed(request);
            LOGGER.log(level, "{0} {1} -> {2}", request.method(), request.url(), response.code());
            return response;
        };
    }

    private static OkHttpClient.Builder withTimeout(OkHttpClient.Builder builder, Duration timeout) {
        Duration connectTimeout =
                timeout.compareTo(MAX_CONNECT_TIMEOUT) < 0 ? timeout : MAX_CONNECT_TIMEOUT;
        return builder.connectTimeout(connectTimeout)
                .readTimeout(timeout)
                .writeTimeout(timeout)
                .callTimeout(timeout);
    }

    /**
     * The Jackson type of a list of {@code item}.
     *
     * @param item the item class
     * @return the list type
     */
    public JavaType listOf(Class<?> item) {
        return objectMapper.getTypeFactory().constructCollectionType(List.class, item);
    }

    /**
     * A builder for a URL under the server URL, keeping its path (e.g. {@code /v1}).
     *
     * @return the builder
     */
    public HttpUrl.Builder newUrlBuilder() {
        return baseUrl.newBuilder();
    }

    /**
     * A request to {@code url}, sent once its response type is set.
     *
     * @param method the HTTP method
     * @param url the URL, query included
     * @return the request builder
     */
    public Call call(String method, HttpUrl url) {
        return new Call(method, url);
    }

    /** How the body of a successful response is read. */
    @FunctionalInterface
    private interface BodyReader<T> {
        T read(Response response) throws IOException;
    }

    /** One request, before its response type is set. */
    public final class Call {
        private final String method;
        private final HttpUrl url;
        private Headers headers;
        private Object json;
        private Object form;
        private Collection<String> deepObject = List.of();
        private Collection<String> unexploded = List.of();
        private RequestBody body;
        private final Map<String, Class<?>> errors = new HashMap<>();
        private RequestOptions options = RequestOptions.none();

        private Call(String method, HttpUrl url) {
            this.method = method;
            this.url = url;
        }

        /**
         * Headers of the operation's parameters.
         *
         * @param headers the headers
         * @return this call
         */
        public Call headers(Headers headers) {
            this.headers = headers;
            return this;
        }

        /**
         * A JSON body, left out when null.
         *
         * @param body the body
         * @return this call
         */
        public Call json(Object body) {
            this.json = body;
            return this;
        }

        /**
         * An {@code application/x-www-form-urlencoded} body, given the properties whose lists are
         * sent as {@code name[]=item} ({@code deepObject}) or comma-separated ({@code explode:
         * false}).
         *
         * @param body the body
         * @param deepObject the deepObject properties
         * @param unexploded the comma-separated properties
         * @return this call
         */
        public Call form(Object body, Collection<String> deepObject, Collection<String> unexploded) {
            this.form = body;
            this.deepObject = deepObject;
            this.unexploded = unexploded;
            return this;
        }

        /**
         * A raw or multipart body. Streamed bodies are sent once, without retries.
         *
         * @param body the body
         * @return this call
         */
        public Call body(RequestBody body) {
            this.body = body;
            return this;
        }

        /**
         * The schema of error bodies with these statuses.
         *
         * @param schema the error model
         * @param statuses {@code "404"}, {@code "4XX"} or {@code "default"}
         * @return this call
         */
        public Call errors(Class<?> schema, String... statuses) {
            for (String status : statuses) {
                errors.put(status, schema);
            }
            return this;
        }

        /**
         * The per-call settings.
         *
         * @param options the options
         * @return this call
         */
        public Call options(RequestOptions options) {
            this.options = options == null ? RequestOptions.none() : options;
            return this;
        }

        /**
         * Expects a JSON body of {@code type}.
         *
         * @param <T> the body type
         * @param type the body class
         * @return the exchange
         */
        public <T> Exchange<T> returning(Class<T> type) {
            return returning(objectMapper.getTypeFactory().constructType(type));
        }

        /**
         * Expects a JSON body of {@code type}.
         *
         * @param <T> the body type
         * @param type the body type
         * @return the exchange
         */
        public <T> Exchange<T> returning(TypeReference<T> type) {
            return returning(objectMapper.getTypeFactory().constructType(type));
        }

        /**
         * Expects a JSON body of {@code type}.
         *
         * @param <T> the body type
         * @param type the body type
         * @return the exchange
         */
        public <T> Exchange<T> returning(JavaType type) {
            return new Exchange<>(this, false, response -> readJson(response, type, true));
        }

        /**
         * Expects a JSON body of {@code type}, or none.
         *
         * @param <T> the body type
         * @param type the body class
         * @return the exchange, empty without a body
         */
        public <T> Exchange<Optional<T>> returningOptional(Class<T> type) {
            return returningOptional(objectMapper.getTypeFactory().constructType(type));
        }

        /**
         * Expects a JSON body of {@code type}, or none.
         *
         * @param <T> the body type
         * @param type the body type
         * @return the exchange, empty without a body
         */
        public <T> Exchange<Optional<T>> returningOptional(TypeReference<T> type) {
            return returningOptional(objectMapper.getTypeFactory().constructType(type));
        }

        private <T> Exchange<Optional<T>> returningOptional(JavaType type) {
            return new Exchange<>(this, false, response -> Optional.ofNullable(readJson(response, type, false)));
        }

        /**
         * Expects no body, or ignores it.
         *
         * @return the exchange
         */
        public Exchange<Void> returningNothing() {
            return new Exchange<>(this, false, response -> null);
        }

        /**
         * Expects a binary body.
         *
         * @return the exchange
         */
        public Exchange<byte[]> returningBytes() {
            return new Exchange<>(
                    this, false, response -> response.body() == null ? new byte[0] : response.body().bytes());
        }

        /**
         * Expects a text body, read in the charset the response declares, UTF-8 by default.
         *
         * @return the exchange
         */
        public Exchange<String> returningText() {
            return new Exchange<>(
                    this, false, response -> response.body() == null ? "" : response.body().string());
        }

        /**
         * Expects a {@code text/event-stream} body, yielding its raw events.
         *
         * @return the exchange
         */
        public Exchange<EventStream<SseEvent>> returningEvents() {
            return new Exchange<>(this, true, EventStream::raw);
        }

        /**
         * Expects a {@code text/event-stream} body whose events carry {@code type} as JSON.
         *
         * @param <T> the event type
         * @param type the event class
         * @return the exchange
         */
        public <T> Exchange<EventStream<T>> returningEvents(Class<T> type) {
            JavaType eventType = objectMapper.getTypeFactory().constructType(type);
            return new Exchange<>(
                    this, true, response -> EventStream.typed(response, event -> decodeEvent(event, eventType)));
        }

        /**
         * Expects a {@code text/event-stream} body whose events carry {@code type} as JSON, for
         * event types a class cannot name, such as unions or lists.
         *
         * @param <T> the event type
         * @param type the event type
         * @return the exchange
         */
        public <T> Exchange<EventStream<T>> returningEvents(TypeReference<T> type) {
            JavaType eventType = objectMapper.getTypeFactory().constructType(type);
            return new Exchange<>(
                    this, true, response -> EventStream.typed(response, event -> decodeEvent(event, eventType)));
        }

        private Request request(boolean streaming) {
            RequestBody content = body;
            if (json != null) {
                try {
                    content = RequestBody.create(objectMapper.writeValueAsString(json), JSON);
                } catch (JsonProcessingException e) {
                    throw new @@CLIENT_NAME@@Exception("cannot serialize the request body: " + e.getOriginalMessage(), e);
                }
            } else if (form != null) {
                content = formBody(form, deepObject, unexploded);
            }
            String verb = method.toUpperCase();
            if (content == null && BODY_METHODS.contains(verb)) {
                content = RequestBody.create(new byte[0], null);
            }
            Request.Builder request = new Request.Builder().url(url).method(verb, content);
            defaultHeaders.forEach(request::header);
            if (auth != null) {
                auth.apply(request, url, security);
            }
            if (headers != null) {
                headers.forEach(pair -> setHeader(request, pair.getFirst(), pair.getSecond()));
            }
            if (streaming) {
                request.header("Accept", "text/event-stream");
            }
            options.headers().forEach((name, value) -> setHeader(request, name, value));
            options.idempotencyKey().ifPresent(key -> request.header("idempotency-key", key));
            // Cookie parameters, the API key cookie and a Cookie header of the call share one header.
            List<String> cookies = request.build().headers("Cookie");
            if (cookies.size() > 1) {
                request.header("Cookie", String.join("; ", cookies));
            }
            String idempotencyKey = request.build().header("idempotency-key");
            if ((idempotencyKey == null || idempotencyKey.isEmpty()) && verb.equals("POST")) {
                request.header("idempotency-key", "auto_" + UUID.randomUUID());
            }
            request.header(
                    "x-@@HEADER_PREFIX@@-req-id",
                    String.valueOf(ThreadLocalRandom.current().nextLong(0, Long.MAX_VALUE)));
            return request.build();
        }

        private OkHttpClient http(boolean streaming) {
            if (!streaming && options.timeout().isEmpty()) {
                return client;
            }
            OkHttpClient.Builder builder = client.newBuilder();
            options.timeout().ifPresent(timeout -> withTimeout(builder, timeout));
            if (streaming) {
                builder.readTimeout(Duration.ZERO).callTimeout(Duration.ZERO);
            }
            return builder.build();
        }

        private int retries() {
            return options.maxRetries().orElse(retrySchedule.size());
        }
    }

    /**
     * A request and the way to read its response, sent blocking or asynchronously, returning the
     * body or the whole response.
     *
     * @param <T> the type of the body
     */
    public final class Exchange<T> {
        private final Call call;
        private final boolean streaming;
        private final BodyReader<T> reader;

        private Exchange(Call call, boolean streaming, BodyReader<T> reader) {
            this.call = call;
            this.streaming = streaming;
            this.reader = reader;
        }

        /**
         * Sends the request, blocking.
         *
         * @return the body
         */
        public T send() {
            return sendRaw().body();
        }

        /**
         * Sends the request, blocking.
         *
         * @return the status, headers and body
         */
        public ApiResponse<T> sendRaw() {
            Request request = call.request(streaming);
            Response response;
            try {
                response = execute(request, call.http(streaming), call.retries());
            } catch (IOException e) {
                throw transportError(e);
            }
            return handle(response);
        }

        /**
         * Sends the request without blocking.
         *
         * @return the body, once received
         */
        public CompletableFuture<T> sendAsync() {
            return sendAsync(ApiResponse::body);
        }

        /**
         * Sends the request without blocking.
         *
         * @return the status, headers and body, once received
         */
        public CompletableFuture<ApiResponse<T>> sendRawAsync() {
            return sendAsync(Function.identity());
        }

        private <R> CompletableFuture<R> sendAsync(Function<ApiResponse<T>, R> result) {
            CompletableFuture<R> out = new CompletableFuture<>();
            CompletableFuture<Response> responses;
            try {
                responses = executeAsync(call.request(streaming), call.http(streaming), call.retries());
            } catch (RuntimeException e) {
                out.completeExceptionally(e);
                return out;
            }
            responses.whenComplete(
                    (response, error) -> {
                        if (error != null) {
                            out.completeExceptionally(error);
                            return;
                        }
                        try {
                            if (!out.complete(result.apply(handle(response)))) {
                                response.close();
                            }
                        } catch (RuntimeException e) {
                            out.completeExceptionally(e);
                        }
                    });
            out.whenComplete(
                    (value, error) -> {
                        if (out.isCancelled()) {
                            responses.cancel(false);
                        }
                    });
            return out;
        }

        private ApiResponse<T> handle(Response response) {
            boolean keepOpen = false;
            try {
                if (!response.isSuccessful()) {
                    throw error(response, call.errors);
                }
                if (streaming) {
                    checkEventStream(response);
                }
                T body = reader.read(response);
                keepOpen = streaming;
                return new ApiResponse<>(response.code(), response.headers(), body);
            } catch (JsonProcessingException e) {
                throw new InvalidDataException(
                        "the response body is not the JSON this SDK expects: " + e.getOriginalMessage(), e);
            } catch (IOException e) {
                throw transportError(e);
            } finally {
                if (!keepOpen) {
                    response.close();
                }
            }
        }
    }

    private static void checkEventStream(Response response) {
        MediaType contentType = response.body() == null ? null : response.body().contentType();
        if (contentType == null
                || !"text/event-stream".equals(contentType.type() + "/" + contentType.subtype())) {
            throw new InvalidDataException(
                    "expected a text/event-stream response, got "
                            + contentType
                            + ": does the request ask for a stream?");
        }
    }

    private <T> T readJson(Response response, JavaType type, boolean required) throws IOException {
        if (response.code() == 204 || response.code() == 205) {
            return null;
        }
        String text = response.body() == null ? "" : response.body().string();
        if (text.isBlank()) {
            if (required) {
                throw new InvalidDataException(
                        "the " + response.code() + " response has an empty body, but a JSON body was expected");
            }
            return null;
        }
        return objectMapper.readValue(text, type);
    }

    private <T> T decodeEvent(SseEvent event, JavaType type) {
        try {
            return objectMapper.readValue(event.data(), type);
        } catch (JsonProcessingException e) {
            throw new InvalidDataException(
                    "the data of a `" + event.event() + "` event is not the JSON this SDK expects: "
                            + e.getOriginalMessage(),
                    e);
        }
    }

    private RequestBody formBody(
            Object value, Collection<String> deepObject, Collection<String> unexploded) {
        List<Map.Entry<String, String>> pairs = new ArrayList<>();
        objectMapper
                .valueToTree(value)
                .fields()
                .forEachRemaining(
                        field ->
                                Utils.encodeParam(
                                        field.getKey(),
                                        field.getValue(),
                                        deepObject.contains(field.getKey()),
                                        !unexploded.contains(field.getKey()),
                                        pairs));
        FormBody.Builder form = new FormBody.Builder();
        pairs.forEach(pair -> form.add(pair.getKey(), pair.getValue()));
        return form.build();
    }

    private static ApiConnectionException transportError(IOException e) {
        boolean timeout =
                e instanceof SocketTimeoutException
                        || (e instanceof InterruptedIOException && "timeout".equals(e.getMessage()));
        return timeout ? new ApiTimeoutException(e) : new ApiConnectionException(e);
    }

    private ApiException error(Response response, Map<String, Class<?>> errors) throws IOException {
        String body = response.body() == null ? "" : response.body().string();
        int code = response.code();
        String message =
                response.request().method()
                        + " "
                        + response.request().url().encodedPath()
                        + " failed with status "
                        + code
                        + (body.isEmpty() ? "" : ": " + abbreviate(body));
        Headers headers = response.headers();
        Object error = errorBody(body, code, errors);
        switch (code) {
            case 400:
                return new BadRequestException(message, code, headers, body, error);
            case 401:
                return new AuthenticationException(message, code, headers, body, error);
            case 403:
                return new PermissionDeniedException(message, code, headers, body, error);
            case 404:
                return new NotFoundException(message, code, headers, body, error);
            case 409:
                return new ConflictException(message, code, headers, body, error);
            case 422:
                return new UnprocessableEntityException(message, code, headers, body, error);
            case 429:
                return new RateLimitException(message, code, headers, body, error);
            default:
                return code >= 500
                        ? new InternalServerException(message, code, headers, body, error)
                        : new ApiException(message, code, headers, body, error);
        }
    }

    private static String abbreviate(String body) {
        String line = body.strip().replaceAll("\\s+", " ");
        return line.length() <= 500 ? line : line.substring(0, 500) + "...";
    }

    /** {@code body} as the schema declared for {@code code}, else as JSON, else null. */
    private Object errorBody(String body, int code, Map<String, Class<?>> errors) {
        if (body.isEmpty()) {
            return null;
        }
        Class<?> type = errors.get(String.valueOf(code));
        if (type == null) {
            type = errors.get(code / 100 + "XX");
        }
        if (type == null) {
            type = errors.get("default");
        }
        if (type != null) {
            try {
                return objectMapper.readValue(body, type);
            } catch (IOException | RuntimeException e) {
                // Not the declared schema: fall back to the JSON value.
            }
        }
        try {
            return objectMapper.readTree(body);
        } catch (IOException e) {
            return null;
        }
    }

    /** Sets a header; {@code Cookie} values add up, the others replace. */
    private static void setHeader(Request.Builder request, String name, String value) {
        if (name.equalsIgnoreCase("Cookie")) {
            request.addHeader(name, value);
        } else {
            request.header(name, value);
        }
    }

    private static boolean retryable(Request request) {
        RequestBody body = request.body();
        return (IDEMPOTENT_METHODS.contains(request.method())
                        || request.header("idempotency-key") != null)
                && (body == null || !body.isOneShot());
    }

    private static Request attempt(Request request, int attempt) {
        return attempt == 0
                ? request
                : request.newBuilder()
                        .header("x-@@HEADER_PREFIX@@-retry-count", String.valueOf(attempt))
                        .build();
    }

    /**
     * Retries transport errors, 408, 429 and 5xx responses of requests that are safe to repeat:
     * idempotent methods, or those carrying an idempotency key.
     */
    private Response execute(Request request, OkHttpClient http, int retries) throws IOException {
        boolean retryable = retryable(request);
        // An access token the API rejects is replaced once, without using up a retry.
        boolean renewed = false;
        for (int attempt = 0; ; attempt++) {
            boolean lastAttempt = !retryable || attempt >= retries;
            Response response;
            try {
                response = http.newCall(attempt(request, attempt)).execute();
            } catch (IOException e) {
                if (lastAttempt || Thread.currentThread().isInterrupted()) {
                    throw e;
                }
                sleep(backoff(attempt));
                continue;
            }
            if (!renewed && rejectedToken(request, response)) {
                renewed = true;
                response.close();
                request = auth.renew(request);
                attempt--;
                continue;
            }
            Duration delay = lastAttempt ? null : retryDelay(response, attempt);
            if (delay == null) {
                return response;
            }
            response.close();
            sleep(delay);
        }
    }

    /** Whether {@code response} rejects the OAuth2 access token {@code request} carries. */
    private boolean rejectedToken(Request request, Response response) {
        RequestBody body = request.body();
        return response.code() == 401
                && auth != null
                && (body == null || !body.isOneShot())
                && auth.renewable(request);
    }

    private CompletableFuture<Response> executeAsync(Request request, OkHttpClient http, int retries) {
        CompletableFuture<Response> result = new CompletableFuture<>();
        executeAsync(request, http, retryable(request) ? retries : 0, 0, false, result);
        return result;
    }

    private void executeAsync(
            Request request,
            OkHttpClient http,
            int retries,
            int attempt,
            boolean renewed,
            CompletableFuture<Response> result) {
        if (result.isDone()) {
            return;
        }
        boolean lastAttempt = attempt >= retries;
        okhttp3.Call call = http.newCall(attempt(request, attempt));
        result.whenComplete(
                (response, error) -> {
                    if (result.isCancelled()) {
                        call.cancel();
                    }
                });
        call.enqueue(
                new Callback() {
                    @Override
                    public void onFailure(okhttp3.Call call, IOException e) {
                        if (lastAttempt) {
                            result.completeExceptionally(transportError(e));
                        } else {
                            later(
                                    backoff(attempt),
                                    () -> executeAsync(request, http, retries, attempt + 1, renewed, result));
                        }
                    }

                    @Override
                    public void onResponse(okhttp3.Call call, Response response) {
                        if (!renewed && rejectedToken(request, response)) {
                            response.close();
                            // Fetching a token blocks, so it does not run on the dispatcher's thread.
                            CompletableFuture.runAsync(
                                    () -> {
                                        try {
                                            executeAsync(auth.renew(request), http, retries, attempt, true, result);
                                        } catch (RuntimeException e) {
                                            result.completeExceptionally(e);
                                        }
                                    });
                            return;
                        }
                        Duration delay = lastAttempt ? null : retryDelay(response, attempt);
                        if (delay == null) {
                            if (!result.complete(response)) {
                                response.close();
                            }
                            return;
                        }
                        response.close();
                        later(delay, () -> executeAsync(request, http, retries, attempt + 1, renewed, result));
                    }
                });
    }

    private static void later(Duration delay, Runnable task) {
        CompletableFuture.delayedExecutor(delay.toMillis(), TimeUnit.MILLISECONDS).execute(task);
    }

    /** The delay before retrying after {@code response}, or null to return it. */
    private Duration retryDelay(Response response, int attempt) {
        int status = response.code();
        if (status != 408 && status != 429 && status < 500) {
            return null;
        }
        Duration delay = retryAfter(response);
        if (delay == null || delay.isNegative() || delay.compareTo(MAX_RETRY_AFTER) > 0) {
            return backoff(attempt);
        }
        return delay;
    }

    /** The scheduled delay, the last one past the schedule, with jitter between half and all of it. */
    private Duration backoff(int attempt) {
        long millis =
                retrySchedule.isEmpty()
                        ? DEFAULT_BACKOFF_MILLIS
                        : retrySchedule.get(Math.min(attempt, retrySchedule.size() - 1));
        return Duration.ofMillis(millis / 2 + ThreadLocalRandom.current().nextLong(millis / 2 + 1));
    }

    /** {@code retry-after-ms}, or {@code Retry-After} in seconds or as an HTTP date, if valid. */
    private static Duration retryAfter(Response response) {
        String millis = response.header("retry-after-ms");
        if (millis != null) {
            try {
                return Duration.ofMillis((long) Double.parseDouble(millis.trim()));
            } catch (NumberFormatException ignored) {
                // Fall back to Retry-After.
            }
        }
        String header = response.header("Retry-After");
        if (header == null) {
            return null;
        }
        try {
            return Duration.ofSeconds(Long.parseLong(header.trim()));
        } catch (NumberFormatException e) {
            try {
                ZonedDateTime at = ZonedDateTime.parse(header.trim(), DateTimeFormatter.RFC_1123_DATE_TIME);
                return Duration.between(ZonedDateTime.now(at.getZone()), at);
            } catch (DateTimeParseException ignored) {
                return null;
            }
        }
    }

    private static void sleep(Duration delay) throws InterruptedIOException {
        try {
            Thread.sleep(delay.toMillis());
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new InterruptedIOException("interrupted while waiting to retry");
        }
    }
}
