// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_INTERNAL_PACKAGE@@;

import @@JAVA_PACKAGE@@.exceptions.@@CLIENT_NAME@@Exception;
import java.io.IOException;
import java.math.BigInteger;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.Proxy;
import java.net.ProxySelector;
import java.net.SocketAddress;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URLDecoder;
import java.net.UnknownHostException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import okhttp3.Authenticator;
import okhttp3.Credentials;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.Route;

/**
 * The proxies the environment names, as curl reads them: {@code HTTPS_PROXY}, {@code HTTP_PROXY}
 * or {@code ALL_PROXY} (or their lowercase names) by scheme, unless {@code NO_PROXY} lists the
 * host. An HTTP proxy tunnels HTTPS and takes its URL's credentials; {@code socks5://} works too,
 * without credentials, which the JDK only reads from the process-wide {@link
 * java.net.Authenticator}. OkHttp cannot reach a proxy over TLS, so an {@code https://} proxy is an
 * error. Internal.
 */
public final class EnvProxy extends ProxySelector implements Authenticator {
    private final Endpoint http;
    private final Endpoint https;
    private final List<String> noProxy;

    private EnvProxy(Endpoint http, Endpoint https, List<String> noProxy) {
        this.http = http;
        this.https = https;
        this.noProxy = noProxy;
    }

    /**
     * The proxies of {@code env}, such as {@code System.getenv()}.
     *
     * @param env the environment variables
     * @return the proxies, empty when the environment names none
     * @throws @@CLIENT_NAME@@Exception if a variable names an {@code https://} proxy
     */
    public static Optional<EnvProxy> fromEnv(Map<String, String> env) {
        String all = first(env, "ALL_PROXY", "all_proxy");
        boolean cgi = env.containsKey("REQUEST_METHOD");
        String http = cgi ? first(env, "http_proxy") : first(env, "HTTP_PROXY", "http_proxy");
        String https = first(env, "HTTPS_PROXY", "https_proxy");
        for (String proxy : new String[] {http != null ? http : all, https != null ? https : all}) {
            if (proxy != null && proxy.regionMatches(true, 0, "https://", 0, 8)) {
                throw new @@CLIENT_NAME@@Exception(
                        "the environment names an https:// proxy, which OkHttp cannot connect to over TLS: "
                                + "give its http:// URL, or set the proxy or httpClient option of the client");
            }
        }
        Endpoint httpProxy = Endpoint.parse(http != null ? http : all);
        Endpoint httpsProxy = Endpoint.parse(https != null ? https : all);
        if (httpProxy == null && httpsProxy == null) {
            return Optional.empty();
        }
        List<String> noProxy = new ArrayList<>();
        String bypassed = first(env, "NO_PROXY", "no_proxy");
        for (String entry : (bypassed == null ? "" : bypassed).split(",")) {
            if (!entry.isBlank()) {
                noProxy.add(entry.trim().toLowerCase(Locale.ROOT));
            }
        }
        return Optional.of(new EnvProxy(httpProxy, httpsProxy, noProxy));
    }

    private static String first(Map<String, String> env, String... names) {
        for (String name : names) {
            String value = env.get(name);
            if (value != null && !value.isBlank()) {
                return value.trim();
            }
        }
        return null;
    }

    @Override
    public List<Proxy> select(URI uri) {
        Endpoint endpoint = "https".equalsIgnoreCase(uri.getScheme()) ? https : http;
        if (endpoint == null || uri.getHost() == null || bypasses(uri.getHost())) {
            return List.of(Proxy.NO_PROXY);
        }
        return List.of(endpoint.proxy);
    }

    @Override
    public void connectFailed(URI uri, SocketAddress address, IOException error) {}

    /** Answers the proxy's 407, or OkHttp's preemptive challenge of a tunnel, with Basic credentials. */
    @Override
    public Request authenticate(Route route, Response response) {
        Endpoint endpoint = response.request().url().isHttps() ? https : http;
        if (endpoint == null
                || endpoint.credentials == null
                || endpoint.credentials.equals(response.request().header("Proxy-Authorization"))) {
            return null;
        }
        return response.request().newBuilder().header("Proxy-Authorization", endpoint.credentials).build();
    }

    /**
     * Whether {@code NO_PROXY} lists {@code host}: {@code *}, the host, a domain it is in, or an IP
     * network it is in.
     *
     * @param host the host name or IP address
     * @return whether to connect directly
     */
    public boolean bypasses(String host) {
        String name = host.replaceAll("^\\[|]$", "").toLowerCase(Locale.ROOT).replaceAll("\\.$", "");
        byte[] ip = literal(name);
        for (String entry : noProxy) {
            if (entry.equals("*")) {
                return true;
            }
            if (ip != null) {
                if (inNetwork(entry, ip)) {
                    return true;
                }
                continue;
            }
            String domain = entry.replaceAll("^\\*?\\.?", "");
            if (name.equals(domain) || name.endsWith("." + domain)) {
                return true;
            }
        }
        return false;
    }

    private static boolean inNetwork(String entry, byte[] ip) {
        int slash = entry.indexOf('/');
        byte[] network = literal((slash < 0 ? entry : entry.substring(0, slash)).replaceAll("^\\[|]$", ""));
        if (network == null || network.length != ip.length) {
            return false;
        }
        int width = ip.length * 8;
        int bits;
        try {
            bits = slash < 0 ? width : Integer.parseInt(entry.substring(slash + 1));
        } catch (NumberFormatException e) {
            return false;
        }
        if (bits < 0 || bits > width) {
            return false;
        }
        BigInteger difference = new BigInteger(1, network).xor(new BigInteger(1, ip));
        return difference.shiftRight(width - bits).signum() == 0;
    }

    /** The bytes of an IP address literal, without a DNS lookup; null for a host name. */
    private static byte[] literal(String host) {
        if (!host.matches("\\d{1,3}(\\.\\d{1,3}){3}") && !host.matches("[0-9a-f:.]*:[0-9a-f:.]*")) {
            return null;
        }
        try {
            return InetAddress.getByName(host).getAddress();
        } catch (UnknownHostException e) {
            return null;
        }
    }

    /** A proxy and the {@code Proxy-Authorization} its URL's credentials give. */
    private static final class Endpoint {
        private final Proxy proxy;
        private final String credentials;

        private Endpoint(Proxy proxy, String credentials) {
            this.proxy = proxy;
            this.credentials = credentials;
        }

        private static Endpoint parse(String value) {
            if (value == null) {
                return null;
            }
            URI uri;
            try {
                uri = new URI(value.contains("://") ? value : "http://" + value);
            } catch (URISyntaxException e) {
                return null;
            }
            String scheme = uri.getScheme().toLowerCase(Locale.ROOT);
            boolean socks = scheme.startsWith("socks");
            if (uri.getHost() == null || !(socks || scheme.equals("http"))) {
                return null;
            }
            int port = uri.getPort() >= 0 ? uri.getPort() : socks ? 1080 : 80;
            String host = uri.getHost().replaceAll("^\\[|]$", "");
            Proxy proxy = new Proxy(socks ? Proxy.Type.SOCKS : Proxy.Type.HTTP, InetSocketAddress.createUnresolved(host, port));
            String userInfo = uri.getRawUserInfo();
            String credentials = null;
            if (userInfo != null && !socks) {
                int colon = userInfo.indexOf(':');
                credentials = Credentials.basic(
                        decode(colon < 0 ? userInfo : userInfo.substring(0, colon)),
                        decode(colon < 0 ? "" : userInfo.substring(colon + 1)),
                        StandardCharsets.UTF_8);
            }
            return new Endpoint(proxy, credentials);
        }

        private static String decode(String text) {
            return URLDecoder.decode(text.replace("+", "%2B"), StandardCharsets.UTF_8);
        }
    }
}
