// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_INTERNAL_PACKAGE@@;

import @@JAVA_PACKAGE@@.exceptions.InvalidDataException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.function.ToIntFunction;

/** Picks the variant of an object in a union of several objects, or of variants sharing a tag. */
public final class Unions {
    private Unions() {}

    /**
     * {@code value} converted to a {@code type} through its JSON form.
     *
     * @param <T> the type
     * @param value the value
     * @param type the class
     * @return the converted value
     */
    public static <T> T convert(Object value, Class<T> type) {
        try {
            return Utils.objectMapper().convertValue(value, type);
        } catch (IllegalArgumentException e) {
            throw new InvalidDataException("not a " + type.getSimpleName() + ": " + e.getMessage(), e);
        }
    }

    /**
     * {@code value} converted to a generic {@code type} through its JSON form.
     *
     * @param <T> the type
     * @param value the value
     * @param type the type
     * @return the converted value
     */
    public static <T> T convert(Object value, TypeReference<T> type) {
        try {
            return Utils.objectMapper().convertValue(value, type);
        } catch (IllegalArgumentException e) {
            throw new InvalidDataException("not a " + type.getType().getTypeName() + ": " + e.getMessage(), e);
        }
    }

    /**
     * Whether the JSON object {@code node} has {@code property}, equal to the JSON text {@code
     * expected} unless null.
     *
     * @param node the JSON object
     * @param property the property name
     * @param expected the JSON text of the expected value, or null
     * @return whether it matches
     */
    public static boolean has(JsonNode node, String property, String expected) {
        JsonNode value = node.get(property);
        if (value == null || expected == null) {
            return value != null;
        }
        try {
            return Utils.objectMapper().readTree(expected).equals(value);
        } catch (JsonProcessingException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * Decodes a value as one variant.
     *
     * @param <T> the variant
     */
    @FunctionalInterface
    public interface Decoder<T> {
        /**
         * The decoded value.
         *
         * @return the value
         * @throws IOException if it is not this variant
         */
        T decode() throws IOException;
    }

    /**
     * The value of the candidate that decodes it with the fewest {@code leftovers}, the first one
     * on ties; the first one that decodes when {@code leftovers} rejects them all with {@code
     * Integer.MAX_VALUE}.
     *
     * @param <T> the union
     * @param leftovers the properties a decoded value does not know, or {@code Integer.MAX_VALUE}
     * @param candidates the variants to try, in order of preference
     * @return the decoded value
     * @throws IOException the first failure, when no candidate decodes
     */
    @SafeVarargs
    public static <T> T closest(ToIntFunction<T> leftovers, Decoder<? extends T>... candidates)
            throws IOException {
        T best = null;
        T fallback = null;
        int fewest = Integer.MAX_VALUE;
        Exception failure = null;
        for (Decoder<? extends T> candidate : candidates) {
            T value;
            try {
                value = candidate.decode();
            } catch (IOException | RuntimeException e) {
                failure = failure == null ? e : failure;
                continue;
            }
            fallback = fallback == null ? value : fallback;
            int unknown = leftovers.applyAsInt(value);
            if (unknown < fewest) {
                best = value;
                fewest = unknown;
            }
        }
        if (best != null || fallback != null) {
            return best != null ? best : fallback;
        }
        if (failure instanceof IOException) {
            throw (IOException) failure;
        }
        throw (RuntimeException) failure;
    }

    /**
     * The index of the candidate, as its required then known properties, whose required
     * properties the JSON object {@code node} all has and which knows the most of its
     * properties, the first one on ties; -1 when none fits.
     *
     * @param node the JSON object
     * @param candidates per variant, its required then known properties
     * @return the index of the variant, or -1
     */
    public static int bestMatch(JsonNode node, String[][]... candidates) {
        int best = -1;
        int top = -1;
        for (int i = 0; i < candidates.length; i++) {
            boolean fits = true;
            for (String property : candidates[i][0]) {
                fits &= node.has(property);
            }
            if (!fits) {
                continue;
            }
            int score = 0;
            for (String property : candidates[i][1]) {
                score += node.has(property) ? 1 : 0;
            }
            if (score > top) {
                best = i;
                top = score;
            }
        }
        return best;
    }

    /**
     * The indexes of the candidates, as their required then known properties, whose required
     * properties the JSON object {@code node} all has, best match first: the one knowing the most
     * of its properties, the first one on ties. Decoding tries them in this order.
     *
     * @param node the JSON object
     * @param candidates per variant, its required then known properties
     * @return the indexes of the variants that fit, best first
     */
    public static int[] rank(JsonNode node, String[][]... candidates) {
        int[] order = new int[candidates.length];
        int[] scores = new int[candidates.length];
        int count = 0;
        for (int i = 0; i < candidates.length; i++) {
            boolean fits = true;
            for (String property : candidates[i][0]) {
                fits &= node.has(property);
            }
            if (!fits) {
                continue;
            }
            int score = 0;
            for (String property : candidates[i][1]) {
                score += node.has(property) ? 1 : 0;
            }
            int at = count++;
            while (at > 0 && scores[at - 1] < score) {
                order[at] = order[at - 1];
                scores[at] = scores[at - 1];
                at--;
            }
            order[at] = i;
            scores[at] = score;
        }
        return java.util.Arrays.copyOf(order, count);
    }
}
