// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_INTERNAL_PACKAGE@@;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import @@JAVA_PACKAGE@@.exceptions.@@CLIENT_NAME@@Exception;
import @@JAVA_PACKAGE@@.exceptions.InvalidDataException;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import okhttp3.HttpUrl;

/** JSON and parameter encoding shared by the generated code. Internal. */
public final class Utils {
    private static final ObjectMapper MAPPER = newObjectMapper();

    private Utils() {}

    /**
     * A {@code name=value} cookie pair, its value percent-encoded to stay RFC 6265 safe.
     *
     * @param name the cookie name
     * @param value the cookie value
     * @return the pair
     */
    public static String cookiePair(String name, String value) {
        String encoded =
                java.net.URLEncoder.encode(value, java.nio.charset.StandardCharsets.UTF_8)
                        .replace("+", "%20")
                        .replace("*", "%2A")
                        .replace("%7E", "~");
        return name + "=" + encoded;
    }

    /**
     * The value of a required property, which a response may still leave out.
     *
     * @param <T> the property type
     * @param value the value, null when left out
     * @param name the JSON name of the property
     * @return the value
     * @throws InvalidDataException when it was left out
     */
    public static <T> T required(T value, String name) {
        if (value == null) {
            throw new InvalidDataException("`" + name + "` is required, but the response left it out");
        }
        return value;
    }

    /**
     * Checks a builder set a required property.
     *
     * @param value the value
     * @param name the JSON name of the property
     * @throws IllegalStateException when it is not set
     */
    public static void checkRequired(Object value, String name) {
        if (value == null) {
            throw new IllegalStateException("`" + name + "` is required, but was not set");
        }
    }

    /**
     * An optional value as an {@link Optional}, null meaning empty.
     *
     * @param <T> the value type
     * @param value the value
     * @return the value, or empty
     */
    public static <T> Optional<T> optional(Optional<T> value) {
        return value == null ? Optional.empty() : value;
    }

    /**
     * A value as an {@link Optional}, null meaning empty.
     *
     * @param <T> the value type
     * @param value the value
     * @return the value, or empty
     */
    public static <T> Optional<T> optional(T value) {
        return Optional.ofNullable(value);
    }

    /**
     * A copy a builder can add to.
     *
     * @param <T> the item type
     * @param items the items, or null
     * @return a new list, or null
     */
    public static <T> List<T> mutableList(Collection<? extends T> items) {
        return items == null ? null : new ArrayList<>(items);
    }

    /**
     * A copy a builder can add to.
     *
     * @param <T> the item type
     * @param items the items, or null
     * @return a new set, or null
     */
    public static <T> Set<T> mutableSet(Collection<? extends T> items) {
        return items == null ? null : new LinkedHashSet<>(items);
    }

    /**
     * A copy a builder can add to.
     *
     * @param <V> the value type
     * @param entries the entries, or null
     * @return a new map, or null
     */
    public static <V> Map<String, V> mutableMap(Map<String, ? extends V> entries) {
        return entries == null ? null : new LinkedHashMap<>(entries);
    }

    /**
     * An unmodifiable copy, for a built model.
     *
     * @param <T> the item type
     * @param items the items, or null
     * @return the copy, or null
     */
    public static <T> List<T> copyList(Collection<? extends T> items) {
        return items == null ? null : Collections.unmodifiableList(new ArrayList<>(items));
    }

    /**
     * An unmodifiable copy, for a built model.
     *
     * @param <T> the item type
     * @param items the items, or null
     * @return the copy, or null
     */
    public static <T> Set<T> copySet(Collection<? extends T> items) {
        return items == null ? null : Collections.unmodifiableSet(new LinkedHashSet<>(items));
    }

    /**
     * An unmodifiable copy, for a built model.
     *
     * @param <V> the value type
     * @param entries the entries, or null
     * @return the copy, or null
     */
    public static <V> Map<String, V> copyMap(Map<String, ? extends V> entries) {
        return entries == null ? null : Collections.unmodifiableMap(new LinkedHashMap<>(entries));
    }

    /**
     * The JSON properties of a model, for the model extending it.
     *
     * @param value the model, or null
     * @return its properties by name, empty for null
     */
    public static Map<String, JsonNode> properties(Object value) {
        Map<String, JsonNode> properties = new LinkedHashMap<>();
        if (value != null) {
            MAPPER.valueToTree(value).fields().forEachRemaining(e -> properties.put(e.getKey(), e.getValue()));
        }
        return properties;
    }

    /**
     * A query parameter value as sent, before URL encoding.
     *
     * @param v the value
     * @return the text
     */
    public static String serializeQueryParam(Object v) {
        if (v instanceof ToQueryParam) {
            return ((ToQueryParam) v).toQueryParam();
        } else if (v instanceof OffsetDateTime) {
            return ((OffsetDateTime) v).format(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        } else if (v instanceof BigDecimal) {
            return ((BigDecimal) v).toPlainString();
        } else if (v instanceof Collection) {
            Stream<String> items = ((Collection<?>) v).stream().map(Utils::serializeQueryParam);
            // A set has no order of its own: sort it so that URLs are stable.
            if (v instanceof Set) {
                items = items.sorted();
            }
            return items.collect(Collectors.joining(","));
        } else {
            return String.valueOf(v);
        }
    }

    /**
     * Append a collection as repeated query parameters, one entry per item (OpenAPI {@code
     * explode=true} behavior, e.g. {@code ?tag=a&tag=b}).
     *
     * @param url the URL builder
     * @param name the parameter name
     * @param values the items
     */
    public static void addExplodedQueryParameter(HttpUrl.Builder url, String name, Iterable<?> values) {
        for (Object item : values) {
            url.addQueryParameter(name, serializeQueryParam(item));
        }
    }

    /**
     * Append the JSON value of {@code value}: objects as {@code name[key]=value}, lists as
     * repeated {@code name=item} ({@code name[]=item} with {@code deepObject}, {@code name=a,b}
     * without {@code explode}).
     *
     * @param url the URL builder
     * @param name the parameter name
     * @param value the value
     * @param deepObject whether lists are sent as {@code name[]=item}
     * @param explode whether lists of scalars repeat {@code name}
     */
    public static void addStructuredQueryParameter(
            HttpUrl.Builder url, String name, Object value, boolean deepObject, boolean explode) {
        List<Map.Entry<String, String>> pairs = new ArrayList<>();
        encodeParam(name, MAPPER.valueToTree(value), deepObject, explode, pairs);
        pairs.forEach(pair -> url.addQueryParameter(pair.getKey(), pair.getValue()));
    }

    /**
     * Append the items of a list joined by {@code delimiter} ({@code pipeDelimited}, {@code
     * spaceDelimited}).
     *
     * @param url the URL builder
     * @param name the parameter name
     * @param value the list
     * @param delimiter the text between items
     */
    public static void addDelimitedQueryParameter(
            HttpUrl.Builder url, String name, Object value, String delimiter) {
        List<String> texts = new ArrayList<>();
        for (JsonNode item : MAPPER.valueToTree(value)) {
            if (!item.isNull()) {
                texts.add(item.asText());
            }
        }
        if (!texts.isEmpty()) {
            url.addQueryParameter(name, String.join(delimiter, texts));
        }
    }

    /**
     * Append a {@code content: application/json} parameter as compact JSON text.
     *
     * @param url the URL builder
     * @param name the parameter name
     * @param value the value
     */
    public static void addJsonQueryParameter(HttpUrl.Builder url, String name, Object value) {
        url.addQueryParameter(name, json(value));
    }

    /**
     * One JSON value as query or form pairs, nested values the way Stripe-style APIs read them:
     * {@code name[key]=value}, {@code name[]=item} for lists of scalars and {@code
     * name[0][key]=value} for lists of objects. Top-level lists of scalars repeat {@code name}
     * unless {@code deepObject} or not {@code explode}.
     *
     * @param name the parameter name
     * @param value the JSON value
     * @param deepObject whether lists are sent as {@code name[]=item}
     * @param explode whether lists of scalars repeat {@code name}
     * @param out receives the pairs
     */
    public static void encodeParam(
            String name,
            JsonNode value,
            boolean deepObject,
            boolean explode,
            List<Map.Entry<String, String>> out) {
        boolean nested = false;
        for (JsonNode item : value) {
            nested |= item.isContainerNode();
        }
        if (value.isArray() && !deepObject && !nested) {
            List<String> texts = new ArrayList<>();
            for (JsonNode item : value) {
                if (!item.isNull()) {
                    texts.add(item.asText());
                }
            }
            if (explode) {
                texts.forEach(text -> out.add(new AbstractMap.SimpleEntry<>(name, text)));
            } else if (!texts.isEmpty()) {
                out.add(new AbstractMap.SimpleEntry<>(name, String.join(",", texts)));
            }
            return;
        }
        flattenParam(name, value, out);
    }

    private static void flattenParam(
            String prefix, JsonNode value, List<Map.Entry<String, String>> out) {
        if (value.isObject()) {
            Iterator<Map.Entry<String, JsonNode>> fields = value.fields();
            while (fields.hasNext()) {
                Map.Entry<String, JsonNode> field = fields.next();
                flattenParam(prefix + "[" + field.getKey() + "]", field.getValue(), out);
            }
        } else if (value.isArray()) {
            for (int index = 0; index < value.size(); index++) {
                JsonNode item = value.get(index);
                flattenParam(prefix + (item.isContainerNode() ? "[" + index + "]" : "[]"), item, out);
            }
        } else if (!value.isNull() && !value.isMissingNode()) {
            out.add(new AbstractMap.SimpleEntry<>(prefix, value.asText()));
        }
    }

    /**
     * {@code value} as one path segment, which the URL builder percent-encodes. Dot segments and
     * empty values are rejected: they would change the path of the request.
     *
     * @param name the parameter name
     * @param value the value
     * @return the segment
     */
    public static String pathSegment(String name, Object value) {
        String segment = value == null ? "" : serializeQueryParam(value);
        if (segment.isEmpty() || segment.equals(".") || segment.equals("..")) {
            throw new IllegalArgumentException(
                    "invalid path parameter `" + name + "`: \"" + segment + "\"");
        }
        return segment;
    }

    /** Percent-encodes everything but the unreserved characters. */
    private static String escapeUnreserved(String text) {
        return java.net.URLEncoder.encode(text, java.nio.charset.StandardCharsets.UTF_8)
                .replace("+", "%20")
                .replace("*", "%2A")
                .replace("%7E", "~");
    }

    private static String pathText(JsonNode node) {
        if (node == null || node.isNull() || node.isMissingNode()) {
            return "";
        }
        return node.isContainerNode() ? node.toString() : node.asText();
    }

    /**
     * A plain path parameter inside a segment that also holds styled ones, percent-encoded, for
     * {@code addEncodedPathSegment}.
     *
     * @param name the parameter name
     * @param value the value
     * @return the encoded text
     */
    public static String encodePathValue(String name, Object value) {
        String segment = value == null ? "" : serializeQueryParam(value);
        if (segment.isEmpty()) {
            throw new IllegalArgumentException("invalid path parameter `" + name + "`: \"\"");
        }
        return escapeUnreserved(segment);
    }

    /**
     * A path segment built from encoded parts: dot segments would change the request path.
     *
     * @param name the parameter name
     * @param segment the encoded segment
     * @return the segment
     */
    public static String encodedPathSegment(String name, String segment) {
        if (segment.isEmpty() || segment.equals(".") || segment.equals("..")) {
            throw new IllegalArgumentException(
                    "invalid path parameter `" + name + "`: \"" + segment + "\"");
        }
        return segment;
    }

    /**
     * A path parameter in its OpenAPI {@code style} ({@code simple}, {@code label}, {@code
     * matrix}; {@code json} for {@code content} values), each part percent-encoded.
     *
     * @param name the parameter name
     * @param value the value
     * @param style the style
     * @param explode whether lists and objects are exploded
     * @return the encoded text
     */
    public static String encodePathParam(String name, Object value, String style, boolean explode) {
        JsonNode node = MAPPER.valueToTree(value);
        if (style.equals("json")) {
            return escapeUnreserved(node == null ? "" : node.toString());
        }
        String head = style.equals("label") ? "." : style.equals("matrix") ? ";" : "";
        String separator = style.equals("label") ? "." : style.equals("matrix") ? ";" : ",";
        String key = escapeUnreserved(name);
        if (node != null && node.isArray()) {
            List<String> values = new ArrayList<>();
            for (JsonNode item : node) {
                values.add(escapeUnreserved(pathText(item)));
            }
            if (style.equals("matrix")) {
                if (!explode) {
                    return ";" + key + "=" + String.join(",", values);
                }
                StringBuilder out = new StringBuilder();
                values.forEach(item -> out.append(';').append(key).append('=').append(item));
                return out.toString();
            }
            return head + String.join(explode ? separator : ",", values);
        }
        if (node != null && node.isObject()) {
            List<String> pairs = new ArrayList<>();
            List<String> flat = new ArrayList<>();
            Iterator<Map.Entry<String, JsonNode>> fields = node.fields();
            while (fields.hasNext()) {
                Map.Entry<String, JsonNode> field = fields.next();
                String fieldName = escapeUnreserved(field.getKey());
                String text = escapeUnreserved(pathText(field.getValue()));
                pairs.add(fieldName + "=" + text);
                flat.add(fieldName);
                flat.add(text);
            }
            if (style.equals("matrix")) {
                return explode ? ";" + String.join(";", pairs) : ";" + key + "=" + String.join(",", flat);
            }
            return head + (explode ? String.join(separator, pairs) : String.join(",", flat));
        }
        String text = escapeUnreserved(pathText(node));
        if (style.equals("label")) {
            return "." + text;
        }
        if (style.equals("matrix")) {
            return text.isEmpty() ? ";" + key : ";" + key + "=" + text;
        }
        return text;
    }

    /** A value with its own query string form. */
    public interface ToQueryParam {
        /**
         * The value as sent in a query string, before URL encoding.
         *
         * @return the text
         */
        String toQueryParam();
    }

    /**
     * {@code value} as JSON; a value the mapper cannot write is a bug, thrown unchecked.
     *
     * @param value the value
     * @return the JSON text
     */
    public static String json(Object value) {
        try {
            return MAPPER.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            throw new @@CLIENT_NAME@@Exception("cannot serialize " + value.getClass().getSimpleName(), e);
        }
    }

    /**
     * Parse {@code json} into a {@code type}.
     *
     * @param <T> the type
     * @param json the JSON text
     * @param type the class
     * @return the value
     * @throws InvalidDataException if it is not valid JSON of this shape
     */
    public static <T> T parse(String json, Class<T> type) {
        try {
            return MAPPER.readValue(json, type);
        } catch (JsonProcessingException e) {
            throw new InvalidDataException(
                    "not a JSON " + type.getSimpleName() + ": " + e.getOriginalMessage(), e);
        }
    }

    /** The mapper the SDK uses, shared: configure a {@link #getObjectMapper()} copy instead. */
    static ObjectMapper objectMapper() {
        return MAPPER;
    }

    /**
     * A new mapper configured like the SDK's: ISO-8601 dates keeping their offset, decimals as
     * strings, unknown properties ignored.
     *
     * @return a new mapper
     */
    public static ObjectMapper getObjectMapper() {
        return MAPPER.copy();
    }

    private static ObjectMapper newObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        mapper.disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);
        mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        mapper.enable(JsonParser.Feature.INCLUDE_SOURCE_IN_LOCATION);
        mapper.registerModule(new JavaTimeModule());
        mapper.registerModule(new Jdk8Module());
        mapper.registerModule(
                new SimpleModule()
                        .addSerializer(new DecimalSerializer())
                        // A set keeps the order of its JSON array, as the builders' sets do.
                        .addAbstractTypeMapping(Set.class, LinkedHashSet.class));
        return mapper;
    }

    /**
     * Reads a union of values told apart by their JSON type, such as {@code string | Customer}.
     *
     * @param <T> the union class
     */
    public abstract static class UnionDeserializer<T> extends StdDeserializer<T> {
        private static final long serialVersionUID = 1L;

        /**
         * A deserializer of {@code type}.
         *
         * @param type the union class
         */
        protected UnionDeserializer(Class<T> type) {
            super(type);
        }

        /**
         * The variant holding {@code node}, or null when none takes its JSON type.
         *
         * @param node the JSON value
         * @param ctxt the context
         * @return the variant, or null
         * @throws IOException if a variant fails to decode
         */
        protected abstract T decode(JsonNode node, DeserializationContext ctxt) throws IOException;

        /**
         * {@code node} decoded as {@code type}.
         *
         * @param <V> the type
         * @param node the JSON value
         * @param ctxt the context
         * @param type the type
         * @return the value
         * @throws IOException if it fails to decode
         */
        protected static <V> V read(JsonNode node, DeserializationContext ctxt, TypeReference<V> type)
                throws IOException {
            return ctxt.readTreeAsValue(node, ctxt.getTypeFactory().constructType(type));
        }

        @Override
        public T deserialize(JsonParser parser, DeserializationContext ctxt) throws IOException {
            JsonNode node = ctxt.readTree(parser);
            T value = decode(node, ctxt);
            if (value == null) {
                return ctxt.reportInputMismatch(
                        this,
                        "no variant of %s is a JSON %s",
                        handledType().getSimpleName(),
                        node.getNodeType());
            }
            return value;
        }
    }

    /** Decimals travel as strings, so that no JSON parser rounds them through a double. */
    private static final class DecimalSerializer extends StdSerializer<BigDecimal> {
        private static final long serialVersionUID = 1L;

        DecimalSerializer() {
            super(BigDecimal.class);
        }

        @Override
        public void serialize(BigDecimal value, JsonGenerator gen, SerializerProvider provider)
                throws IOException {
            gen.writeString(value.toPlainString());
        }
    }
}
