// this file is @generated by Perseid; edit the shared runtime template.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;

namespace @@PACKAGE_NAME@@;

/// <summary>A 400 Bad Request response.</summary>
public class BadRequestException(HttpStatusCode statusCode, string body, HttpResponseHeaders headers)
    : ApiException(statusCode, body, headers);

/// <summary>A 401 Unauthorized response: missing or invalid credentials.</summary>
public class UnauthorizedException(HttpStatusCode statusCode, string body, HttpResponseHeaders headers)
    : ApiException(statusCode, body, headers);

/// <summary>A 403 Forbidden response: the credentials lack a permission.</summary>
public class ForbiddenException(HttpStatusCode statusCode, string body, HttpResponseHeaders headers)
    : ApiException(statusCode, body, headers);

/// <summary>A 404 Not Found response.</summary>
public class NotFoundException(HttpStatusCode statusCode, string body, HttpResponseHeaders headers)
    : ApiException(statusCode, body, headers);

/// <summary>A 409 Conflict response.</summary>
public class ConflictException(HttpStatusCode statusCode, string body, HttpResponseHeaders headers)
    : ApiException(statusCode, body, headers);

/// <summary>A 422 Unprocessable Entity response: the request failed validation.</summary>
public class UnprocessableEntityException(
    HttpStatusCode statusCode,
    string body,
    HttpResponseHeaders headers
) : ApiException(statusCode, body, headers);

/// <summary>A 429 Too Many Requests response, once retries are exhausted.</summary>
public class RateLimitException(HttpStatusCode statusCode, string body, HttpResponseHeaders headers)
    : ApiException(statusCode, body, headers);

/// <summary>A 5xx response, once retries are exhausted.</summary>
public class ServerErrorException(HttpStatusCode statusCode, string body, HttpResponseHeaders headers)
    : ApiException(statusCode, body, headers);

/// <summary>Typed access to the body of an <see cref="ApiException"/>.</summary>
public static partial class ApiExceptionExtensions
{
    /// <summary>
    /// The body parsed as the model <typeparamref name="T"/>, or <c>default</c> when it is not one.
    /// </summary>
    public static T? GetError<T>(this ApiException exception)
    {
        ArgumentNullException.ThrowIfNull(exception);
        try
        {
            var typeInfo = Json.TypeInfo<T>(Models.@@CLIENT_NAME@@JsonContext.Default.Options);
            return JsonSerializer.Deserialize(exception.Body, typeInfo);
        }
        catch (JsonException)
        {
            return default;
        }
    }

    private const int MaxBodyInMessage = 500;

    /// <summary>The message of an error response, as <c>HTTP 429 (rate_limit_exceeded): Slow down</c>:
    /// the code or type and message of the body's <c>error</c>, else its <c>message</c> or
    /// <c>detail</c>, else the body itself, shortened.</summary>
    internal static string Describe(HttpStatusCode statusCode, string body)
    {
        ArgumentNullException.ThrowIfNull(body);
        var (code, message) = Summarize(body);
        var head = code is null
            ? $"HTTP {(int)statusCode}"
            : $"HTTP {(int)statusCode} ({code})";
        message ??= body.Length > MaxBodyInMessage ? $"{body[..MaxBodyInMessage]}…" : body;
        return message.Length == 0 ? head : $"{head}: {message}";
    }

    private static (string? Code, string? Message) Summarize(string body)
    {
        try
        {
            using var document = JsonDocument.Parse(body);
            var root = document.RootElement;
            if (root.ValueKind != JsonValueKind.Object)
            {
                return (null, null);
            }
            if (root.TryGetProperty("error", out var error) && error.ValueKind == JsonValueKind.Object)
            {
                return (
                    Text(error, "code") ?? Text(error, "type"),
                    Text(error, "message") ?? Text(root, "message")
                );
            }
            return (Text(root, "code"), Text(root, "error") ?? Text(root, "message") ?? Text(root, "detail"));
        }
        catch (JsonException)
        {
            return (null, null);
        }
    }

    private static string? Text(JsonElement element, string name) =>
        element.TryGetProperty(name, out var value)
            ? value.ValueKind switch
            {
                JsonValueKind.String when value.GetString() is { Length: > 0 } text => text,
                JsonValueKind.Number => value.GetRawText(),
                _ => null,
            }
            : null;

    internal static string? RequestId(HttpHeaders headers)
    {
        foreach (var name in (string[])["x-request-id", "request-id"])
        {
            if (headers.TryGetValues(name, out var values))
            {
                return values.FirstOrDefault();
            }
        }
        return null;
    }

    /// <summary>The body parsed as <paramref name="typeInfo"/>, else as a <see cref="JsonElement"/>;
    /// <c>null</c> when it is not JSON.</summary>
    internal static object? DecodeError(string body, JsonTypeInfo? typeInfo)
    {
        if (typeInfo is not null)
        {
            try
            {
                return JsonSerializer.Deserialize(body, typeInfo);
            }
            catch (JsonException) { }
        }
        try
        {
            using var document = JsonDocument.Parse(body);
            return document.RootElement.Clone();
        }
        catch (JsonException)
        {
            return null;
        }
    }

    /// <summary>The exception of an error response: the <see cref="ApiException.FromResponse"/> hook,
    /// else the subclass of its status, knowing the schema its body follows.</summary>
    internal static ApiException ForResponse(
        HttpStatusCode statusCode,
        string body,
        HttpResponseHeaders headers,
        IReadOnlyList<KeyValuePair<string, JsonTypeInfo>>? errorTypes
    )
    {
        var error = ApiException.FromResponse(statusCode, body, headers);
        if (error.GetType() == typeof(ApiException))
        {
            error = ForStatus(statusCode, body, headers);
        }
        error.ErrorType = ErrorType((int)statusCode, errorTypes);
        return error;
    }

    private static JsonTypeInfo? ErrorType(
        int status,
        IReadOnlyList<KeyValuePair<string, JsonTypeInfo>>? errorTypes
    )
    {
        var exact = status.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var range = $"{exact[0]}XX";
        foreach (var key in (string[])[exact, range, "default"])
        {
            foreach (var (declared, typeInfo) in errorTypes ?? [])
            {
                if (string.Equals(declared, key, StringComparison.OrdinalIgnoreCase))
                {
                    return typeInfo;
                }
            }
        }
        return null;
    }

    /// <summary>The <see cref="ApiException"/> subclass of a status code.</summary>
    internal static ApiException ForStatus(
        HttpStatusCode statusCode,
        string body,
        HttpResponseHeaders headers
    ) =>
        (int)statusCode switch
        {
            400 => new BadRequestException(statusCode, body, headers),
            401 => new UnauthorizedException(statusCode, body, headers),
            403 => new ForbiddenException(statusCode, body, headers),
            404 => new NotFoundException(statusCode, body, headers),
            409 => new ConflictException(statusCode, body, headers),
            422 => new UnprocessableEntityException(statusCode, body, headers),
            429 => new RateLimitException(statusCode, body, headers),
            >= 500 and < 600 => new ServerErrorException(statusCode, body, headers),
            _ => new ApiException(statusCode, body, headers),
        };
}
