// this file is @generated by Perseid; edit the shared runtime template.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization.Metadata;

namespace @@PACKAGE_NAME@@;

/// <summary>One API call, built by the generated resources and sent by <see cref="ApiTransport"/>.</summary>
internal sealed class ApiRequest(HttpMethod method, string path, string operation)
{
    private readonly List<KeyValuePair<string, string>> _query = [];
    private byte[]? _json;
    private List<KeyValuePair<string, string>>? _form;
    private Upload? _upload;
    private string _uploadType = "application/octet-stream";
    private MultipartBody? _multipart;

    public HttpMethod Method { get; } = method;

    public string Path { get; } = path;

    /// <summary>The operation, <c>resource.method</c>, naming the trace activity of the call.</summary>
    public string Operation { get; } = operation;

    /// <summary>The error schemas the operation declares, by status: <c>404</c>, <c>4XX</c> or <c>default</c>.</summary>
    public IReadOnlyList<KeyValuePair<string, JsonTypeInfo>>? ErrorTypes { get; set; }

    public Dictionary<string, string> Headers { get; } = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>The operation's security requirement, when it differs from the API-wide one.</summary>
    public string[][]? Security { get; set; }

    /// <summary>Whether the body can only be sent once, which rules out retries.</summary>
    public bool IsOneShot => _upload?.IsStream == true || _multipart?.IsOneShot == true;

    /// <summary>Adds a query parameter unless <paramref name="value"/> is null. Lists repeat the
    /// parameter (OpenAPI <c>explode: true</c>) or are comma-joined.</summary>
    public void AddQuery(string name, object? value, bool explode = true)
    {
        switch (value)
        {
            case null:
                return;
            case string text:
                _query.Add(new(name, text));
                return;
            case IEnumerable items:
                var values = new List<string>();
                foreach (var item in items)
                {
                    if (item is not null)
                    {
                        values.Add(Format(item));
                    }
                }
                if (explode)
                {
                    values.ForEach(v => _query.Add(new(name, v)));
                }
                else if (values.Count > 0)
                {
                    _query.Add(new(name, string.Join(",", values)));
                }
                return;
            default:
                _query.Add(new(name, Format(value)));
                return;
        }
    }

    /// <summary>Adds the JSON form of <paramref name="value"/> unless it is null: objects as
    /// <c>name[key]=value</c>, lists as repeated <c>name=item</c> (<c>name[]=item</c> with
    /// <paramref name="deepObject"/>, comma-joined without <paramref name="explode"/>).</summary>
    public void AddStructuredQuery<T>(
        string name,
        T? value,
        JsonTypeInfo<T> typeInfo,
        bool deepObject,
        bool explode
    )
    {
        if (value is not null)
        {
            EncodeParam(name, JsonSerializer.SerializeToNode(value, typeInfo), deepObject, explode, _query);
        }
    }

    public void AddStructuredQuery(string name, JsonNode? value, bool deepObject, bool explode) =>
        EncodeParam(name, value, deepObject, explode, _query);

    /// <summary>Adds the items of a list joined by <paramref name="delimiter"/>
    /// (<c>pipeDelimited</c>, <c>spaceDelimited</c>).</summary>
    public void AddDelimitedQuery<T>(
        string name,
        object? value,
        JsonTypeInfo<T> typeInfo,
        string delimiter
    )
    {
        if (value is not null)
        {
            AddDelimitedQuery(name, JsonSerializer.SerializeToNode((T)value, typeInfo), delimiter);
        }
    }

    public void AddDelimitedQuery(string name, JsonNode? value, string delimiter)
    {
        if (value is JsonArray items)
        {
            var texts = items.OfType<JsonNode>().Select(ScalarText).ToList();
            if (texts.Count > 0)
            {
                _query.Add(new(name, string.Join(delimiter, texts)));
            }
        }
    }

    /// <summary>Adds a <c>content: application/json</c> parameter as compact JSON text.</summary>
    public void AddJsonQuery<T>(string name, object? value, JsonTypeInfo<T> typeInfo)
    {
        if (value is not null)
        {
            _query.Add(new(name, JsonSerializer.Serialize((T)value, typeInfo)));
        }
    }

    public void AddJsonQuery(string name, JsonNode? value)
    {
        if (value is not null)
        {
            _query.Add(new(name, value.ToJsonString()));
        }
    }

    /// <summary>A path parameter in its OpenAPI <paramref name="style"/> (<c>simple</c>,
    /// <c>label</c>, <c>matrix</c>; <c>json</c> for <c>content</c> values), percent-encoded.</summary>
    public static string EncodePathParam<T>(
        string name,
        object value,
        JsonTypeInfo<T> typeInfo,
        string style,
        bool explode
    ) => EncodePathParam(name, JsonSerializer.SerializeToNode((T)value, typeInfo), style, explode);

    public static string EncodePathParam(string name, string value, string style, bool explode) =>
        EncodePathParam(name, JsonValue.Create(value), style, explode);

    public static string EncodePathParam(string name, JsonNode? value, string style, bool explode)
    {
        if (style == "json")
        {
            return Uri.EscapeDataString(value?.ToJsonString() ?? "");
        }
        string Encode(JsonNode? node) =>
            Uri.EscapeDataString(
                node is null ? "" : IsNested(node) ? node.ToJsonString() : ScalarText(node)
            );
        var head = style switch { "label" => ".", "matrix" => ";", _ => "" };
        var separator = style switch { "label" => ".", "matrix" => ";", _ => "," };
        var key = Uri.EscapeDataString(name);
        switch (value)
        {
            case JsonArray items:
                var values = items.Select(Encode).ToList();
                if (style == "matrix")
                {
                    return explode
                        ? string.Concat(values.Select(item => $";{key}={item}"))
                        : $";{key}=" + string.Join(",", values);
                }
                return head + string.Join(explode ? separator : ",", values);
            case JsonObject fields:
                var pairs = fields
                    .Select(field => (Key: Uri.EscapeDataString(field.Key), Value: Encode(field.Value)))
                    .ToList();
                var flat = string.Join(",", pairs.SelectMany(pair => new[] { pair.Key, pair.Value }));
                if (style == "matrix")
                {
                    return explode
                        ? string.Concat(pairs.Select(pair => $";{pair.Key}={pair.Value}"))
                        : $";{key}={flat}";
                }
                return head
                    + (explode ? string.Join(separator, pairs.Select(pair => $"{pair.Key}={pair.Value}")) : flat);
            default:
                var text = Encode(value);
                return style switch
                {
                    "label" => "." + text,
                    "matrix" => text.Length == 0 ? $";{key}" : $";{key}={text}",
                    _ => text,
                };
        }
    }

    /// <summary>The cookie parameters, merged into one <c>Cookie</c> header when sending.</summary>
    public List<string> Cookies { get; } = new();

    public void SetCookie(string name, object? value)
    {
        if (value is not null)
        {
            Cookies.Add($"{name}={Uri.EscapeDataString(HeaderText(value))}");
        }
    }

    /// <summary>Sets a <c>content: application/json</c> header as compact JSON text.</summary>
    public void SetJsonHeader<T>(string name, object? value, JsonTypeInfo<T> typeInfo)
    {
        if (value is not null)
        {
            Headers[name] = JsonSerializer.Serialize((T)value, typeInfo);
        }
    }

    public void SetJsonHeader(string name, JsonNode? value)
    {
        if (value is not null)
        {
            Headers[name] = value.ToJsonString();
        }
    }

    public void SetHeader(string name, object? value)
    {
        if (value is not null)
        {
            Headers[name] = HeaderText(value);
        }
    }

    /// <summary>A header or cookie value as text: a list comma-separated.</summary>
    private static string HeaderText(object value) =>
        value switch
        {
            string text => text,
            IEnumerable items => string.Join(",", items.Cast<object?>().Where(i => i is not null).Select(i => Format(i!))),
            _ => Format(value),
        };

    public void SetJsonBody<T>(T body, JsonTypeInfo<T> typeInfo) =>
        _json = JsonSerializer.SerializeToUtf8Bytes(body, typeInfo);

    public void SetJsonBody(JsonObject body) => _json = Encoding.UTF8.GetBytes(body.ToJsonString());

    /// <summary>Sets an <c>application/x-www-form-urlencoded</c> body from the JSON form of
    /// <paramref name="body"/>, so wire names come from the model's attributes. Lists of the
    /// <paramref name="deepObject"/> properties are sent as <c>name[]=item</c>, those of the
    /// <paramref name="unexploded"/> ones comma-joined.</summary>
    public void SetFormBody<T>(
        T body,
        JsonTypeInfo<T> typeInfo,
        string[]? deepObject = null,
        string[]? unexploded = null
    )
    {
        if (JsonSerializer.SerializeToNode(body, typeInfo) is not JsonObject fields)
        {
            throw new ArgumentException("form bodies must serialize to JSON objects", nameof(body));
        }
        _form = [];
        foreach (var (name, value) in fields)
        {
            var deep = deepObject is not null && Array.IndexOf(deepObject, name) >= 0;
            var explode = unexploded is null || Array.IndexOf(unexploded, name) < 0;
            EncodeParam(name, value, deep, explode, _form);
        }
    }

    /// <summary>Sets an <c>application/x-www-form-urlencoded</c> body from ready name and value pairs.</summary>
    public void SetFormFields(IEnumerable<KeyValuePair<string, string>> fields) => _form = [.. fields];

    /// <summary>Sets a raw body of the operation's media type, unless the upload names its type.</summary>
    public void SetUploadBody(Upload body, string contentType = "application/octet-stream")
    {
        _upload = body;
        _uploadType = contentType;
    }

    public void SetMultipartBody(MultipartBody body) => _multipart = body;

    public Uri BuildUri(string baseUrl, IEnumerable<KeyValuePair<string, string>> extraQuery)
    {
        // `Uri` resolves dot segments away, which would leave the path of the operation.
        foreach (var segment in Path.Split('?')[0].Split('/'))
        {
            if (segment is "." or "..")
            {
                throw new @@CLIENT_NAME@@Exception(
                    $"the request path {Path} holds the dot segment `{segment}`, which cannot be sent as is"
                );
            }
        }
        // The token endpoint of an OAuth2 scheme may live elsewhere.
        var url = new StringBuilder(Path.Contains("://") ? "" : baseUrl.TrimEnd('/')).Append(Path);
        var first = !Path.Contains('?');
        foreach (var (name, value) in _query.Concat(extraQuery))
        {
            url.Append(first ? '?' : '&')
                .Append(Uri.EscapeDataString(name))
                .Append('=')
                .Append(Uri.EscapeDataString(value));
            first = false;
        }
        return new Uri(url.ToString());
    }

    /// <summary>A fresh body for each attempt: <see cref="HttpContent"/> cannot be sent twice.</summary>
    public HttpContent? CreateContent()
    {
        if (_json is not null)
        {
            var content = new ByteArrayContent(_json);
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json")
            {
                CharSet = "utf-8",
            };
            return content;
        }
        if (_form is not null)
        {
            return new FormUrlEncodedContent(_form);
        }
        return _upload?.CreateContent(_uploadType) ?? _multipart?.CreateContent();
    }

    private static string Format(object value) =>
        value switch
        {
            bool b => b ? "true" : "false",
            DateTimeOffset d => d.ToString("O", CultureInfo.InvariantCulture),
            DateTime d => d.ToString("O", CultureInfo.InvariantCulture),
            DateOnly d => d.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
            IFormattable f => f.ToString(null, CultureInfo.InvariantCulture),
            _ => value.ToString() ?? string.Empty,
        };

    private static bool IsNested(JsonNode? node) => node is JsonObject or JsonArray;

    private static string ScalarText(JsonNode node) =>
        node.GetValueKind() switch
        {
            JsonValueKind.String => node.GetValue<string>(),
            JsonValueKind.True => "true",
            JsonValueKind.False => "false",
            _ => node.ToJsonString(),
        };

    /// <summary>One JSON value as pairs, nested values the way Stripe-style APIs read them:
    /// <c>name[key]=value</c>, <c>name[]=item</c> for lists of scalars and
    /// <c>name[0][key]=value</c> for lists of objects.</summary>
    private static void EncodeParam(
        string name,
        JsonNode? value,
        bool deepObject,
        bool explode,
        List<KeyValuePair<string, string>> output
    )
    {
        if (value is JsonArray items && !deepObject && !items.Any(IsNested))
        {
            var texts = items.OfType<JsonNode>().Select(ScalarText).ToList();
            if (explode)
            {
                texts.ForEach(text => output.Add(new(name, text)));
            }
            else if (texts.Count > 0)
            {
                output.Add(new(name, string.Join(",", texts)));
            }
            return;
        }
        FlattenParam(name, value, output);
    }

    private static void FlattenParam(
        string prefix,
        JsonNode? value,
        List<KeyValuePair<string, string>> output
    )
    {
        switch (value)
        {
            case null:
                return;
            case JsonObject fields:
                foreach (var (key, item) in fields)
                {
                    FlattenParam($"{prefix}[{key}]", item, output);
                }
                return;
            case JsonArray items:
                for (var index = 0; index < items.Count; index++)
                {
                    var item = items[index];
                    FlattenParam(IsNested(item) ? $"{prefix}[{index}]" : $"{prefix}[]", item, output);
                }
                return;
            default:
                output.Add(new(prefix, ScalarText(value)));
                return;
        }
    }
}
