// this file is @generated by Perseid; edit the shared runtime template.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization.Metadata;

namespace @@PACKAGE_NAME@@;

/// <summary>One API call, built by the generated resources and sent by <see cref="ApiTransport"/>.</summary>
internal sealed class ApiRequest(HttpMethod method, string path)
{
    private readonly List<KeyValuePair<string, string>> _query = [];
    private byte[]? _json;
    private List<KeyValuePair<string, string>>? _form;

    public HttpMethod Method { get; } = method;

    public string Path { get; } = path;

    public Dictionary<string, string> Headers { get; } = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>Adds a query parameter unless <paramref name="value"/> is null. Lists repeat the
    /// parameter (OpenAPI <c>explode: true</c>) or are comma-joined.</summary>
    public void AddQuery(string name, object? value, bool explode = true)
    {
        switch (value)
        {
            case null:
                return;
            case string text:
                _query.Add(new(name, text));
                return;
            case IEnumerable items:
                var values = new List<string>();
                foreach (var item in items)
                {
                    if (item is not null)
                    {
                        values.Add(Format(item));
                    }
                }
                if (explode)
                {
                    values.ForEach(v => _query.Add(new(name, v)));
                }
                else if (values.Count > 0)
                {
                    _query.Add(new(name, string.Join(",", values)));
                }
                return;
            default:
                _query.Add(new(name, Format(value)));
                return;
        }
    }

    public void SetHeader(string name, string? value)
    {
        if (value is not null)
        {
            Headers[name] = value;
        }
    }

    public void SetJsonBody<T>(T body, JsonTypeInfo<T> typeInfo) =>
        _json = JsonSerializer.SerializeToUtf8Bytes(body, typeInfo);

    /// <summary>Sets an <c>application/x-www-form-urlencoded</c> body from the JSON form of
    /// <paramref name="body"/>, so wire names come from the model's attributes.</summary>
    public void SetFormBody<T>(T body, JsonTypeInfo<T> typeInfo)
    {
        if (JsonSerializer.SerializeToNode(body, typeInfo) is not JsonObject fields)
        {
            throw new ArgumentException("form bodies must serialize to JSON objects", nameof(body));
        }
        _form = [];
        foreach (var (name, value) in fields)
        {
            if (value is JsonArray array)
            {
                foreach (var item in array)
                {
                    if (item is not null)
                    {
                        _form.Add(new(name, FormValue(item)));
                    }
                }
            }
            else if (value is not null)
            {
                _form.Add(new(name, FormValue(value)));
            }
        }
    }

    public Uri BuildUri(string baseUrl)
    {
        var url = new StringBuilder(baseUrl.TrimEnd('/')).Append(Path);
        for (var i = 0; i < _query.Count; i++)
        {
            url.Append(i == 0 ? '?' : '&')
                .Append(Uri.EscapeDataString(_query[i].Key))
                .Append('=')
                .Append(Uri.EscapeDataString(_query[i].Value));
        }
        return new Uri(url.ToString());
    }

    /// <summary>A fresh body for each attempt: <see cref="HttpContent"/> cannot be sent twice.</summary>
    public HttpContent? CreateContent()
    {
        if (_json is not null)
        {
            var content = new ByteArrayContent(_json);
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json")
            {
                CharSet = "utf-8",
            };
            return content;
        }
        return _form is null ? null : new FormUrlEncodedContent(_form);
    }

    private static string Format(object value) =>
        value switch
        {
            bool b => b ? "true" : "false",
            DateTimeOffset d => d.ToString("O", CultureInfo.InvariantCulture),
            DateTime d => d.ToString("O", CultureInfo.InvariantCulture),
            IFormattable f => f.ToString(null, CultureInfo.InvariantCulture),
            _ => value.ToString() ?? string.Empty,
        };

    private static string FormValue(JsonNode node) =>
        node.GetValueKind() == JsonValueKind.String ? node.GetValue<string>() : node.ToJsonString();
}
