// this file is @generated by Perseid; edit the shared runtime template.
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using System.Threading;
using System.Threading.Tasks;

namespace @@PACKAGE_NAME@@;

/// <summary>Sends <see cref="ApiRequest"/>s through the middleware: authentication, idempotency
/// keys, timeouts, retries, tracing and error mapping.</summary>
internal sealed class ApiTransport : IDisposable
{
    private static readonly TimeSpan InitialBackoff = TimeSpan.FromMilliseconds(500);
    private static readonly TimeSpan MaxBackoff = TimeSpan.FromSeconds(8);
    private static readonly TimeSpan MaxRetryAfter = TimeSpan.FromSeconds(60);

    internal static readonly string Version =
        typeof(ApiTransport)
            .Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()
            ?.InformationalVersion.Split('+')[0]
        ?? "0.0.0";

    private static readonly ActivitySource s_activities = new(
        @@CLIENT_NAME@@ClientOptions.ActivitySourceName,
        Version
    );

    private readonly HttpMessageInvoker _pipeline;
    private readonly ApiAuth _auth;
    private readonly Credentials _credentials;
    private readonly string _baseUrl;
    private readonly TimeSpan _timeout;
    private readonly IReadOnlyList<TimeSpan>? _retrySchedule;
    private readonly int _maxRetries;
    private readonly string _userAgent;

    public ApiTransport(
        ApiAuth auth,
        Credentials credentials,
        @@CLIENT_NAME@@ClientOptions options,
        HttpClient? http
    )
    {
        _baseUrl =
            options.BaseUrl
            ?? NonEmpty(Environment.GetEnvironmentVariable("@@ENV_PREFIX@@_BASE_URL"))
            ?? @@CLIENT_NAME@@ClientOptions.DefaultBaseUrl
            ?? throw new @@CLIENT_NAME@@Exception(
                "no base URL: set BaseUrl in the @@CLIENT_NAME@@ClientOptions or the @@ENV_PREFIX@@_BASE_URL environment variable"
            );
        HttpMessageHandler handler = http is not null
            ? new Forwarder(http, owned: false)
            : options.HttpMessageHandler is { } custom
                ? new Forwarder(new HttpMessageInvoker(custom, disposeHandler: false), owned: true)
                : new SocketsHttpHandler { PooledConnectionLifetime = TimeSpan.FromMinutes(5) };
        for (var i = options.Handlers.Count - 1; i >= 0; i--)
        {
            options.Handlers[i].InnerHandler = handler;
            handler = options.Handlers[i];
        }
        _pipeline = new HttpMessageInvoker(handler);
        _auth = auth;
        _credentials = credentials;
        if (credentials.OAuth is { } oauth)
        {
            oauth.Fetch = FetchGrantAsync;
        }
        _timeout = options.Timeout;
        _retrySchedule = options.RetrySchedule;
        _maxRetries = Math.Max(0, options.MaxRetries);
        _userAgent = options.UserAgent ?? $"@@USER_AGENT_PREFIX@@-csharp/{Version}";
    }

    internal static string? NonEmpty(string? value) => string.IsNullOrEmpty(value) ? null : value;

    /// <summary>Requests an access token with the client credentials grant, through the middleware,
    /// timeouts and retries like any other request.</summary>
    private async Task<OAuthGrant> FetchGrantAsync(
        string tokenUrl,
        string scope,
        OAuthClient client,
        CancellationToken cancellationToken
    )
    {
        var request = new ApiRequest(HttpMethod.Post, tokenUrl, "oauth.token") { Security = [] };
        var form = new List<KeyValuePair<string, string>> { new("grant_type", "client_credentials") };
        if (scope.Length > 0)
        {
            form.Add(new("scope", scope));
        }
        if (client.InBody)
        {
            form.Add(new("client_id", client.ClientId));
            form.Add(new("client_secret", client.ClientSecret));
        }
        else
        {
            request.Headers["Authorization"] = client.BasicAuthorization();
        }
        request.SetFormFields(form);
        var result = await SendWithRetriesAsync(request, null, false, cancellationToken).ConfigureAwait(false);
        try
        {
            using var document = JsonDocument.Parse(result.Body);
            var root = document.RootElement;
            if (
                root.ValueKind != JsonValueKind.Object
                || !root.TryGetProperty("access_token", out var token)
                || token.ValueKind != JsonValueKind.String
                || string.IsNullOrEmpty(token.GetString())
            )
            {
                throw new ApiDecodeException("the token endpoint answered without an access_token", null);
            }
            double? expiresIn = null;
            if (root.TryGetProperty("expires_in", out var life))
            {
                if (life.ValueKind == JsonValueKind.Number)
                {
                    expiresIn = life.GetDouble();
                }
                else if (
                    life.ValueKind == JsonValueKind.String
                    && double.TryParse(life.GetString(), NumberStyles.Float, CultureInfo.InvariantCulture, out var parsed)
                )
                {
                    expiresIn = parsed;
                }
            }
            return new OAuthGrant(token.GetString()!, expiresIn);
        }
        catch (JsonException e)
        {
            throw new ApiDecodeException($"the token endpoint response is not JSON: {e.Message}", e);
        }
    }

    public async Task<ApiResponse> SendAsync(
        ApiRequest request,
        RequestOptions? options,
        CancellationToken cancellationToken
    ) =>
        (await SendWithRetriesAsync(request, options, false, cancellationToken).ConfigureAwait(false))
            .Response;

    public async Task<ApiResponse<T>> SendJsonAsync<T>(
        ApiRequest request,
        JsonTypeInfo<T> typeInfo,
        RequestOptions? options,
        CancellationToken cancellationToken
    )
    {
        var result = await SendWithRetriesAsync(request, options, false, cancellationToken)
            .ConfigureAwait(false);
        if (result.Body.Length == 0)
        {
            throw new ApiDecodeException(
                $"expected a {typeof(T).Name} body, got an empty response (status {(int)result.Response.StatusCode})",
                null
            );
        }
        return new ApiResponse<T>(result.Response, Decode(result.Body, typeInfo));
    }

    private static T Decode<T>(byte[] body, JsonTypeInfo<T> typeInfo)
    {
        try
        {
            return JsonSerializer.Deserialize(body, typeInfo)
                ?? throw new JsonException($"expected a {typeof(T).Name} body, got null");
        }
        catch (JsonException e)
        {
            throw new ApiDecodeException($"the response is not a valid {typeof(T).Name}: {e.Message}", e);
        }
    }

    /// <summary>Like <see cref="SendJsonAsync"/>, with the default <typeparamref name="TResult"/>
    /// (<c>null</c>) for an empty body or a JSON <c>null</c>.</summary>
    public async Task<ApiResponse<TResult>> SendJsonOrDefaultAsync<T, TResult>(
        ApiRequest request,
        JsonTypeInfo<T> typeInfo,
        RequestOptions? options,
        CancellationToken cancellationToken
    )
    {
        var result = await SendWithRetriesAsync(request, options, false, cancellationToken)
            .ConfigureAwait(false);
        return new(
            result.Response,
            IsNullBody(result.Body) ? default! : (TResult)(object)Decode(result.Body, typeInfo)!
        );
    }

    private static bool IsNullBody(byte[] body)
    {
        var text = System.Text.Encoding.UTF8.GetString(body).Trim();
        return text.Length == 0 || text == "null";
    }

    public async Task<ApiResponse<byte[]>> SendBytesAsync(
        ApiRequest request,
        RequestOptions? options,
        CancellationToken cancellationToken
    )
    {
        var result = await SendWithRetriesAsync(request, options, false, cancellationToken)
            .ConfigureAwait(false);
        return new(result.Response, result.Body);
    }

    public async Task<ApiResponse<string>> SendTextAsync(
        ApiRequest request,
        RequestOptions? options,
        CancellationToken cancellationToken
    )
    {
        var result = await SendWithRetriesAsync(request, options, false, cancellationToken)
            .ConfigureAwait(false);
        return new(result.Response, System.Text.Encoding.UTF8.GetString(result.Body));
    }

    /// <summary>Opens an event stream. The timeout covers the response headers, not the events.</summary>
    public async Task<ApiResponse<EventStream>> SendEventStreamAsync(
        ApiRequest request,
        RequestOptions? options,
        CancellationToken cancellationToken
    )
    {
        request.Headers["Accept"] = "text/event-stream";
        var result = await SendWithRetriesAsync(request, options, true, cancellationToken)
            .ConfigureAwait(false);
        var response = result.Stream!;
        var mediaType = response.Content.Headers.ContentType?.MediaType;
        if (!string.Equals(mediaType, "text/event-stream", StringComparison.OrdinalIgnoreCase))
        {
            response.Dispose();
            throw new ApiDecodeException(
                $"expected a text/event-stream response, got {mediaType ?? "no content type"}",
                null
            );
        }
        return new(result.Response, new EventStream(response));
    }

    /// <summary>Opens an event stream whose events carry <typeparamref name="T"/> as JSON.</summary>
    public async Task<ApiResponse<EventStream<T>>> SendEventStreamAsync<T>(
        ApiRequest request,
        JsonTypeInfo<T> typeInfo,
        RequestOptions? options,
        CancellationToken cancellationToken
    )
    {
        var raw = await SendEventStreamAsync(request, options, cancellationToken).ConfigureAwait(false);
        return new(raw, new EventStream<T>(raw.Value, typeInfo));
    }

    private readonly record struct Result(ApiResponse Response, byte[] Body, HttpResponseMessage? Stream);

    private async Task<Result> SendWithRetriesAsync(
        ApiRequest request,
        RequestOptions? options,
        bool stream,
        CancellationToken cancellationToken
    )
    {
        var headers = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Accept"] = "application/json, */*;q=0.8",
        };
        var authQuery = new List<KeyValuePair<string, string>>();
        var oauthUse = await _auth
            .ApplyAsync(request.Security, _credentials, headers, authQuery, cancellationToken)
            .ConfigureAwait(false);
        headers.Remove("Cookie", out var authCookie);
        headers["User-Agent"] = _userAgent;
        headers["@@HEADER_PREFIX@@-req-id"] = ((ulong)Random.Shared.NextInt64()).ToString(
            CultureInfo.InvariantCulture
        );
        foreach (var (name, value) in request.Headers)
        {
            headers[name] = value;
        }
        if (options?.IdempotencyKey is { } key)
        {
            headers["Idempotency-Key"] = key;
        }
        foreach (var (name, value) in options?.Headers ?? new Dictionary<string, string>())
        {
            headers[name] = value;
        }
        // Cookie parameters, the API key cookie and a Cookie header of the call share one header.
        var cookies = new List<string>(request.Cookies);
        if (authCookie is not null)
        {
            cookies.Add(authCookie);
        }
        if (headers.Remove("Cookie", out var callCookie))
        {
            cookies.Add(callCookie);
        }
        if (cookies.Count > 0)
        {
            headers["Cookie"] = string.Join("; ", cookies);
        }
        if (request.Method == HttpMethod.Post && !headers.ContainsKey("Idempotency-Key"))
        {
            headers["Idempotency-Key"] = $"auto_{Guid.NewGuid()}";
        }

        var uri = request.BuildUri(_baseUrl, authQuery);
        var retryable =
            (IsIdempotent(request.Method) || headers.ContainsKey("Idempotency-Key"))
            && !request.IsOneShot;
        var retries = retryable
            ? Math.Max(0, options?.MaxRetries ?? _retrySchedule?.Count ?? _maxRetries)
            : 0;
        var timeout = options?.Timeout ?? _timeout;
        using var activity = s_activities.StartActivity(request.Operation, ActivityKind.Client);
        activity?.SetTag("http.request.method", request.Method.Method);
        activity?.SetTag("url.full", uri.GetLeftPart(UriPartial.Path));
        // An access token the API rejects is replaced once, without using up a retry.
        var renewed = false;
        for (var attempt = 0; ; attempt++)
        {
            if (attempt > 0)
            {
                headers["@@HEADER_PREFIX@@-retry-count"] = attempt.ToString(
                    CultureInfo.InvariantCulture
                );
                activity?.SetTag("http.request.resend_count", attempt);
            }
            using var message = new HttpRequestMessage(request.Method, uri)
            {
                Content = request.CreateContent(),
            };
            foreach (var (name, value) in headers)
            {
                if (!message.Headers.TryAddWithoutValidation(name, value))
                {
                    message.Content?.Headers.TryAddWithoutValidation(name, value);
                }
            }

            var last = attempt >= retries;
            var renew = false;
            TimeSpan? wait = null;
            using (var attemptToken = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken))
            {
                attemptToken.CancelAfter(timeout);
                try
                {
                    var response = await _pipeline
                        .SendAsync(message, attemptToken.Token)
                        .ConfigureAwait(false);
                    activity?.SetTag("http.response.status_code", (int)response.StatusCode);
                    var meta = new ApiResponse(
                        response.StatusCode,
                        response.Headers,
                        response.Content.Headers
                    );
                    if (response.IsSuccessStatusCode && stream)
                    {
                        return new(meta, [], response);
                    }
                    byte[] body;
                    using (response)
                    {
                        body = await response
                            .Content.ReadAsByteArrayAsync(attemptToken.Token)
                            .ConfigureAwait(false);
                    }
                    if (response.IsSuccessStatusCode)
                    {
                        return new(meta, body, null);
                    }
                    if (
                        !renewed
                        && oauthUse is not null
                        && response.StatusCode == HttpStatusCode.Unauthorized
                        && !request.IsOneShot
                        && headers.TryGetValue("Authorization", out var sent)
                        && sent == $"Bearer {oauthUse.Token}"
                    )
                    {
                        renew = true;
                    }
                    else if (last || !ShouldRetry((int)response.StatusCode))
                    {
                        activity?.SetStatus(ActivityStatusCode.Error);
                        throw ApiExceptionExtensions.ForResponse(
                            response.StatusCode,
                            System.Text.Encoding.UTF8.GetString(body),
                            response.Headers,
                            request.ErrorTypes
                        );
                    }
                    else
                    {
                        wait = RetryDelay(attempt, response);
                    }
                }
                catch (Exception e) when (e is HttpRequestException or IOException)
                {
                    if (last)
                    {
                        activity?.SetStatus(ActivityStatusCode.Error, e.Message);
                        throw new ApiConnectionException(
                            $"{request.Method} {request.Path} failed: {e.Message}",
                            e
                        );
                    }
                }
                catch (OperationCanceledException e) when (!cancellationToken.IsCancellationRequested)
                {
                    if (last)
                    {
                        activity?.SetStatus(ActivityStatusCode.Error, "timeout");
                        throw new ApiTimeoutException(
                            $"{request.Method} {request.Path} timed out after {timeout}",
                            e
                        );
                    }
                }
            }
            if (renew)
            {
                renewed = true;
                oauthUse = await _auth.RenewAsync(oauthUse!, _credentials, cancellationToken).ConfigureAwait(false);
                headers["Authorization"] = $"Bearer {oauthUse.Token}";
                attempt--;
                continue;
            }
            await Task.Delay(wait ?? Backoff(attempt), cancellationToken).ConfigureAwait(false);
        }
    }

    private static bool IsIdempotent(HttpMethod method) =>
        method == HttpMethod.Get
        || method == HttpMethod.Head
        || method == HttpMethod.Put
        || method == HttpMethod.Delete
        || method == HttpMethod.Options
        || method == HttpMethod.Trace;

    private static bool ShouldRetry(int status) => status is 408 or 429 or >= 500;

    /// <summary>The server's <c>retry-after-ms</c> or <c>Retry-After</c> when within a minute, else
    /// the backoff.</summary>
    private TimeSpan RetryDelay(int attempt, HttpResponseMessage response) =>
        RetryAfter(response, DateTimeOffset.UtcNow) is { } delay
        && delay >= TimeSpan.Zero
        && delay <= MaxRetryAfter
            ? delay
            : Backoff(attempt);

    /// <summary>The scheduled delay, else 0.5s doubling up to 8s, with jitter between half and all of it.</summary>
    private TimeSpan Backoff(int attempt)
    {
        if (_retrySchedule is not null && attempt < _retrySchedule.Count)
        {
            return _retrySchedule[attempt];
        }
        var backoff = InitialBackoff * Math.Pow(2, Math.Min(attempt, 16));
        var capped = backoff < MaxBackoff ? backoff : MaxBackoff;
        return capped * (0.5 + Random.Shared.NextDouble() / 2);
    }

    /// <summary><c>retry-after-ms</c>, else <c>Retry-After</c> in seconds or as an HTTP date.</summary>
    internal static TimeSpan? RetryAfter(HttpResponseMessage? response, DateTimeOffset now)
    {
        if (response is null)
        {
            return null;
        }
        if (
            response.Headers.TryGetValues("retry-after-ms", out var ms)
            && double.TryParse(
                string.Join(",", ms),
                NumberStyles.Float,
                CultureInfo.InvariantCulture,
                out var millis
            )
            && double.IsFinite(millis)
        )
        {
            return TimeSpan.FromMilliseconds(Math.Clamp(millis, -1, int.MaxValue));
        }
        return response.Headers.RetryAfter switch
        {
            { Delta: { } delta } => delta,
            { Date: { } date } => date - now,
            _ => null,
        };
    }

    public void Dispose()
    {
        _pipeline.Dispose();
        _credentials.OAuth?.Dispose();
    }

    /// <summary>Ends the middleware chain with an <see cref="HttpClient"/> or a caller's handler.</summary>
    private sealed class Forwarder(HttpMessageInvoker inner, bool owned) : HttpMessageHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request,
            CancellationToken cancellationToken
        ) =>
            inner is HttpClient client
                ? client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken)
                : inner.SendAsync(request, cancellationToken);

        protected override void Dispose(bool disposing)
        {
            if (disposing && owned)
            {
                inner.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
