// this file is @generated by Perseid; edit the shared runtime template.
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace @@PACKAGE_NAME@@;

/// <summary>HTTP basic credentials.</summary>
/// <param name="Username">The user name.</param>
/// <param name="Password">The password, left out of <see cref="ToString"/>.</param>
public sealed record BasicCredentials(string Username, string Password)
{
    /// <summary>The user name, without the password.</summary>
    /// <returns>The description.</returns>
    public override string ToString() => $"BasicCredentials {{ Username = {Username} }}";
}

internal enum SchemeKind
{
    Bearer,
    Basic,
    ApiKey,
}

/// <summary>A security scheme of the spec; API keys go in a header, query parameter or cookie.</summary>
internal sealed record SecurityScheme(SchemeKind Kind, string? In = null, string? Param = null);

/// <summary>What the caller configured to authenticate.</summary>
internal sealed record Credentials(
    string? Token,
    Func<CancellationToken, ValueTask<string>>? TokenProvider,
    BasicCredentials? Basic,
    IReadOnlyDictionary<string, string?> ApiKeys
);

/// <summary>The API's security schemes, and the requirement of operations declaring none: the first
/// alternative whose credentials are all configured is sent.</summary>
internal sealed class ApiAuth(IReadOnlyDictionary<string, SecurityScheme> schemes, string[][] security)
{
    public async ValueTask ApplyAsync(
        string[][]? requirement,
        Credentials credentials,
        IDictionary<string, string> headers,
        IList<KeyValuePair<string, string>> query,
        CancellationToken cancellationToken
    )
    {
        string[]? chosen = null;
        foreach (var names in requirement ?? security)
        {
            if (names.Length > 0 && Array.TrueForAll(names, n => Configured(n, credentials)))
            {
                chosen = names;
                break;
            }
        }
        foreach (var name in chosen ?? [])
        {
            var scheme = schemes[name];
            switch (scheme.Kind)
            {
                case SchemeKind.Bearer:
                    var token = credentials.TokenProvider is { } provider
                        ? await provider(cancellationToken).ConfigureAwait(false)
                        : credentials.Token;
                    headers["Authorization"] = $"Bearer {token}";
                    break;
                case SchemeKind.Basic:
                    var (username, password) = credentials.Basic!;
                    var encoded = Convert.ToBase64String(
                        Encoding.UTF8.GetBytes($"{username}:{password}")
                    );
                    headers["Authorization"] = $"Basic {encoded}";
                    break;
                default:
                    var key = ApiKey(name, credentials)!;
                    if (scheme.In == "query")
                    {
                        query.Add(new(scheme.Param!, key));
                    }
                    else if (scheme.In == "cookie")
                    {
                        var cookie = $"{scheme.Param}={Uri.EscapeDataString(key)}";
                        headers["Cookie"] = headers.TryGetValue("Cookie", out var existing)
                            ? $"{existing}; {cookie}"
                            : cookie;
                    }
                    else
                    {
                        headers[scheme.Param!] = key;
                    }
                    break;
            }
        }
    }

    private bool Configured(string name, Credentials credentials) =>
        schemes.TryGetValue(name, out var scheme)
        && scheme.Kind switch
        {
            SchemeKind.Bearer => credentials.TokenProvider is not null
                || !string.IsNullOrEmpty(credentials.Token),
            SchemeKind.Basic => credentials.Basic is not null,
            _ => !string.IsNullOrEmpty(ApiKey(name, credentials)),
        };

    private static string? ApiKey(string name, Credentials credentials) =>
        credentials.ApiKeys.TryGetValue(name, out var key) && !string.IsNullOrEmpty(key)
            ? key
            : credentials.Token;
}
