// this file is @generated by Perseid; edit the shared runtime template.
using System;
using System.Collections.Generic;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace @@PACKAGE_NAME@@;

/// <summary>HTTP basic credentials.</summary>
/// <param name="Username">The user name.</param>
/// <param name="Password">The password, left out of <see cref="ToString"/>.</param>
public sealed record BasicCredentials(string Username, string Password)
{
    /// <summary>The user name, without the password.</summary>
    /// <returns>The description.</returns>
    public override string ToString() => $"BasicCredentials {{ Username = {Username} }}";
}

internal enum SchemeKind
{
    Bearer,
    Basic,
    ApiKey,
}

/// <summary>A security scheme of the spec; API keys go in a header, query parameter or cookie. A bearer
/// scheme with a <paramref name="TokenUrl"/> (absolute, or relative to the base URL) gets its token
/// from the OAuth2 client credentials flow, asking for <paramref name="Scope"/>.</summary>
internal sealed record SecurityScheme(
    SchemeKind Kind,
    string? In = null,
    string? Param = null,
    string? TokenUrl = null,
    string? Scope = null
);

/// <summary>What the caller configured to authenticate.</summary>
internal sealed record Credentials(
    string? Token,
    Func<CancellationToken, ValueTask<string>>? TokenProvider,
    BasicCredentials? Basic,
    IReadOnlyDictionary<string, string?> ApiKeys,
    OAuthClient? OAuth = null
);

/// <summary>The answer of a token endpoint; <paramref name="ExpiresIn"/> is in seconds.</summary>
internal readonly record struct OAuthGrant(string AccessToken, double? ExpiresIn);

/// <summary>The OAuth2 access token a request carries, which a 401 response replaces.</summary>
internal sealed record OAuthUse(string Scheme, string Token);

/// <summary>OAuth2 client credentials: an access token per security scheme, fetched on first use and
/// kept until it is about to expire. Concurrent callers share one token request.</summary>
internal sealed class OAuthClient(string clientId, string clientSecret, bool inBody) : IDisposable
{
    /// <summary>Tokens are renewed this long before they expire, or at half their life when shorter.</summary>
    private const long MarginMs = 60_000;

    private readonly SemaphoreSlim _gate = new(1, 1);
    private readonly Dictionary<string, (string Token, long ExpiresAt)> _tokens = [];

    public string ClientId { get; } = clientId;

    public string ClientSecret { get; } = clientSecret;

    /// <summary>Whether the credentials go in the form of the token request, not a basic header.</summary>
    public bool InBody { get; } = inBody;

    /// <summary>Requests a token: the token URL, the scope and these credentials.</summary>
    public Func<string, string, OAuthClient, CancellationToken, Task<OAuthGrant>>? Fetch { get; set; }

    /// <summary>The <c>Authorization</c> header of the credentials, form-encoded before the base64 (RFC 6749 2.3.1).</summary>
    public string BasicAuthorization() =>
        "Basic "
        + Convert.ToBase64String(
            Encoding.UTF8.GetBytes($"{WebUtility.UrlEncode(ClientId)}:{WebUtility.UrlEncode(ClientSecret)}")
        );

    public async ValueTask<string> TokenAsync(
        string name,
        SecurityScheme scheme,
        CancellationToken cancellationToken
    )
    {
        await _gate.WaitAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            lock (_tokens)
            {
                if (_tokens.TryGetValue(name, out var cached) && cached.ExpiresAt > Environment.TickCount64)
                {
                    return cached.Token;
                }
            }
            var fetch = Fetch ?? throw new InvalidOperationException("the OAuth2 client has no transport");
            var grant = await fetch(scheme.TokenUrl!, scheme.Scope ?? "", this, cancellationToken)
                .ConfigureAwait(false);
            var life = grant.ExpiresIn is { } seconds ? (long)(Math.Max(seconds, 0) * 1000) : long.MaxValue / 4;
            var expiresAt = Environment.TickCount64 + life - Math.Min(MarginMs, life / 2);
            lock (_tokens)
            {
                _tokens[name] = (grant.AccessToken, expiresAt);
            }
            return grant.AccessToken;
        }
        finally
        {
            _gate.Release();
        }
    }

    /// <summary>Forgets <paramref name="token"/> of the scheme after the API rejected it, unless a newer one replaced it.</summary>
    public void Forget(string name, string token)
    {
        lock (_tokens)
        {
            if (_tokens.TryGetValue(name, out var cached) && cached.Token == token)
            {
                _tokens.Remove(name);
            }
        }
    }

    /// <summary>Releases the gate that serializes token requests.</summary>
    public void Dispose() => _gate.Dispose();
}

/// <summary>The API's security schemes, and the requirement of operations declaring none: the first
/// alternative whose credentials are all configured is sent.</summary>
internal sealed class ApiAuth(IReadOnlyDictionary<string, SecurityScheme> schemes, string[][] security)
{
    /// <summary>Adds the credentials of the first satisfiable alternative to a request. Gives the OAuth2
    /// access token it used, if any.</summary>
    public async ValueTask<OAuthUse?> ApplyAsync(
        string[][]? requirement,
        Credentials credentials,
        IDictionary<string, string> headers,
        IList<KeyValuePair<string, string>> query,
        CancellationToken cancellationToken
    )
    {
        string[]? chosen = null;
        foreach (var names in requirement ?? security)
        {
            if (names.Length > 0 && Array.TrueForAll(names, n => Configured(n, credentials)))
            {
                chosen = names;
                break;
            }
        }
        OAuthUse? used = null;
        foreach (var name in chosen ?? [])
        {
            var scheme = schemes[name];
            switch (scheme.Kind)
            {
                case SchemeKind.Bearer:
                    string? token;
                    if (credentials.TokenProvider is { } provider)
                    {
                        token = await provider(cancellationToken).ConfigureAwait(false);
                    }
                    else if (!string.IsNullOrEmpty(credentials.Token))
                    {
                        token = credentials.Token;
                    }
                    else if (scheme.TokenUrl is not null && credentials.OAuth is { } oauth)
                    {
                        token = await oauth.TokenAsync(name, scheme, cancellationToken).ConfigureAwait(false);
                        used = new OAuthUse(name, token);
                    }
                    else
                    {
                        token = credentials.Token;
                    }
                    headers["Authorization"] = $"Bearer {token}";
                    break;
                case SchemeKind.Basic:
                    var (username, password) = credentials.Basic!;
                    var encoded = Convert.ToBase64String(
                        Encoding.UTF8.GetBytes($"{username}:{password}")
                    );
                    headers["Authorization"] = $"Basic {encoded}";
                    break;
                default:
                    var key = ApiKey(name, credentials)!;
                    if (scheme.In == "query")
                    {
                        query.Add(new(scheme.Param!, key));
                    }
                    else if (scheme.In == "cookie")
                    {
                        var cookie = $"{scheme.Param}={Uri.EscapeDataString(key)}";
                        headers["Cookie"] = headers.TryGetValue("Cookie", out var existing)
                            ? $"{existing}; {cookie}"
                            : cookie;
                    }
                    else
                    {
                        headers[scheme.Param!] = key;
                    }
                    break;
            }
        }
        return used;
    }

    /// <summary>The access token that replaces <paramref name="rejected"/>, which the API refused.</summary>
    public async ValueTask<OAuthUse> RenewAsync(
        OAuthUse rejected,
        Credentials credentials,
        CancellationToken cancellationToken
    )
    {
        var oauth = credentials.OAuth!;
        oauth.Forget(rejected.Scheme, rejected.Token);
        var token = await oauth
            .TokenAsync(rejected.Scheme, schemes[rejected.Scheme], cancellationToken)
            .ConfigureAwait(false);
        return rejected with { Token = token };
    }

    private bool Configured(string name, Credentials credentials) =>
        schemes.TryGetValue(name, out var scheme)
        && scheme.Kind switch
        {
            SchemeKind.Bearer => credentials.TokenProvider is not null
                || !string.IsNullOrEmpty(credentials.Token)
                || (scheme.TokenUrl is not null && credentials.OAuth is not null),
            SchemeKind.Basic => credentials.Basic is not null,
            _ => !string.IsNullOrEmpty(ApiKey(name, credentials)),
        };

    private static string? ApiKey(string name, Credentials credentials) =>
        credentials.ApiKeys.TryGetValue(name, out var key) && !string.IsNullOrEmpty(key)
            ? key
            : credentials.Token;
}
