// this file is @generated by Perseid; edit the shared runtime template.
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using System.Threading;
using System.Threading.Tasks;

namespace @@PACKAGE_NAME@@;

/// <summary>How a list operation pages. Paths are JSON property names from the response root.</summary>
internal sealed record Pagination(string[] Items)
{
    public string[]? NextCursor { get; init; }
    public string? ItemCursor { get; init; }
    public string[]? HasMore { get; init; }
    public string[]? TotalPages { get; init; }
    public string[]? Total { get; init; }
    public long FirstPage { get; init; } = 1;
}

/// <summary>Yields every item of a paginated operation, fetching the next page once the current one is consumed.</summary>
internal static class Paginator
{
    public static async IAsyncEnumerable<TItem> CursorAsync<TPage, TItem>(
        Pagination pagination,
        string? start,
        Func<string?, CancellationToken, Task<TPage>> fetchPage,
        JsonTypeInfo<TPage> pageInfo,
        JsonTypeInfo<TItem> itemInfo,
        [EnumeratorCancellation] CancellationToken cancellationToken
    )
    {
        var cursor = start;
        while (true)
        {
            var page = JsonSerializer.SerializeToElement(
                await fetchPage(cursor, cancellationToken).ConfigureAwait(false),
                pageInfo
            );
            var items = Items(page, pagination);
            foreach (var item in items)
            {
                yield return item.Deserialize(itemInfo)!;
            }
            if (items.Count == 0 || NoMore(page, pagination))
            {
                yield break;
            }
            var next = pagination.NextCursor is { } path
                ? At(page, path)
                : At(items[^1], [pagination.ItemCursor!]);
            var value = next?.ValueKind == JsonValueKind.String ? next.Value.GetString() : null;
            if (string.IsNullOrEmpty(value) || value == cursor)
            {
                yield break;
            }
            cursor = value;
        }
    }

    /// <summary>Page (<paramref name="pages"/>) or offset pagination.</summary>
    public static async IAsyncEnumerable<TItem> NumberedAsync<TPage, TItem>(
        Pagination pagination,
        bool pages,
        long? start,
        Func<long, CancellationToken, Task<TPage>> fetchPage,
        JsonTypeInfo<TPage> pageInfo,
        JsonTypeInfo<TItem> itemInfo,
        [EnumeratorCancellation] CancellationToken cancellationToken
    )
    {
        var param = start ?? (pages ? pagination.FirstPage : 0);
        while (true)
        {
            var page = JsonSerializer.SerializeToElement(
                await fetchPage(param, cancellationToken).ConfigureAwait(false),
                pageInfo
            );
            var items = Items(page, pagination);
            foreach (var item in items)
            {
                yield return item.Deserialize(itemInfo)!;
            }
            if (items.Count == 0 || NoMore(page, pagination))
            {
                yield break;
            }
            if (pages)
            {
                if (
                    Integer(page, pagination.TotalPages) is { } totalPages
                    && param - pagination.FirstPage + 1 >= totalPages
                )
                {
                    yield break;
                }
                param++;
            }
            else
            {
                param += items.Count;
                if (Integer(page, pagination.Total) is { } total && param >= total)
                {
                    yield break;
                }
            }
        }
    }

    private static List<JsonElement> Items(JsonElement page, Pagination pagination) =>
        At(page, pagination.Items) is { ValueKind: JsonValueKind.Array } items
            ? [.. items.EnumerateArray()]
            : [];

    private static bool NoMore(JsonElement page, Pagination pagination) =>
        pagination.HasMore is { } path && At(page, path)?.ValueKind == JsonValueKind.False;

    private static long? Integer(JsonElement page, string[]? path) =>
        path is not null && At(page, path) is { ValueKind: JsonValueKind.Number } value
            ? value.GetInt64()
            : null;

    private static JsonElement? At(JsonElement value, string[] path)
    {
        foreach (var key in path)
        {
            if (value.ValueKind != JsonValueKind.Object || !value.TryGetProperty(key, out value))
            {
                return null;
            }
        }
        return value;
    }
}
