// this file is @generated by Perseid; edit the shared runtime template.
using System;
using System.Collections.Generic;

namespace @@PACKAGE_NAME@@;

/// <summary>Options for a single call, the argument before the <c>CancellationToken</c> of every method.</summary>
public sealed class RequestOptions
{
    /// <summary>Extra headers, sent in place of the SDK's own headers of the same name.</summary>
    public IDictionary<string, string> Headers { get; init; } =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

    /// <summary>Bounds each attempt instead of the client's <c>Timeout</c>.</summary>
    public TimeSpan? Timeout { get; init; }

    /// <summary>How many times this call may be retried, instead of the client's setting.</summary>
    public int? MaxRetries { get; init; }

    /// <summary>Sent as the <c>Idempotency-Key</c> header, making the request retryable. POST
    /// requests get a random one by default.</summary>
    public string? IdempotencyKey { get; init; }
}
