// this file is @generated by Perseid; edit the shared runtime template.
use std::time::Duration;
use hyper::body::Bytes;
use hyper_util::client::legacy::Client as HyperClient;
use crate::connector::Connector;

pub struct Configuration {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub bearer_access_token: Option<String>,
    pub timeout: Option<Duration>,
    pub num_retries: u32,
    pub retry_schedule: Option<Vec<Duration>>,

    pub(crate) client: HyperClient<Connector, http_body_util::Full<Bytes>>,
}
