// this file is @generated by Perseid; edit the shared runtime template.
//! Iteration over every item of a paginated list operation.
#![allow(dead_code)]
use std::{
    collections::VecDeque,
    future::Future,
    pin::Pin,
    task::{Context, Poll},
};

use serde::de::DeserializeOwned;
use serde_json::Value;

use crate::error::Error;

pub(crate) enum Style {
    Cursor,
    Page,
    Offset,
}

/// How an operation pages. Paths are JSON property names from the response root.
pub(crate) struct Spec {
    pub(crate) style: Style,
    pub(crate) items: &'static [&'static str],
    pub(crate) next_cursor: Option<&'static [&'static str]>,
    pub(crate) item_cursor: Option<&'static str>,
    pub(crate) has_more: Option<&'static [&'static str]>,
    pub(crate) total_pages: Option<&'static [&'static str]>,
    pub(crate) total: Option<&'static [&'static str]>,
    pub(crate) first_page: i64,
}

pub(crate) type PageFuture<'a> = Pin<Box<dyn Future<Output = Result<Value, Error>> + Send + 'a>>;
type Fetch<'a> = Box<dyn FnMut(Option<Value>) -> PageFuture<'a> + Send + 'a>;

/// Every item of a paginated list operation, fetching the next page once the
/// current one is consumed: `while let Some(item) = items.next().await`.
/// It is also a `futures_core::Stream`.
pub struct Paginator<'a, T> {
    spec: &'static Spec,
    fetch: Fetch<'a>,
    pending: Option<PageFuture<'a>>,
    param: Option<Value>,
    buffered: VecDeque<T>,
    done: bool,
}

// Items are never pinned: only the boxed page future is polled in place.
impl<T> Unpin for Paginator<'_, T> {}

impl<'a, T: DeserializeOwned> Paginator<'a, T> {
    pub(crate) fn new(spec: &'static Spec, start: Option<Value>, fetch: Fetch<'a>) -> Self {
        let param = start.or(match spec.style {
            Style::Page => Some(spec.first_page.into()),
            Style::Offset => Some(0.into()),
            Style::Cursor => None,
        });
        Self {
            spec,
            fetch,
            pending: None,
            param,
            buffered: VecDeque::new(),
            done: false,
        }
    }

    /// The next item, `None` once every item has been read. An error ends the iteration.
    pub async fn next(&mut self) -> Option<Result<T, Error>> {
        std::future::poll_fn(|cx| self.poll_item(cx)).await
    }

    pub(crate) fn poll_item(&mut self, cx: &mut Context<'_>) -> Poll<Option<Result<T, Error>>> {
        loop {
            if let Some(item) = self.buffered.pop_front() {
                return Poll::Ready(Some(Ok(item)));
            }
            if self.done {
                return Poll::Ready(None);
            }
            let param = &self.param;
            let fetch = &mut self.fetch;
            let page = self.pending.get_or_insert_with(|| fetch(param.clone()));
            let Poll::Ready(page) = page.as_mut().poll(cx) else {
                return Poll::Pending;
            };
            self.pending = None;
            if let Err(error) = page.and_then(|page| self.read_page(&page)) {
                self.done = true;
                return Poll::Ready(Some(Err(error)));
            }
        }
    }

    /// Reads every remaining item.
    pub async fn collect(mut self) -> Result<Vec<T>, Error> {
        let mut items = Vec::new();
        while let Some(item) = self.next().await {
            items.push(item?);
        }
        Ok(items)
    }

    fn read_page(&mut self, page: &Value) -> Result<(), Error> {
        let items = match at(page, Some(self.spec.items)) {
            Some(Value::Array(items)) => items.clone(),
            _ => Vec::new(),
        };
        for item in &items {
            self.buffered
                .push_back(serde_json::from_value(item.clone()).map_err(crate::request::decode_error)?);
        }
        self.done = !self.advance(page, &items);
        Ok(())
    }

    /// Moves to the next page, returning whether there is one.
    fn advance(&mut self, page: &Value, items: &[Value]) -> bool {
        let spec = self.spec;
        if items.is_empty() || at(page, spec.has_more) == Some(&Value::Bool(false)) {
            return false;
        }
        let current = self.param.as_ref().and_then(Value::as_i64).unwrap_or(0);
        match spec.style {
            Style::Cursor => {
                let next = match spec.item_cursor {
                    Some(field) => items.last().and_then(|item| item.get(field)),
                    None => at(page, spec.next_cursor),
                };
                match next {
                    Some(Value::String(next))
                        if !next.is_empty() && self.param.as_ref() != Some(&next.clone().into()) =>
                    {
                        self.param = Some(next.clone().into());
                        true
                    }
                    _ => false,
                }
            }
            Style::Page => {
                self.param = Some((current + 1).into());
                let total_pages = at(page, spec.total_pages).and_then(Value::as_i64);
                total_pages.is_none_or(|total| current - spec.first_page + 1 < total)
            }
            Style::Offset => {
                let offset = current + items.len() as i64;
                self.param = Some(offset.into());
                let total = at(page, spec.total).and_then(Value::as_i64);
                total.is_none_or(|total| offset < total)
            }
        }
    }
}

fn at<'v>(mut value: &'v Value, path: Option<&[&str]>) -> Option<&'v Value> {
    for key in path? {
        value = value.get(key)?;
    }
    Some(value)
}
