// this file is @generated by Perseid; edit the shared runtime template.
//! Request building, retries and response decoding.
#![allow(dead_code)]

use std::{
    fmt,
    hash::{BuildHasher as _, Hasher as _},
    time::{Duration, SystemTime},
};

use bytes::Bytes;
use http1::{
    header::{CONTENT_LENGTH, CONTENT_TYPE, RETRY_AFTER, USER_AGENT},
    HeaderMap, HeaderName, HeaderValue, Method, StatusCode,
};
use percent_encoding::{utf8_percent_encode, AsciiSet, CONTROLS};
use serde::de::DeserializeOwned;

use crate::api::{
    auth_schemes::Security,
    middleware::{BoxError, Next, Request as MiddlewareRequest, Response},
    upload::{Multipart, RequestBody},
    EventStream, Upload,
};
use crate::{error::Error, Configuration};

const IDEMPOTENCY_KEY: &str = "idempotency-key";
const MAX_RETRY_AFTER: Duration = Duration::from_secs(60);

/// A request that got no usable API response. The crate's `Error` is built from it.
#[derive(Debug)]
#[non_exhaustive]
pub(crate) enum Failure {
    /// The request could not be built: an invalid header, URL or body.
    Request(BoxError),
    /// No response within the configured timeout.
    Timeout,
    /// Connecting, sending or reading the response failed.
    Transport(BoxError),
    /// The response body does not match the expected type.
    Decode(BoxError),
}

impl fmt::Display for Failure {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Request(error) => write!(f, "invalid request: {error}"),
            Self::Timeout => f.write_str("request timed out"),
            Self::Transport(error) => write!(f, "transport error: {error}"),
            Self::Decode(error) => write!(f, "unexpected response body: {error}"),
        }
    }
}

impl std::error::Error for Failure {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Request(error) | Self::Transport(error) | Self::Decode(error) => Some(&**error),
            Self::Timeout => None,
        }
    }
}

pub(crate) fn request_error(error: impl Into<BoxError>) -> Error {
    Error::generic(Failure::Request(error.into()))
}

pub(crate) fn transport_error(error: impl Into<BoxError>) -> Error {
    Error::generic(Failure::Transport(error.into()))
}

pub(crate) fn decode_error(error: impl Into<BoxError>) -> Error {
    Error::generic(Failure::Decode(error.into()))
}

enum ResponseBody {
    Buffered(Bytes),
    Events(EventStream),
}

/// How one attempt ended, before deciding whether to retry.
enum Attempt {
    Done(ResponseBody),
    Status(StatusCode, HeaderMap, Bytes),
    Failed(Failure),
}

impl Attempt {
    fn retryable(&self) -> bool {
        match self {
            Self::Done(_) | Self::Failed(Failure::Request(_) | Failure::Decode(_)) => false,
            Self::Failed(Failure::Timeout | Failure::Transport(_)) => true,
            Self::Status(status, ..) => {
                matches!(status.as_u16(), 408 | 429) || status.is_server_error()
            }
        }
    }

    fn retry_after(&self) -> Option<Duration> {
        let Self::Status(_, headers, _) = self else {
            return None;
        };
        let header = |name: &str| headers.get(name)?.to_str().ok();
        let delay = if let Some(ms) = header("retry-after-ms") {
            Duration::try_from_secs_f64(ms.trim().parse::<f64>().ok()? / 1000.0).ok()?
        } else {
            let value = header(RETRY_AFTER.as_str())?.trim();
            match value.parse::<u64>() {
                Ok(seconds) => Duration::from_secs(seconds),
                Err(_) => httpdate(value)?.duration_since(SystemTime::now()).ok()?,
            }
        };
        (delay <= MAX_RETRY_AFTER).then_some(delay)
    }

    fn into_error(self) -> Error {
        match self {
            Self::Done(_) => unreachable!("a successful attempt is not an error"),
            Self::Status(status, headers, body) => Error::from_response(status, headers, body),
            Self::Failed(failure) => Error::generic(failure),
        }
    }
}

/// HTTP request builder with retry logic.
pub(crate) struct Request {
    method: Method,
    path: &'static str,
    query_params: Vec<(&'static str, String)>,
    path_params: Vec<(&'static str, String)>,
    headers: HeaderMap,
    serialized_body: Option<Bytes>,
    body_is_form: bool,
    upload: Option<Upload>,
    multipart: Option<Multipart>,
    error: Option<Error>,
    security: Option<Security>,
}

impl Request {
    pub fn new(method: Method, path: &'static str) -> Self {
        Request {
            method,
            path,
            query_params: Vec::new(),
            path_params: Vec::new(),
            headers: HeaderMap::new(),
            serialized_body: None,
            body_is_form: false,
            upload: None,
            multipart: None,
            error: None,
            security: None,
        }
    }

    fn fail(&mut self, error: impl Into<BoxError>) {
        self.error.get_or_insert_with(|| request_error(error));
    }

    pub fn with_body_param<T: serde::Serialize>(mut self, param: T) -> Self {
        match serde_json::to_vec(&param) {
            Ok(body) => self.serialized_body = Some(body.into()),
            Err(error) => self.fail(error),
        }
        self
    }

    pub fn with_optional_body_param<T: serde::Serialize>(self, param: Option<T>) -> Self {
        match param {
            Some(body) => self.with_body_param(body),
            None => self,
        }
    }

    pub fn with_form_body_param<T: serde::Serialize>(mut self, param: T) -> Self {
        match serde_urlencoded::to_string(&param) {
            Ok(body) => self.serialized_body = Some(body.into()),
            Err(error) => self.fail(error),
        }
        self.body_is_form = true;
        self
    }

    pub fn with_upload_body(mut self, body: Option<Upload>) -> Self {
        self.upload = body;
        self
    }

    pub fn with_multipart_body(mut self, body: Option<Multipart>) -> Self {
        self.multipart = body;
        self
    }

    /// Overrides the API-wide security requirement.
    pub fn with_security(mut self, security: Security) -> Self {
        self.security = Some(security);
        self
    }

    pub fn with_header_param(mut self, name: &'static str, value: String) -> Self {
        let name = HeaderName::from_bytes(name.as_bytes());
        match name.map_err(BoxError::from).and_then(|name| {
            let value = HeaderValue::try_from(value)?;
            Ok((name, value))
        }) {
            Ok((name, value)) => {
                self.headers.insert(name, value);
            }
            Err(error) => self.fail(error),
        }
        self
    }

    pub fn with_optional_header_param(self, name: &'static str, value: Option<String>) -> Self {
        match value {
            Some(value) => self.with_header_param(name, value),
            None => self,
        }
    }

    pub fn with_query_param(mut self, name: &'static str, param: impl QueryParamValue) -> Self {
        self.query_params.push((name, param.encode()));
        self
    }

    pub fn with_optional_query_param(
        self,
        name: &'static str,
        param: Option<impl QueryParamValue>,
    ) -> Self {
        match param {
            Some(value) => self.with_query_param(name, value),
            None => self,
        }
    }

    /// Repeats the parameter for each value (OpenAPI `explode: true`): `?tag=a&tag=b`.
    pub fn with_exploded_query_param<T: QueryParamValue>(
        mut self,
        name: &'static str,
        values: Vec<T>,
    ) -> Self {
        for value in values {
            self.query_params.push((name, value.encode()));
        }
        self
    }

    pub fn with_optional_exploded_query_param<T: QueryParamValue>(
        self,
        name: &'static str,
        values: Option<Vec<T>>,
    ) -> Self {
        match values {
            Some(values) => self.with_exploded_query_param(name, values),
            None => self,
        }
    }

    pub fn with_path_param(mut self, name: &'static str, value: impl fmt::Display) -> Self {
        self.path_params.push((name, value.to_string()));
        self
    }

    pub async fn execute<T: DeserializeOwned>(self, conf: &Configuration) -> Result<T, Error> {
        let bytes = self.execute_bytes(conf).await?;
        serde_json::from_slice(&bytes).map_err(decode_error)
    }

    /// Runs a request whose response has no body worth decoding.
    pub async fn execute_empty(self, conf: &Configuration) -> Result<(), Error> {
        self.execute_bytes(conf).await.map(drop)
    }

    pub async fn execute_binary(self, conf: &Configuration) -> Result<Bytes, Error> {
        self.execute_bytes(conf).await
    }

    pub async fn execute_text(self, conf: &Configuration) -> Result<String, Error> {
        let bytes = self.execute_bytes(conf).await?;
        String::from_utf8(bytes.into()).map_err(decode_error)
    }

    pub async fn execute_event_stream(
        mut self,
        conf: &Configuration,
    ) -> Result<EventStream, Error> {
        self.headers.insert(
            http1::header::ACCEPT,
            HeaderValue::from_static("text/event-stream"),
        );
        match self.send(conf, true).await? {
            ResponseBody::Events(stream) => Ok(stream),
            ResponseBody::Buffered(_) => unreachable!("event streams are never buffered"),
        }
    }

    async fn execute_bytes(self, conf: &Configuration) -> Result<Bytes, Error> {
        match self.send(conf, false).await? {
            ResponseBody::Buffered(body) => Ok(body),
            ResponseBody::Events(_) => unreachable!("only event streams are streamed"),
        }
    }

    async fn send(mut self, conf: &Configuration, event_stream: bool) -> Result<ResponseBody, Error> {
        if let Some(error) = self.error.take() {
            return Err(error);
        }
        let token = conf.bearer_access_token.as_deref().filter(|t| !t.is_empty());
        let auth = conf.credentials.apply(self.security, token).await?;
        self.query_params.extend(auth.query);
        for (name, value) in auth.headers {
            let name = HeaderName::from_bytes(name.as_bytes()).map_err(request_error)?;
            let mut value = HeaderValue::try_from(value).map_err(request_error)?;
            value.set_sensitive(true);
            self.headers.insert(name, value);
        }
        if self.method == Method::POST && !self.headers.contains_key(IDEMPOTENCY_KEY) {
            let key = format!("auto_{}", uuid::Uuid::new_v4());
            self.headers
                .insert(IDEMPOTENCY_KEY, HeaderValue::try_from(key).map_err(request_error)?);
        }
        self.headers.insert(
            "@@HEADER_PREFIX@@-req-id",
            HeaderValue::from(random() as u32),
        );
        // Retrying a non-idempotent request without a key could apply it twice.
        let idempotent = self.method.is_idempotent() || self.headers.contains_key(IDEMPOTENCY_KEY);
        let replayable = self.upload.as_ref().is_none_or(Upload::replayable)
            && self.multipart.as_ref().is_none_or(Multipart::replayable);
        let max_retries = match &conf.retry_schedule {
            Some(schedule) => schedule.len(),
            None => conf.num_retries as usize,
        };
        let mut retries = 0;
        loop {
            let attempt = self.attempt(conf, event_stream).await;
            if let Attempt::Done(body) = attempt {
                return Ok(body);
            }
            if !(idempotent && replayable && attempt.retryable()) || retries >= max_retries {
                return Err(attempt.into_error());
            }
            let delay = attempt
                .retry_after()
                .unwrap_or_else(|| backoff(conf, retries));
            tokio::time::sleep(delay).await;
            retries += 1;
            self.headers
                .insert("@@HEADER_PREFIX@@-retry-count", HeaderValue::from(retries));
        }
    }

    async fn attempt(&mut self, conf: &Configuration, event_stream: bool) -> Attempt {
        let mut request = match self.build_request(conf) {
            Ok(request) => request,
            Err(error) => return Attempt::Failed(Failure::Request(error)),
        };
        let exchange = async {
            let body = request.body_mut().validate_empty().await;
            body.map_err(|error| Failure::Request(error.into()))?;
            let response = Next::new(&conf.middleware, &*conf.client)
                .run(MiddlewareRequest(request))
                .await
                .map_err(Failure::Transport)?;
            let status = response.status();
            if status.is_success() && event_stream {
                return open_event_stream(response).map(Attempt::Done);
            }
            let (status, headers, body) =
                response.into_parts().await.map_err(Failure::Transport)?;
            Ok(match status.is_success() {
                true => Attempt::Done(ResponseBody::Buffered(body)),
                false => Attempt::Status(status, headers, body),
            })
        };
        let result = match conf.timeout {
            Some(timeout) => tokio::time::timeout(timeout, exchange)
                .await
                .unwrap_or(Err(Failure::Timeout)),
            None => exchange.await,
        };
        result.unwrap_or_else(Attempt::Failed)
    }

    fn build_request(
        &mut self,
        conf: &Configuration,
    ) -> Result<http1::Request<RequestBody>, BoxError> {
        const FRAGMENT: &AsciiSet = &CONTROLS.add(b' ').add(b'"').add(b'<').add(b'>').add(b'`');
        const PATH: &AsciiSet = &FRAGMENT.add(b'#').add(b'?').add(b'{').add(b'}');
        const PATH_SEGMENT: &AsciiSet = &PATH.add(b'/').add(b'%');

        let mut path = self.path.to_owned();
        for (name, value) in &self.path_params {
            let value = utf8_percent_encode(value, PATH_SEGMENT).to_string();
            path = path.replace(&format!("{{{name}}}"), &value);
        }
        let mut uri = format!("{}{path}", conf.base_path.trim_end_matches('/'));
        if !self.query_params.is_empty() {
            let mut query = url::form_urlencoded::Serializer::new(String::new());
            for (name, value) in &self.query_params {
                query.append_pair(name, value);
            }
            uri.push('?');
            uri.push_str(&query.finish());
        }

        let (body, content_type) = if let Some(form) = &mut self.multipart {
            (form.body()?, Some(form.content_type()))
        } else if let Some(upload) = &mut self.upload {
            (upload.body()?, Some("application/octet-stream".to_owned()))
        } else if let Some(body) = &self.serialized_body {
            let content_type = match self.body_is_form {
                true => "application/x-www-form-urlencoded",
                false => "application/json",
            };
            (Upload::bytes(body.clone()).body()?, Some(content_type.to_owned()))
        } else {
            (RequestBody::empty(), None)
        };

        let length = body.length();
        let mut request = http1::Request::builder()
            .method(self.method.clone())
            .uri(uri)
            .body(body)?;
        let headers = request.headers_mut();
        if let Some(content_type) = content_type {
            headers.insert(CONTENT_TYPE, HeaderValue::try_from(content_type)?);
            if let Some(length) = length {
                headers.insert(CONTENT_LENGTH, length.into());
            }
        }
        if let Some(user_agent) = &conf.user_agent {
            headers.insert(USER_AGENT, HeaderValue::try_from(user_agent)?);
        }
        for (name, value) in &self.headers {
            headers.insert(name, value.clone());
        }
        Ok(request)
    }
}

fn open_event_stream(response: Response) -> Result<ResponseBody, Failure> {
    let content_type = response
        .headers()
        .get(CONTENT_TYPE)
        .and_then(|value| value.to_str().ok())
        .and_then(|value| value.split(';').next())
        .unwrap_or_default()
        .trim();
    if !content_type.eq_ignore_ascii_case("text/event-stream") {
        return Err(Failure::Decode(
            format!("expected a text/event-stream response, got `{content_type}`").into(),
        ));
    }
    match response.into_upstream() {
        Some(body) => Ok(ResponseBody::Events(EventStream::new(body))),
        None => Err(Failure::Transport(
            "middleware cannot buffer an event stream".into(),
        )),
    }
}

/// Exponential backoff from 500ms up to 8s with jitter, unless a schedule is configured.
fn backoff(conf: &Configuration, retries: usize) -> Duration {
    if let Some(delay) = conf.retry_schedule.as_ref().and_then(|s| s.get(retries)) {
        return *delay;
    }
    let delay = Duration::from_millis(500) * 2u32.saturating_pow(retries as u32);
    let jitter = 1.0 - (random() % 1000) as f64 / 4000.0;
    delay.min(Duration::from_secs(8)).mul_f64(jitter)
}

/// Randomness for request ids and jitter, without a dependency.
fn random() -> u64 {
    let mut hasher = std::collections::hash_map::RandomState::new().build_hasher();
    hasher.write_u128(
        SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos(),
    );
    hasher.finish()
}

/// Parses an IMF-fixdate (`Sun, 06 Nov 1994 08:49:37 GMT`), the form `Retry-After` uses.
fn httpdate(value: &str) -> Option<SystemTime> {
    let mut parts = value.split_whitespace().skip(1);
    let day: u64 = parts.next()?.parse().ok()?;
    let month = [
        "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
    ]
    .iter()
    .position(|m| Some(*m) == parts.next())? as u64
        + 1;
    let year: u64 = parts.next()?.parse().ok()?;
    let mut time = parts.next()?.split(':').map(|n| n.parse::<u64>().ok());
    let (h, m, s) = (time.next()??, time.next()??, time.next()??);
    // Days since 1970-01-01, from Howard Hinnant's `days_from_civil`.
    let (y, mo) = if month <= 2 { (year - 1, month + 9) } else { (year, month - 3) };
    let era = y / 400;
    let yoe = y - era * 400;
    let doy = (153 * mo + 2) / 5 + day - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    let days = (era * 146_097 + doe).checked_sub(719_468)?;
    let seconds = days * 86_400 + h * 3600 + m * 60 + s;
    Some(SystemTime::UNIX_EPOCH + Duration::from_secs(seconds))
}

pub(crate) trait QueryParamValue {
    fn encode(&self) -> String;
}

macro_rules! impl_query_param_value {
    ($($ty:ty),*) => {
        $(impl QueryParamValue for $ty {
            fn encode(&self) -> String {
                self.to_string()
            }
        })*
    };
}

impl_query_param_value!(bool, i16, u16, i32, u32, i64, u64, f32, f64, String, &str);

impl QueryParamValue for rust_decimal::Decimal {
    fn encode(&self) -> String {
        self.to_string()
    }
}

/// A comma-separated list (OpenAPI `explode: false`).
impl<T: QueryParamValue> QueryParamValue for Vec<T> {
    fn encode(&self) -> String {
        self.iter().map(T::encode).collect::<Vec<_>>().join(",")
    }
}
