// this file is @generated by Perseid; edit the shared runtime template.
package @@PACKAGE_NAME@@

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"
)

// Webhook verifies and signs webhook payloads following the Standard Webhooks
// specification (https://www.standardwebhooks.com). The legacy svix-* headers
// are accepted too; the webhook-* ones win when both are present.
//
//	wh, err := @@PACKAGE_NAME@@.NewWebhook(os.Getenv("WEBHOOK_SECRET"))
//	if err != nil {
//		return err
//	}
//	if err := wh.Verify(body, r.Header); err != nil {
//		http.Error(w, "invalid signature", http.StatusBadRequest)
//		return
//	}
type Webhook struct {
	key []byte
}

// WebhookSecretPrefix is the optional prefix of webhook signing secrets.
const WebhookSecretPrefix = "whsec_"

// WebhookTolerance is how far the signed timestamp may drift from the current time.
const WebhookTolerance = 5 * time.Minute

// Errors returned by Webhook.Verify.
var (
	ErrWebhookMissingHeaders      = errors.New("@@PACKAGE_NAME@@: missing webhook signature headers")
	ErrWebhookInvalidTimestamp    = errors.New("@@PACKAGE_NAME@@: invalid webhook timestamp header")
	ErrWebhookTimestampTooOld     = errors.New("@@PACKAGE_NAME@@: webhook timestamp is too old")
	ErrWebhookTimestampTooNew     = errors.New("@@PACKAGE_NAME@@: webhook timestamp is too far in the future")
	ErrWebhookNoMatchingSignature = errors.New("@@PACKAGE_NAME@@: no matching webhook signature")
)

var (
	webhookIDHeaders        = []string{"webhook-id", "svix-id"}
	webhookTimestampHeaders = []string{"webhook-timestamp", "svix-timestamp"}
	webhookSignatureHeaders = []string{"webhook-signature", "svix-signature"}
)

// NewWebhook builds a verifier from the signing secret: base64, with or without
// the "whsec_" prefix.
func NewWebhook(secret string) (*Webhook, error) {
	key, err := base64.StdEncoding.DecodeString(strings.TrimPrefix(secret, WebhookSecretPrefix))
	if err != nil {
		return nil, fmt.Errorf("@@PACKAGE_NAME@@: webhook secret is not valid base64: %w", err)
	}
	if len(key) == 0 {
		return nil, errors.New("@@PACKAGE_NAME@@: webhook secret is empty")
	}
	return &Webhook{key: key}, nil
}

// NewWebhookRaw builds a verifier from an already decoded signing key.
func NewWebhookRaw(key []byte) *Webhook {
	return &Webhook{key: append([]byte(nil), key...)}
}

// Verify checks a payload's signature and that it was signed within
// WebhookTolerance. payload must be the exact request body, before any parsing.
func (w *Webhook) Verify(payload []byte, headers http.Header) error {
	msgID := firstHeader(headers, webhookIDHeaders)
	msgTimestamp := firstHeader(headers, webhookTimestampHeaders)
	msgSignature := firstHeader(headers, webhookSignatureHeaders)
	if msgID == "" || msgTimestamp == "" || msgSignature == "" {
		return ErrWebhookMissingHeaders
	}

	seconds, err := strconv.ParseInt(msgTimestamp, 10, 64)
	if err != nil {
		return ErrWebhookInvalidTimestamp
	}
	timestamp := time.Unix(seconds, 0)
	now := time.Now()
	if timestamp.Before(now.Add(-WebhookTolerance)) {
		return ErrWebhookTimestampTooOld
	}
	if timestamp.After(now.Add(WebhookTolerance)) {
		return ErrWebhookTimestampTooNew
	}

	expected := w.signature(msgID, seconds, payload)
	for _, part := range strings.Fields(msgSignature) {
		version, signature, ok := strings.Cut(part, ",")
		if ok && version == "v1" && hmac.Equal([]byte(signature), []byte(expected)) {
			return nil
		}
	}
	return ErrWebhookNoMatchingSignature
}

// Sign returns the value of the webhook-signature header for a payload.
func (w *Webhook) Sign(msgID string, timestamp time.Time, payload []byte) string {
	return "v1," + w.signature(msgID, timestamp.Unix(), payload)
}

func (w *Webhook) signature(msgID string, timestamp int64, payload []byte) string {
	mac := hmac.New(sha256.New, w.key)
	mac.Write([]byte(msgID + "." + strconv.FormatInt(timestamp, 10) + "."))
	mac.Write(payload)
	return base64.StdEncoding.EncodeToString(mac.Sum(nil))
}

func firstHeader(headers http.Header, names []string) string {
	for _, name := range names {
		if value := strings.Join(headers.Values(name), " "); value != "" {
			return value
		}
	}
	return ""
}
