// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_PACKAGE@@.exceptions;

import java.io.IOException;

/** The request failed without a response, after its retries: connection, TLS or I/O error. */
public class ApiConnectionException extends @@CLIENT_NAME@@Exception {
    private static final long serialVersionUID = 1L;

    /**
     * An exception for a failed request.
     *
     * @param cause the I/O error
     */
    public ApiConnectionException(IOException cause) {
        super(String.valueOf(cause.getMessage()), cause);
    }

    @Override
    public synchronized IOException getCause() {
        return (IOException) super.getCause();
    }
}
