// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_PACKAGE@@.exceptions;

/** A 409 Conflict response. */
public class ConflictException extends ApiException {
    private static final long serialVersionUID = 1L;

    public ConflictException(String message, int code, String responseBody) {
        super(message, code, responseBody);
    }
}
