// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_PACKAGE@@.exceptions;

/**
 * A response the SDK cannot read: a body that is not the JSON the API describes, a required
 * property it left out, or another content type than announced.
 */
public class InvalidDataException extends @@CLIENT_NAME@@Exception {
    private static final long serialVersionUID = 1L;

    /**
     * An exception for unreadable data.
     *
     * @param message what is wrong with the data
     */
    public InvalidDataException(String message) {
        super(message);
    }

    /**
     * An exception for unreadable data.
     *
     * @param message what is wrong with the data
     * @param cause the decoding error
     */
    public InvalidDataException(String message, Throwable cause) {
        super(message, cause);
    }
}
