// this file is @generated by Perseid; edit the shared runtime template.
package @@JAVA_PACKAGE@@.exceptions;

/** A 429 Too Many Requests response, returned once the retries are spent. */
public class RateLimitException extends ApiException {
    private static final long serialVersionUID = 1L;

    public RateLimitException(String message, int code, String responseBody) {
        super(message, code, responseBody);
    }
}
