from __future__ import annotations

from contextlib import contextmanager
import json
from pathlib import Path
import re
import tempfile

from .common import run, write
from .sources import git_url, locked
from .workspace import checkout, groups, render


def github_repo(url):
    match = re.fullmatch(
        r"(?:https://github\.com/|git@github\.com:)([\w.-]+/[\w.-]+?)(?:\.git)?/?", url
    )
    if not match:
        raise ValueError(f"GitHub delivery requires a github.com repository: {url}")
    return match[1]


def repository_url(project, repository):
    if repository == ".":
        return run(
            ["git", "remote", "get-url", "origin"], cwd=project.root, capture=True
        ).strip()
    return git_url(repository, project.root)


@contextmanager
def delivery_checkout(project, repository, names):
    with tempfile.TemporaryDirectory(prefix="perseid-delivery-") as directory:
        root = Path(directory) / "repo"
        checkout(project, repository_url(project, repository), names, root)
        yield root


def git_output(root, *args):
    return run(["git", *args], cwd=root, capture=True).strip()


def tracked_changes(root):
    run(["git", "add", "--all"], cwd=root)
    return git_output(root, "diff", "--cached", "--name-only")


def copy_control_files(project, root):
    for source in (
        project.path,
        project.snapshot,
        project.lock_path,
        project.versions_path,
    ):
        if source.exists():
            write(root / source.relative_to(project.root), source.read_bytes())


def propose(project, names, *, dry_run=False):
    lock = locked(project)
    results = []
    # Resolve every repo and validate all checks before the first push/PR.
    from contextlib import ExitStack

    with ExitStack() as stack:
        pending = []
        destinations = groups(project, names)
        # A stable branch represents the complete update for a repository, so a
        # target filter must not discard another target's pending PR changes.
        all_destinations = groups(project, [])
        destinations = {repo: all_destinations[repo] for repo in destinations}
        # The controller's spec/lock/version metadata needs review even when all
        # SDK targets live in other repositories.
        destinations.setdefault(".", [])
        for repository, selected in destinations.items():
            repo = github_repo(repository_url(project, repository))
            root = stack.enter_context(delivery_checkout(project, repository, selected))
            base = git_output(root, "branch", "--show-current")
            branch = f"perseid/{project.data['name']}/update"
            if base == branch:
                raise ValueError("The update branch cannot also be the base branch")
            if repository == ".":
                copy_control_files(project, root)
            render(project, root, selected, lock, checks=True)
            paths = tracked_changes(root)
            title = f"Update {project.data['name']} SDKs"
            body = "Generated by Perseid from the committed spec snapshot.\n\n"
            body += f"Spec SHA-256: `{lock['spec_sha256']}`\n\n"
            body += (
                "Targets: "
                + ", ".join(selected)
                + ".\n\nConfigured SDK checks passed.\n"
            )
            pending.append((root, repo, base, branch, title, body, paths.splitlines()))
        for root, repo, base, branch, title, body, paths in pending:
            if dry_run:
                results.append(
                    {
                        "repository": repo,
                        "base": base,
                        "branch": branch,
                        "changed": paths,
                    }
                )
                continue
            existing = json.loads(
                run(
                    [
                        "gh",
                        "pr",
                        "list",
                        "--repo",
                        repo,
                        "--head",
                        branch,
                        "--base",
                        base,
                        "--state",
                        "open",
                        "--json",
                        "number,url",
                    ],
                    capture=True,
                )
            )
            remote = git_output(
                root, "ls-remote", "--heads", "origin", f"refs/heads/{branch}"
            )
            expected = remote.split()[0] if remote else ""
            # The branch is reserved for this project. If somebody has added
            # unrelated commits, require review instead of silently replacing them.
            if expected:
                run(
                    ["git", "fetch", "--quiet", "origin", f"refs/heads/{branch}"],
                    cwd=root,
                )
                subject = git_output(root, "show", "-s", "--format=%s", expected)
                marker = git_output(root, "show", "-s", "--format=%B", expected)
                if (
                    subject != title
                    or f"Perseid-Project: {project.data['name']}"
                    not in marker.splitlines()
                ):
                    raise ValueError(
                        f"Reserved branch {branch} contains a non-Perseid commit"
                    )
                staged_tree = git_output(root, "write-tree")
                if (
                    staged_tree == git_output(root, "rev-parse", f"{expected}^{{tree}}")
                    and existing
                    and paths
                ):
                    results.append(
                        {"repository": repo, "changed": [], "pr": existing[0]["url"]}
                    )
                    continue
            if not paths:
                if existing:
                    run(
                        [
                            "gh",
                            "pr",
                            "close",
                            str(existing[0]["number"]),
                            "--repo",
                            repo,
                        ]
                    )
                results.append({"repository": repo, "changed": [], "pr": None})
                continue
            run(
                [
                    "git",
                    "-c",
                    "user.name=perseid[bot]",
                    "-c",
                    "user.email=perseid@users.noreply.github.com",
                    "commit",
                    "--quiet",
                    "-m",
                    title,
                    "-m",
                    f"Perseid-Project: {project.data['name']}",
                ],
                cwd=root,
            )
            run(
                [
                    "git",
                    "push",
                    f"--force-with-lease=refs/heads/{branch}:{expected}",
                    "origin",
                    f"HEAD:refs/heads/{branch}",
                ],
                cwd=root,
            )
            body_file = root.parent / "pr-body.md"
            body_file.write_text(body)
            if existing:
                run(
                    [
                        "gh",
                        "pr",
                        "edit",
                        str(existing[0]["number"]),
                        "--repo",
                        repo,
                        "--title",
                        title,
                        "--body-file",
                        body_file,
                    ]
                )
                url = existing[0]["url"]
            else:
                url = run(
                    [
                        "gh",
                        "pr",
                        "create",
                        "--repo",
                        repo,
                        "--base",
                        base,
                        "--head",
                        branch,
                        "--title",
                        title,
                        "--body-file",
                        body_file,
                    ],
                    capture=True,
                ).strip()
            results.append({"repository": repo, "changed": paths, "pr": url})
    return results
